#
# Recursive make - makes the subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS =  $(GENERAL_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	scripts \
	tdrp \
	procmap \
	didss \
	dsserver \
	filters \
        rvp8

include $(RAP_MAKE_INC_DIR)/rap_make_recursive_dir_targets








