#
# Recursive make - makes the subdirectory code
#

include $(LROSE_MAKE_INC_DIR)/lrose_make_macros

TARGETS =  $(GENERAL_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	Radx \
	radar \
	tdrp

include $(LROSE_MAKE_INC_DIR)/lrose_make_recursive_dir_targets








