#
# Recursive make - makes the subdirectory code
#

include $(LROSE_MAKE_INC_DIR)/lrose_make_macros

TARGETS =  $(GENERAL_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	tdrp \
	procmap \
	titan \
	titan_analysis \
	trec \
	didss \
	ingest \
	dsserver \
	mdv_utils \
        physics \
        satApps \
	spdb_utils \
	filedist \
	filters \
        awc \
	hydro \
	interp \
	radar \
	refractt \
        Radx

include $(LROSE_MAKE_INC_DIR)/lrose_make_recursive_dir_targets








