#
# makefile as template for configure
# does not include scripts
#

include $(LROSE_MAKE_INC_DIR)/lrose_make_macros

TARGETS =  $(GENERAL_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	tdrp

include $(LROSE_MAKE_INC_DIR)/lrose_make_recursive_dir_targets
