#
# Recursive make - makes the AWC subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS =  $(GENERAL_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	tdrp \
	awc \
	cidd \
	didss \
	dsserver \
	filters \
	ingest \
	mdv_utils \
	procmap \
	prod_sel98 \
	scripts \
	servmap \
	spdb_server \
	titan 

$(TARGETS): FORCE
	$(MAKE) $(SUB_DIRS) TARGET=$@

$(SUB_DIRS): FORCE
	cd $@; $(MAKE) $(TARGET)

FORCE:







