#
# Recursive make - makes the subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS =  $(GENERAL_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	scripts \
	procmap \
	servmap \
	tdrp \
	cidd \
	didss \
	dsserver \
	filters \
	grib \
	mdv_utils

include $(RAP_MAKE_INC_DIR)/rap_make_recursive_dir_targets








