#
# Recursive make - makes the subdirectory code
#

include $(LROSE_CORE_DIR)/build/make_include/lrose_make_macros

TARGETS =  $(GENERAL_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	tdrp \
	Radx

include $(LROSE_CORE_DIR)/build/make_include/lrose_make_recursive_dir_targets








