#
# Recursive make - makes the subdirectory code
#

include $(LROSE_MAKE_INC_DIR)/lrose_make_macros

TARGETS =  $(GENERAL_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	scripts \
	tdrp \
	procmap \
	titan \
	titan_analysis \
	didss \
	ingest \
	dsserver \
	mdv_utils \
	spdb_utils \
	filters \
        awc \
	radar \
        Radx

include $(LROSE_MAKE_INC_DIR)/lrose_make_recursive_dir_targets








