#
# Recursive make - makes the subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS =  $(GENERAL_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	tdrp \
	trec \
	mdv_utils \
	ingest \
	dsserver \
	didss \
	titan \
	satApps \
	procmap \
	filters \
	mm5 \
	spdb_utils \
	scripts

include $(RAP_MAKE_INC_DIR)/rap_make_recursive_dir_targets





