#
# Recursive make - makes the subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS =  $(GENERAL_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

#	awc \
#	mm5 \
#	titan \
#	trec

SUB_DIRS = \
	cidd \
	didss \
	dsserver \
	filters \
	mdv_utils \
	niwot \
	procmap \
	scripts \
	tdrp

$(TARGETS): FORCE
	$(MAKE) $(SUB_DIRS) TARGET=$@

$(SUB_DIRS): FORCE
	cd $@; $(MAKE) $(TARGET)

FORCE:







