#
# makefile as template for configure, for hcr
# does not include scripts
#

include $(LROSE_CORE_DIR)/build/make_include/lrose_make_macros

TARGETS =  $(GENERAL_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	tdrp \
	procmap \
	didss \
	dsserver \
	filters \
	radar \
        Radx

include $(LROSE_CORE_DIR)/build/make_include/lrose_make_recursive_dir_targets








