#
# Recursive make - makes the subdirectory code
#

include $(LROSE_CORE_DIR)/build/make_include/lrose_make_macros

TARGETS = $(GENERAL_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	CaseStats \
	DistFit \
	PartialProps \
	StormModel \
	TimeProps \
	TrackGridStats \
	TrackMatch \
	TrackProps \
	Tracks2Ascii \
	VerifyTracks \
	grid_forecast \
	storms_to_ascii \
	storms_to_tifs \
	test_tserver \
	track_print \
	verify_day \
	verify_grid \
	verify_tracks

include $(LROSE_CORE_DIR)/build/make_include/lrose_make_recursive_dir_targets
