#*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
# Copyright (c) 1995, UCAR
# University Corporation for Atmospheric Research(UCAR)
# National Center for Atmospheric Research(NCAR)
# Research Applications Program(RAP)
# P.O.Box 3000, Boulder, Colorado, 80307-3000, USA
# All rights reserved. Licenced use only.
# Do not copy or distribute without authorization
# Tue 1 Jul 19103 21:25:40 UTC
#*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*

###########################################################################
#
# Makefile
#
# RAP, NCAR, Boulder, CO, 80307, USA
#
# January 2004
#
###########################################################################

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGET_FILE = readWindtracer

LOC_INCLUDES = 
LOC_CFLAGS = 
FFLAGS =

#
LOC_CPPC_CFLAGS = 
#
DEBUG_FLAG =
LOC_LDFLAGS = 

LOC_LIBS = -lnetcdf 

FC =  g77

HDRS = 	

F_SRCS = \
readWindtracer.f





CPPC_SRCS = readNetcdf.cc
	    

              

#
# standard targets
#

include $(RAP_MAKE_INC_DIR)/rap_make_f_targets


              
#
# local targets
#

depend: depend_generic

# DO NOT DELETE THIS LINE -- make depend depends on it.








