#
# Recursive make - makes the subdirectory code
#

include $(LROSE_MAKE_INC_DIR)/lrose_make_macros

TARGETS = $(GENERAL_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	ApRemoval \
	BrightBand \
	ClutterRemove \
	LogFilter \
	NoiseFilter \
	stratiform_filter \
	tops_filter

include $(LROSE_MAKE_INC_DIR)/lrose_make_recursive_dir_targets
