#
# Recursive make - makes the subdirectory code
#

include $(LROSE_MAKE_INC_DIR)/lrose_make_macros

TARGETS = $(GENERAL_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	Fmq2Fmq \
	Fmq2MultMsgFmq \
	FmqMon \
	InputWatcher \
	Janitor \
	LdataInformer \
	LdataWatcher \
	LdataMultWatcher \
	LdataWriter \
	MultMsgFmq2Fmq \
	RadMon \
	Scout \
	TimeCalc \
	fmq_print

include $(LROSE_MAKE_INC_DIR)/lrose_make_recursive_dir_targets
