/* XPM */
static char *CP2MomentsIcon[] = {
/* columns rows colors chars-per-pixel */
"96 91 3 1",
"  c red",
". c None",
"X c cyan",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXX..............................XXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXX..............................XXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXX............................XXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXX............................XXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXX..........................XXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXX..........................XXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXXX........................XXXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXXX........................XXXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXXX........................XXXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXXXX......................XXXXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXXXX......................XXXXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXXXXX....................XXXXXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXXXXX....................XXXXXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXXXXXX..................XXXXXXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXXXXXX..................XXXXXXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXXXXXX.................XXXXXXXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXX................XXXXXXXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXX................XXXXXXXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXX..............XXXXXXXXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXX..............XXXXXXXXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX............XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX............XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXX........XXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXX........XXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXX......XXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXX......XXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXX....XXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX...XXXXXXXXXXXXXX....XXXXXXXXXXXXX...XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX...XXXXXXXXXXXXXXX..XXXXXXXXXXXXXX...XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXX..XXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXX..XXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX......XXXXXXXXXXXXXXXXXXXXXXXXX......XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX......XXXXXXXXXXXXXXXXXXXXXXXXX......XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX.......XXXXXXXXXXXXXXXXXXXXXXX.......XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX.......XXXXXXXXXXXXXXXXXXXXXXX.......XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX.......XXXXXXXXXXXXXXXXXXXXXXX.......XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX........XXXXXXXXXXXXXXXXXXXXX........XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX........XXXXXXXXXXXXXXXXXXXXX........XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX.........XXXXXXXXXXXXXXXXXXX.........XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX.........XXXXXXXXXXXXXXXXXXX.........XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX.........XXXXXXXXXXXXXXXXXXX.........XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX..........XXXXXXXXXXXXXXXXX..........XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX..........XXXXXXXXXXXXXXXXX..........XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXX........................",
"XXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXX..         .............",
"XXXXXXXXXXXXXXXXX............XXXXXXXXXXXXX............XXXXXXXXXXXXXXXX                ..........",
"XXXXXXXXXXXXXXXXX............XXXXXXXXXXXXX............XXXXXXXXXXXXXX                   .........",
"XXXXXXXXXXXXXXXXX............XXXXXXXXXXXXX............XXXXXXXXXXXXXX                    ........",
"XXXXXXXXXXXXXXXXX.....................................XXXXXXXXXXXXXX                     .......",
"XXXXXXXXXXXXXXXXX.....................................XXXXXXXXXXXXXX                      ......",
"XXXXXXXXXXXXXXXXX.....................................XXXXXXXXXXXXXX                      ......",
"XXXXXXXXXXXXXXXXX.....................................XXXXXXXXXXXXXX      .....            .....",
"XXXXXXXXXXXXXXXXX.....................................XXXXXXXXXXXXXX   X.........          .....",
"XXXXXXXXXXXXXXXXX..         ......................      XXXXXXXXXXXX XXX.........          .....",
"XXXXXXXXXXXXXXXX               .....         ...          XXXXXXXXXXXXXX..........         .....",
"XXXXXXXXXXXXXX                  ....         .             XXXXXXXXXXXXX..........         .....",
"XXXXXXXXXXXXX                   ....                       XXXXXXXXXXXXX..........         .....",
"XXXXXXXXXXXX                    ....                        XXXXXXXXXXXX..........         .....",
"XXXXXXXXXXX                     ....                         XXXXXXXXXXX..........         .....",
"XXXXXXXXXXX           .....     ....           ....          XXXXXXXXXXX.........         ......",
"XXXXXXXXXX          .........   ....         .......         XXXXXXXXXXX.........         ......",
"XXXXXXXXXX         ...........  ....         .......         XXXXXXXXXXX........         .......",
"XXXXXXXXXX         .................         ........         XXXXXXXXXX........         .......",
"XXXXXXXXX         ..................         ........         XXXXXXXXXX.......         ........",
".........         ..................         ........         ................          ........",
".........         ..................         ........         ...............          .........",
".........         ..................         ........         ..............          ..........",
".........         ..................         ........         .............          ...........",
".........         ..................         ........         ............          ............",
".........         ..................         ........         ...........          .............",
".........         ..................         ........         ..........          ..............",
"..........         .................         .......         ..........          ...............",
"..........         ............ ....         .......         .........          ................",
"..........          .........   ....         ......          ........         ..................",
"...........           .....     ....         .....          .......                          ...",
"...........                     ....                        .......                          ...",
"............                    ....                       ........                          ...",
".............                   ....                       ........                          ...",
"..............                  ....                      .........                          ...",
"................               .....         .          ...........                          ...",
"...................         ........         ...      ..........................................",
"....................................         ...................................................",
"....................................         ...................................................",
"....................................         ...................................................",
"....................................         ..................................................."
};
