/* *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* */
/* ** Copyright UCAR (c) 1990 - 2016                                         */
/* ** University Corporation for Atmospheric Research (UCAR)                 */
/* ** National Center for Atmospheric Research (NCAR)                        */
/* ** Boulder, Colorado, USA                                                 */
/* ** BSD licence applies - redistribution and use in source and binary      */
/* ** forms, with or without modification, are permitted provided that       */
/* ** the following conditions are met:                                      */
/* ** 1) If the software is modified to produce derivative works,            */
/* ** such modified software should be clearly marked, so as not             */
/* ** to confuse it with the version available from UCAR.                    */
/* ** 2) Redistributions of source code must retain the above copyright      */
/* ** notice, this list of conditions and the following disclaimer.          */
/* ** 3) Redistributions in binary form must reproduce the above copyright   */
/* ** notice, this list of conditions and the following disclaimer in the    */
/* ** documentation and/or other materials provided with the distribution.   */
/* ** 4) Neither the name of UCAR nor the names of its contributors,         */
/* ** if any, may be used to endorse or promote products derived from        */
/* ** this software without specific prior written permission.               */
/* ** DISCLAIMER: THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS  */
/* ** OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED      */
/* ** WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.    */
/* *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* */
/*
 * read_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `read.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include <devguide/gcm.h>
#include "read_ui.h"

/*
 * Initialize an instance of object `popup1'.
 */
read_popup1_objects *
read_popup1_objects_initialize(ip, owner)
	read_popup1_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (read_popup1_objects *) calloc(1, sizeof (read_popup1_objects))))
		return (read_popup1_objects *) NULL;
	if (!ip->popup1)
		ip->popup1 = read_popup1_popup1_create(ip, owner);
	if (!ip->controls1)
		ip->controls1 = read_popup1_controls1_create(ip, ip->popup1);
	if (!ip->read_directory)
		ip->read_directory = read_popup1_read_directory_create(ip, ip->controls1);
	if (!ip->read_filename)
		ip->read_filename = read_popup1_read_filename_create(ip, ip->controls1);
	if (!ip->read_format)
		ip->read_format = read_popup1_read_format_create(ip, ip->controls1);
	if (!ip->read_button)
		ip->read_button = read_popup1_read_button_create(ip, ip->controls1);
	return ip;
}

/*
 * Create object `popup1' in the specified instance.
 */
Xv_opaque
read_popup1_popup1_create(ip, owner)
	read_popup1_objects	*ip;
	Xv_opaque	owner;
{
	extern void	read_file_done();
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 375,
		XV_HEIGHT, 145,
		XV_LABEL, "Color Scale Editor: Read File",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		FRAME_CMD_PUSHPIN_IN, FALSE,
		FRAME_DONE_PROC, read_file_done,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `controls1' in the specified instance.
 */
Xv_opaque
read_popup1_controls1_create(ip, owner)
	read_popup1_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	gcm_initialize_colors(obj, NULL, NULL);
	return obj;
}

/*
 * Create object `read_directory' in the specified instance.
 */
Xv_opaque
read_popup1_read_directory_create(ip, owner)
	read_popup1_objects	*ip;
	Xv_opaque	owner;
{
	extern void		read_dir_events();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "read:read_directory",
		XV_X, 12,
		XV_Y, 12,
		PANEL_VALUE_DISPLAY_LENGTH, 35,
		PANEL_VALUE_STORED_LENGTH, 35,
		PANEL_LABEL_STRING, "Directory:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_LEVEL, PANEL_ALL,
		PANEL_EVENT_PROC, read_dir_events,
		NULL);
	return obj;
}

/*
 * Create object `read_filename' in the specified instance.
 */
Xv_opaque
read_popup1_read_filename_create(ip, owner)
	read_popup1_objects	*ip;
	Xv_opaque	owner;
{
	extern void		read_filename_events();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "read:read_filename",
		XV_X, 12,
		XV_Y, 40,
		PANEL_VALUE_DISPLAY_LENGTH, 35,
		PANEL_VALUE_STORED_LENGTH, 35,
		PANEL_LABEL_STRING, "Filename:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_LEVEL, PANEL_ALL,
		PANEL_EVENT_PROC, read_filename_events,
		NULL);
	return obj;
}

/*
 * Create object `read_format' in the specified instance.
 */
Xv_opaque
read_popup1_read_format_create(ip, owner)
	read_popup1_objects	*ip;
	Xv_opaque	owner;
{
	extern void		read_format_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "read:read_format",
		XV_X, 12,
		XV_Y, 64,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_LABEL_STRING, "Format:",
		PANEL_NOTIFY_PROC, read_format_proc,
		PANEL_CHOICE_STRINGS,
			"Name",
			"RGB",
			"Hexval",
			NULL,
		PANEL_CHOICE_COLOR,  0, gcm_color_index("blue"),
		PANEL_CHOICE_COLOR,  1, gcm_color_index("blue"),
		PANEL_CHOICE_COLOR,  2, gcm_color_index("blue"),
		NULL);
	return obj;
}

/*
 * Create object `read_button' in the specified instance.
 */
Xv_opaque
read_popup1_read_button_create(ip, owner)
	read_popup1_objects	*ip;
	Xv_opaque	owner;
{
	extern void		read_button_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "read:read_button",
		XV_X, 172,
		XV_Y, 116,
		PANEL_ITEM_COLOR, gcm_color_index("red"),
		PANEL_LABEL_STRING, "Read",
		PANEL_NOTIFY_PROC, read_button_proc,
		NULL);
	return obj;
}

