/*******************************************
 * TrackProps_tdrp.c
 *
 * TDRP C code file 'TrackProps' module.
 *
 * Code for program TrackProps
 *
 * This file has been automatically
 * generated by TDRP, do not modify.
 *
 *******************************************/

#include "TrackProps_tdrp.h"
#include <string.h>

/*
 * file scope variables
 */

static TDRPtable Table[8];
static TrackProps_tdrp_struct *Params;
static char *Module = "TrackProps";

/*************************************************************
 * TrackProps_tdrp_load_from_args()
 *
 * Loads up TDRP using the command line args.
 *
 * Check TDRP_usage() for command line actions associated with
 * this function.
 *
 *   argc, argv: command line args
 *
 *   TrackProps_tdrp_struct *params: loads up this struct
 * 
 *   char **override_list: A null-terminated list of overrides
 *     to the parameter file.
 *     An override string has exactly the format of an entry
 *     in the parameter file itself.
 *
 *   char **params_path_p: if non-NULL, this is set to point to
 *                         the path of the params file used.
 *
 *  Returns 0 on success, -1 on failure.
 */

int TrackProps_tdrp_load_from_args(int argc, char **argv,
                         TrackProps_tdrp_struct *params,
                         char **override_list,
                         char **params_path_p)
{
  Params = params;
  TrackProps_tdrp_init(Params);
  if (tdrpLoadFromArgs(argc, argv,
                       Table, Params,
                       override_list, params_path_p)) {
    return (-1);
  } else {
    return (0);
  }
}

/*************************************************************
 * TrackProps_tdrp_load()
 *
 * Loads up TDRP for a given module.
 *
 * This version of load gives the programmer the option to load
 * up more than one module for a single application. It is a
 * lower-level routine than TrackProps_tdrp_load_from_args,
 * and hence more flexible, but the programmer must do more work.
 *
 *   char *param_file_path: the parameter file to be read in.
 *
 *   TrackProps_tdrp_struct *params: loads up this struct
 *
 *   char **override_list: A null-terminated list of overrides
 *     to the parameter file.
 *     An override string has exactly the format of an entry
 *     in the parameter file itself.
 *
 *  expand_env: flag to control environment variable
 *                expansion during tokenization.
 *              If TRUE, environment expansion is set on.
 *              If FALSE, environment expansion is set off.
 *
 *  Returns 0 on success, -1 on failure.
 */

int TrackProps_tdrp_load(char *param_file_path,
               TrackProps_tdrp_struct *params,
               char **override_list,
               int expand_env, int debug)
{
  Params = params;
  TrackProps_tdrp_init(Params);
  if (tdrpLoad(param_file_path, Table,
               params, override_list,
               expand_env, debug)) {
    return (-1);
  } else {
    return (0);
  }
}

/*************************************************************
 * TrackProps_tdrp_load_defaults()
 *
 * Loads up defaults for a given module.
 *
 * See TrackProps_tdrp_load() for more details.
 *
 *  Returns 0 on success, -1 on failure.
 */

int TrackProps_tdrp_load_defaults(TrackProps_tdrp_struct *params,
                        int expand_env)
{
  Params = params;
  TrackProps_tdrp_init(Params);
  if (tdrpLoad(NULL, Table,
               params, NULL,
               expand_env, FALSE)) {
    return (-1);
  } else {
    return (0);
  }
}

/*************************************************************
 * TrackProps_tdrp_sync()
 *
 * Syncs the user struct data back into the parameter table,
 * in preparation for printing.
 */

void TrackProps_tdrp_sync(void)
{
  tdrpUser2Table(Table, Params);
}

/*************************************************************
 * TrackProps_tdrp_print()
 * 
 * Print params file
 *
 * The modes supported are:
 *
 *   PRINT_SHORT:   main comments only, no help or descriptions
 *                  structs and arrays on a single line
 *   PRINT_NORM:    short + descriptions and help
 *   PRINT_LONG:    norm  + arrays and structs expanded
 *   PRINT_VERBOSE: long  + private params included
 */

void TrackProps_tdrp_print(FILE *out, tdrp_print_mode_t mode)
{
  tdrpPrint(out, Table, Module, mode);
}

/*************************************************************
 * TrackProps_tdrp_check_all_set()
 *
 * Return TRUE if all set, FALSE if not.
 *
 * If out is non-NULL, prints out warning messages for those
 * parameters which are not set.
 */

int TrackProps_tdrp_check_all_set(FILE *out)
{
  return (tdrpCheckAllSet(out, Table, Params));
}

/*************************************************************
 * TrackProps_tdrp_check_is_set()
 *
 * Return TRUE if parameter is set, FALSE if not.
 *
 */

int TrackProps_tdrp_check_is_set(char *param_name)
{
  return (tdrpCheckIsSet(param_name, Table, Params));
}

/*************************************************************
 * TrackProps_tdrp_free_all()
 *
 * Frees up all TDRP dynamic memory.
 */

void TrackProps_tdrp_free_all(void)
{
  tdrpFreeAll(Table, Params);
}

/*************************************************************
 * TrackProps_tdrp_array_realloc()
 *
 * Realloc 1D array.
 *
 * If size is increased, the values from the last array entry is
 * copied into the new space.
 *
 * Returns 0 on success, -1 on error.
 */

int TrackProps_tdrp_array_realloc(char *param_name, int new_array_n)
{
  if (tdrpArrayRealloc(Table, Params, param_name, new_array_n)) {
    return (-1);
  } else {
    return (0);
  }
}

/*************************************************************
 * TrackProps_tdrp_array2D_realloc()
 *
 * Realloc 2D array.
 *
 * If size is increased, the values from the last array entry is
 * copied into the new space.
 *
 * Returns 0 on success, -1 on error.
 */

int TrackProps_tdrp_array2D_realloc(char *param_name,
                          int new_array_n1,
                          int new_array_n2)
{
  if (tdrpArray2DRealloc(Table, Params, param_name,
			 new_array_n1, new_array_n2)) {
    return (-1);
  } else {
    return (0);
  }
}

/*************************************************************
 * TrackProps_tdrp_table()
 *
 * Returns pointer to static Table for this module.
 */

TDRPtable *TrackProps_tdrp_table(void)
{
  return (Table);
}

/*************************************************************
 * TrackProps_tdrp_init()
 *
 * Module table initialization function.
 *
 *
 * Returns pointer to static Table for this module.
 */

TDRPtable *TrackProps_tdrp_init(TrackProps_tdrp_struct *params)

{

  TDRPtable *tt = Table;

  TrackProps_tdrp_struct pp; /* for computing byte_offsets */

  /* zero out struct, and store size */

  memset(params, 0, sizeof(TrackProps_tdrp_struct));
  params->struct_size = sizeof(TrackProps_tdrp_struct);

  /* Parameter 'Comment 0' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = COMMENT_TYPE;
  tt->param_name = tdrpStrDup("Comment 0");
  tt->comment_hdr = tdrpStrDup("Prints out summary track properties. Deprecated. Replaced by Tracks2Ascii.");
  tt->comment_text = tdrpStrDup("");
  tt++;
  
  /* Parameter 'debug' */
  /* ctype is 'TrackProps_debug' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = ENUM_TYPE;
  tt->param_name = tdrpStrDup("debug");
  tt->descr = tdrpStrDup("Debug option");
  tt->help = tdrpStrDup("If set, debug messages will be printed appropriately");
  tt->val_offset = (char *) &(pp.debug) - (char *) &pp;
  tt->enum_def.name = tdrpStrDup("debug");
  tt->enum_def.nfields = 3;
  tt->enum_def.fields = (enum_field_t *)
      tdrpMalloc(tt->enum_def.nfields * sizeof(enum_field_t));
    tt->enum_def.fields[0].name = tdrpStrDup("DEBUG_OFF");
    tt->enum_def.fields[0].val = DEBUG_OFF;
    tt->enum_def.fields[1].name = tdrpStrDup("DEBUG_NORM");
    tt->enum_def.fields[1].val = DEBUG_NORM;
    tt->enum_def.fields[2].name = tdrpStrDup("DEBUG_VERBOSE");
    tt->enum_def.fields[2].val = DEBUG_VERBOSE;
  tt->single_val.e = DEBUG_OFF;
  tt++;
  
  /* Parameter 'malloc_debug_level' */
  /* ctype is 'long' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = LONG_TYPE;
  tt->param_name = tdrpStrDup("malloc_debug_level");
  tt->descr = tdrpStrDup("Malloc debug level");
  tt->help = tdrpStrDup("0 - none, 1 - corruption checking, 2 - records all malloc blocks and checks, 3 - printout of all mallocs etc.");
  tt->val_offset = (char *) &(pp.malloc_debug_level) - (char *) &pp;
  tt->has_min = TRUE;
  tt->has_max = TRUE;
  tt->min_val.l = 0;
  tt->max_val.l = 3;
  tt->single_val.l = 0;
  tt++;
  
  /* Parameter 'instance' */
  /* ctype is 'char*' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = STRING_TYPE;
  tt->param_name = tdrpStrDup("instance");
  tt->descr = tdrpStrDup("Process instance");
  tt->help = tdrpStrDup("Used for registration with procmap.");
  tt->val_offset = (char *) &(pp.instance) - (char *) &pp;
  tt->single_val.s = tdrpStrDup("Test");
  tt++;
  
  /* Parameter 'altitude_threshold' */
  /* ctype is 'double' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = DOUBLE_TYPE;
  tt->param_name = tdrpStrDup("altitude_threshold");
  tt->descr = tdrpStrDup("Altitude threshold for computing altitude-thresholded properties.");
  tt->help = tdrpStrDup("There are a number of properties, e.g. volume, which are computed for the whole storm and for the region above an altitude threshold. This threshold is used for those computations.");
  tt->val_offset = (char *) &(pp.altitude_threshold) - (char *) &pp;
  tt->has_min = TRUE;
  tt->has_max = TRUE;
  tt->min_val.d = 0;
  tt->max_val.d = 30;
  tt->single_val.d = 6;
  tt++;
  
  /* Parameter 'min_duration' */
  /* ctype is 'double' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = DOUBLE_TYPE;
  tt->param_name = tdrpStrDup("min_duration");
  tt->descr = tdrpStrDup("Minimum track duration (secs).");
  tt->help = tdrpStrDup("Only tracks with durations which exceed this value will be processed.");
  tt->val_offset = (char *) &(pp.min_duration) - (char *) &pp;
  tt->has_min = TRUE;
  tt->min_val.d = 0;
  tt->single_val.d = 0;
  tt++;
  
  /* Parameter 'max_duration' */
  /* ctype is 'double' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = DOUBLE_TYPE;
  tt->param_name = tdrpStrDup("max_duration");
  tt->descr = tdrpStrDup("Maximum track duration (secs).");
  tt->help = tdrpStrDup("Only tracks with durations which do not exceed this value will be processed.");
  tt->val_offset = (char *) &(pp.max_duration) - (char *) &pp;
  tt->single_val.d = 86400;
  tt++;
  
  /* trailing entry has param_name set to NULL */
  
  tt->param_name = NULL;
  
  return (Table);

}
