#
# Recursive make for BOM libraries
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(LIB_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	FiltAlg \
	Fmq \
	Mdv \
        Ncxx \
	Radx \
	Spdb \
	advect \
	cidd \
	contour \
	dataport \
	didss \
	dsdata \
	dsserver \
	euclid \
	hydro \
	perl5 \
	physics \
	radar \
	rapformats \
	rapmath \
	rapplot \
	shapelib \
	tdrp \
	titan \
	toolsa
        
include $(RAP_MAKE_INC_DIR)/rap_make_recursive_dir_targets
