#
# Recursive make for LROSE libraries
#

include $(LROSE_CORE_DIR)/build/make_include/lrose_make_macros

TARGETS = $(GENERAL_TARGETS) $(LIB_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	Ncxx \
	Radx \
	dataport \
        euclid \
	kd \
	physics \
	rapmath \
	tdrp \
	toolsa

include $(LROSE_CORE_DIR)/build/make_include/lrose_make_recursive_dir_targets
