#
# Recursive make - makes the subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	chunk_spdb2symprod \
	dist_spdb_data \
	ltg_spdb2symprod \
	spdb_query \
	spdb_server \
	spdb_server_poll \
	xspdb_query

include $(RAP_MAKE_INC_DIR)/rap_make_recursive_dir_targets



