#
# Recursive make - makes the subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	dist_spdb_data \
	spdb_query \
	spdb_server \
	spdb_server_poll

include $(RAP_MAKE_INC_DIR)/rap_make_recursive_dir_targets



