#
# Recursive make - makes the subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	Dsr2Radx \
	Radx2Dsr \
	Radx2Grid \
	RadxBeamBlock \
	RadxCheck \
	RadxClutMon \
	RadxConvert \
	RadxDiff \
	RadxEvad \
	RadxFilter \
	RadxMergeFields \
	RadxMergeVols \
	RadxMon \
	RadxPartRain \
	RadxPrint \
	RadxQpe

include $(RAP_MAKE_INC_DIR)/rap_make_recursive_dir_targets
