#
# Recursive make - makes the subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	Dsr2Radx \
	FixCfradialPaths \
	FixRadxPointing \
	Radx2Dsr \
	Radx2Grid \
	RadxCheck \
	RadxConvert \
	RadxCov2Mom \
	RadxEvad \
	RadxDiff \
	RadxMergeFields \
	RadxMon \
	RadxPartRain \
	RadxPrint

include $(RAP_MAKE_INC_DIR)/rap_make_recursive_dir_targets
