#
# Recursive make - makes the subdirectory code
#

include $(LROSE_CORE_DIR)/build/make_include/lrose_make_macros

TARGETS = $(GENERAL_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	Radx2Grid \
	RadxBeamBlock \
        RadxBufr \
	RadxConvert \
        RadxEvad \
        RadxKdp \
        RadxPartRain \
        RadxPid \
	RadxPrint \
        RadxRate \
        RadxQpe

include $(LROSE_CORE_DIR)/build/make_include/lrose_make_recursive_dir_targets
