#
# Recursive make - makes the subdirectory code
#

include $(LROSE_CORE_DIR)/build/make_include/lrose_make_macros

TARGETS = $(GENERAL_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	Dsr2Radx \
	FixCfradialPaths \
	FixRadxPointing \
	Radx2Dsr \
	RadxCheck \
	RadxConvert \
	RadxDiff \
	RadxDwellCombine \
	RadxFilter \
	RadxMergeFields \
	RadxMergeVols \
	RadxMon \
	RadxPrint

include $(LROSE_CORE_DIR)/build/make_include/lrose_make_recursive_dir_targets
