#
# Recursive make - makes the subdirectory code
#

include $(LROSE_CORE_DIR)/build/make_include/lrose_make_macros

TARGETS = $(GENERAL_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	MM5Ingest \
	MM5Simulate \
	MM5Print \
	MM5Split \
	MM52Spdb \
	MM5toGrib


include $(LROSE_CORE_DIR)/build/make_include/lrose_make_recursive_dir_targets
