# -*- python -*-
#
#


Import('env')

sources  = ['RayFileFactory.cpp']

hFiles   = ['RayFileFactory.h']

libNode  = env.Library('rayfilefactory',source = sources, CPPPATH=[env.installLocalInc,env.netcdfInc]);

localInstallLibNode = env.Install(env.installLocalLib ,libNode);
localInstallIncNode = env.Install(env.installLocalInc ,hFiles);

env.Default([libNode,localInstallLibNode,localInstallIncNode])
env.Install(env.installLib,libNode);
env.Install(env.installInc,hFiles);
