/*
 * fields_pu_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `fields_pu.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include "cidd_gui.h"
#include <group.h>

void		wind_mu_gen_proc(Menu, Menu_generate);
void		wind_color_proc(Panel_item, Event *);
/*
 * Menu handler for `field_mu'.
 */
Menu
field_mu_gen_proc(Menu menu, Menu_generate op)
{
	fields_pu_fields_pu_objects * ip = (fields_pu_fields_pu_objects *) xv_get(menu, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		fputs("cidd_gui: field_mu_gen_proc: MENU_NOTIFY\n", stderr);
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return menu;
}

/*
 * Notify callback function for `display_list'.
 */
int
field_display_proc(Panel_item item, char *string, Xv_opaque client_data, Panel_list_op op, Event *event, int row)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch(op) {
	case PANEL_LIST_OP_DESELECT:
		fprintf(stderr, "cidd_gui: field_display_proc: PANEL_LIST_OP_DESELECT: %s\n",string);
		break;

	case PANEL_LIST_OP_SELECT:
		fprintf(stderr, "cidd_gui: field_display_proc: PANEL_LIST_OP_SELECT: %s\n",string);
		break;

	case PANEL_LIST_OP_VALIDATE:
		fprintf(stderr, "cidd_gui: field_display_proc: PANEL_LIST_OP_VALIDATE: %s\n",string);
		break;

	case PANEL_LIST_OP_DELETE:
		fprintf(stderr, "cidd_gui: field_display_proc: PANEL_LIST_OP_DELETE: %s\n",string);
		break;
	}
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return XV_OK;
}

/*
 * Notify callback function for `f_config_tx1'.
 */
Panel_setting
set_host_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: set_host_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `f_config_tx2'.
 */
Panel_setting
set_port_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: set_port_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `f_config_tx3'.
 */
Panel_setting
set_field_no_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: set_field_no_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `f_config_tx6'.
 */
Panel_setting
set_subtype_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: set_subtype_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `f_config_tx5'.
 */
Panel_setting
set_instance_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: set_instance_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `f_config_tx4'.
 */
Panel_setting
set_stretch_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: set_stretch_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `f_config_tx9'.
 */
Panel_setting
set_time_offset_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: set_time_offset_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `ren_meth_st'.
 */
void
set_ren_meth_proc(Panel_item item, int	 value, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	short	i;
	
	fputs("cidd_gui: set_ren_meth_proc\n", stderr);
	for (i = 0; i < 1; i++) {
		if (value & 01)
			fprintf(stderr, "\t%dth item selected\n", i);
		
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

		value >>= 1;
	}
}

/*
 * Notify callback function for `update_st'.
 */
void
set_update_proc(Panel_item item, int	 value, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	short	i;
	
	fputs("cidd_gui: set_update_proc\n", stderr);
	for (i = 0; i < 1; i++) {
		if (value & 01)
			fprintf(stderr, "\t%dth item selected\n", i);
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		/* gxv_end_connections */

		value >>= 1;
	}
}

/*
 * Notify callback function for `max_st'.
 */
void
set_composite_proc(Panel_item item, int	 value, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	short	i;
	
	fputs("cidd_gui: set_composite_proc\n", stderr);
	for (i = 0; i < 1; i++) {
		if (value & 01)
			fprintf(stderr, "\t%dth item selected\n", i);
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		/* gxv_end_connections */

		value >>= 1;
	}
}

/*
 * Notify callback function for `use_servmap_st'.
 */
void
set_servmap_proc(Panel_item item, int	 value, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	short	i;
	
	fputs("cidd_gui: set_servmap_proc\n", stderr);
	for (i = 0; i < 1; i++) {
		if (value & 01)
			fprintf(stderr, "\t%dth item selected\n", i);
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */
		/* gxv_end_connections */

		value >>= 1;
	}
}

/*
 * Notify callback function for `f_config_tx7'.
 */
Panel_setting
set_cscale_min_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: set_cscale_min_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `f_config_tx8'.
 */
Panel_setting
set_cscale_max_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: set_cscale_max_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `f_config_color_apply_bt'.
 */
void
set_cscale_apply_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("cidd_gui: set_cscale_apply_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `f_config_tx3'.
 */
Panel_setting
set_alt_offset(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: set_alt_offset: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `autoscale_st'.
 */
void
autoscale_proc(Panel_item item, int value, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	short	i;
	
	fputs("cidd_gui: autoscale_proc\n", stderr);
	for (i = 0; i < 1; i++) {
		if (value & 01)
			fprintf(stderr, "\t%dth item selected\n", i);
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		/* gxv_end_connections */

		value >>= 1;
	}
}

/*
 * Menu handler for `prod_mu'.
 */
Menu
prod_mu_gen_proc(Menu menu, Menu_generate op)
{
	fields_pu_fields_pu_objects * ip = (fields_pu_fields_pu_objects *) xv_get(menu, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		fputs("cidd_gui: prod_mu_gen_proc: MENU_NOTIFY\n", stderr);
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return menu;
}

/*
 * Notify callback function for `w_config_url_tx'.
 */
Panel_setting
wind_url_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: wind_url_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `w_config_u_tx'.
 */
Panel_setting
u_name_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: u_name_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `w_config_v_tx'.
 */
Panel_setting
v_name_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: v_name_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `w_config_w_tx'.
 */
Panel_setting
w_name_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: w_name_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `w_style_tx'.
 */
void
wind_style_proc(Panel_item item, int value, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "cidd_gui: wind_style_proc: value: %u\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `w_config_line_width_tx'.
 */
Panel_setting
w_line_width_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	int	value = (int) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: w_line_width_proc: value: %d\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Event callback function for `w_config_color_msg'.
 */
void
fields_pu_fields_pu_w_config_color_msg_event_callback(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "cidd_gui: fields_pu_fields_pu_w_config_color_msg_event_callback: event %d\n", event_id(event));
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (event_action(event) == ACTION_SELECT)
	{
		wind_color_proc(item, event);
	}
	
	/* gxv_end_connections */

	panel_default_handle_event(item, event);
}

/*
 * User-defined action for `w_config_color_msg'.
 */
void
wind_color_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "cidd_gui: wind_color_proc: event %d\n", event_id(event));
}

/*
 * Notify callback function for `p_config_url_tx'.
 */
Panel_setting
prod_url_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: prod_url_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `allow_after_tx'.
 */
Panel_setting
allow_after_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: allow_after_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `p_config_type_tx'.
 */
Panel_setting
prod_data_type_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: prod_data_type_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `allow_before_tx'.
 */
Panel_setting
allow_before_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: allow_before_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `render_type_st'.
 */
void
prod_render_type_proc(Panel_item item, int value, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "cidd_gui: prod_render_type_proc: value: %u\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `text_thresh_tx'.
 */
Panel_setting
test_thresh_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: test_thresh_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Menu handler for `wind_mu'.
 */
Menu
wind_menu_gen_proc(Menu menu, Menu_generate op)
{
	fields_pu_fields_pu_objects * ip = (fields_pu_fields_pu_objects *) xv_get(menu, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		fputs("cidd_gui: wind_menu_gen_proc: MENU_NOTIFY\n", stderr);
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return menu;
}

/*
 * Notify callback function for `wind_alt_tx'.
 */
Panel_setting
wind_alt_offset_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: wind_alt_offset_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `textfield1'.
 */
Panel_setting
wind_time_offset_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: wind_time_offset_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `textfield2'.
 */
Panel_setting
wind_time_slop_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: wind_time_slop_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `topo_url_tx'.
 */
Panel_setting
topo_url_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: topo_url_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `land_use_url_tx'.
 */
Panel_setting
land_use_url_proc(Panel_item item, Event *event)
{
	fields_pu_fields_pu_objects *ip = (fields_pu_fields_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: land_use_url_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}
