/* *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* */
/* ** Copyright UCAR (c) 1990 - 2016                                         */
/* ** University Corporation for Atmospheric Research (UCAR)                 */
/* ** National Center for Atmospheric Research (NCAR)                        */
/* ** Boulder, Colorado, USA                                                 */
/* ** BSD licence applies - redistribution and use in source and binary      */
/* ** forms, with or without modification, are permitted provided that       */
/* ** the following conditions are met:                                      */
/* ** 1) If the software is modified to produce derivative works,            */
/* ** such modified software should be clearly marked, so as not             */
/* ** to confuse it with the version available from UCAR.                    */
/* ** 2) Redistributions of source code must retain the above copyright      */
/* ** notice, this list of conditions and the following disclaimer.          */
/* ** 3) Redistributions in binary form must reproduce the above copyright   */
/* ** notice, this list of conditions and the following disclaimer in the    */
/* ** documentation and/or other materials provided with the distribution.   */
/* ** 4) Neither the name of UCAR nor the names of its contributors,         */
/* ** if any, may be used to endorse or promote products derived from        */
/* ** this software without specific prior written permission.               */
/* ** DISCLAIMER: THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS  */
/* ** OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED      */
/* ** WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.    */
/* *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* */
/*
 * regis_tool_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `regis_tool.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
/*************************************************************************
 * REGIS_TOOL_PROC: Callbacks for the REGISTRATION TOOL
 */
#include "regis_tool.h"

#define MAX_PAIRS 128

void update_average(void);
 
int num_pairs = 0;
int pair_num = -1;
double pair_x1[MAX_PAIRS];
double pair_y1[MAX_PAIRS];
double pair_x2[MAX_PAIRS];
double pair_y2[MAX_PAIRS];
double average_x = 0.0;
double average_y = 0.0;
 
/*************************************************************************
 * Notify callback function for `start_bt'.
 */
void
start_proc(item, event)
	Panel_item	item;
	Event		*event;
{
    regis_tool_win1_objects *ip = (regis_tool_win1_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
    xv_set(gd.gui_objects->status_msg,PANEL_LABEL_STRING,"Enter Point Pairs",NULL);
    xv_set(gd.gui_objects->each_pt_msg,PANEL_LABEL_STRING,"Click on Image Reference Point",NULL);
    num_pairs = 0;
    pair_num = 1;
    average_x = 0.0;
    average_y = 0.0;
    update_average();
}

/*************************************************************************
 * Notify callback function for `comp_bt'.
 */
void
comp_proc(item, event)
	Panel_item	item;
	Event		*event;
{
    char string[256];

    gd.coord_expt->data_offset_x_km = average_x;
    gd.coord_expt->data_offset_y_km = average_y;

    sprintf(string,"Stored X: %10g   Y: %10g",average_x,average_y);
    xv_set(gd.gui_objects->each_pt_msg,PANEL_LABEL_STRING,string,NULL);
    xv_set(gd.gui_objects->status_msg,PANEL_LABEL_STRING,"READY TO START",NULL);
}

/*************************************************************************
 * UPDATE_POS: Calculate the relative positions and
 *     report it by setting panel messages
 *
 */

void
update_position(void) 
{
    char string[256];

    switch(pair_num) {
       default:   /* Ignore */
       break; 
    
       case 1:
	   pair_x1[num_pairs] = gd.coord_expt->pointer_x;
	   pair_y1[num_pairs] = gd.coord_expt->pointer_y;
           xv_set(gd.gui_objects->each_pt_msg,PANEL_LABEL_STRING,"Click on Overlay reference Point",NULL);
	   pair_num = 2;
       break;

       case 2:
	   pair_x2[num_pairs] = gd.coord_expt->pointer_x;
	   pair_y2[num_pairs] = gd.coord_expt->pointer_y;
           xv_set(gd.gui_objects->each_pt_msg,PANEL_LABEL_STRING,"Click on Image Reference Point",NULL);
	   pair_num = 1;
	   if(num_pairs < MAX_PAIRS -2) num_pairs++;
	   update_average();
       break;
	 
    }
	   
}

/*************************************************************************
 * UPDATE_Average: Calculate the average offsets
 *
 */

void
update_average(void) 
{
    int i;
    char string[256];
    double sum_x = 0.0;
    double sum_y = 0.0;

    for(i=0; i < num_pairs; i++ ) {
       sum_x += (pair_x2[i] - pair_x1[i]);
       sum_y += (pair_y2[i] - pair_y1[i]);
    }

    if(num_pairs > 0) {
        average_x = sum_x / num_pairs;
        average_y = sum_y / num_pairs;
    } else {
	average_x = 0.0;
	average_y = 0.0;
    }

    sprintf(string,"X: %10g   Y: %10g",average_x,average_y);
    xv_set(gd.gui_objects->avg_msg,PANEL_LABEL_STRING,string,NULL);
}


