#
# Recursive make - makes the subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	Binet2Dsr \
	DataFileName \
	DsFmq2Tape \
	Dsr2File \
	Dsr2Mdv \
	Dsr2MdvLookup \
	Dsr2Vol \
	File2Dsr \
	Fmq2Fmq \
	Fmq2MultMsgFmq \
	FmqMon \
	GenPt2Spdb \
	Indicator \
	InputWatcher \
	Janitor \
	LdataFMQtrigger \
	LdataInformer \
	LdataWatcher \
	LdataWriter \
	LdataWriterSimultaneous \
	Mdv2Dsr \
	MultMsgFmq2Fmq \
	RadMon \
	Rapic2Dsr \
	RapPirep2Spdb \
	Scout \
	Socket2File \
	Test2Dsr \
	TimeCalc \
	Validator \
	VerifyGrid \
	copy_mh_tape \
	didss_compress \
        dsr2mmq \
	edge2dsr \
	fmq2tape \
	fmq_print \
	kavltg2spdb \
	kavm2mdv \
	map_atd2rap \
	nprtLtg2Spdb \
	print_clutter_table \
	print_polar2mdv_lookup \
	ridds2mom \
	setuid_starter \
	tape_test \
	wsi_ingest \
	wsim2mdv

include $(RAP_MAKE_INC_DIR)/rap_make_recursive_dir_targets
