#
# Recursive make - makes the subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	Bdry2Symprod \
	DataMapper \
	DsFCopyServer \
	DsFileDist \
	DsMdvServer \
	DsServerMgr \
	DsSpdbServer \
	DsTitanServer \
	GenPt2Symprod \
	Ltg2Symprod \
	Metar2Symprod \
	PrintDataMap \
	SpdbQuery \
	Tstorms2Symprod \
	XSpdbQuery 

include $(RAP_MAKE_INC_DIR)/rap_make_recursive_dir_targets

