/* *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* */
/* ** Copyright UCAR (c) 1990 - 2016                                         */
/* ** University Corporation for Atmospheric Research (UCAR)                 */
/* ** National Center for Atmospheric Research (NCAR)                        */
/* ** Boulder, Colorado, USA                                                 */
/* ** BSD licence applies - redistribution and use in source and binary      */
/* ** forms, with or without modification, are permitted provided that       */
/* ** the following conditions are met:                                      */
/* ** 1) If the software is modified to produce derivative works,            */
/* ** such modified software should be clearly marked, so as not             */
/* ** to confuse it with the version available from UCAR.                    */
/* ** 2) Redistributions of source code must retain the above copyright      */
/* ** notice, this list of conditions and the following disclaimer.          */
/* ** 3) Redistributions in binary form must reproduce the above copyright   */
/* ** notice, this list of conditions and the following disclaimer in the    */
/* ** documentation and/or other materials provided with the distribution.   */
/* ** 4) Neither the name of UCAR nor the names of its contributors,         */
/* ** if any, may be used to endorse or promote products derived from        */
/* ** this software without specific prior written permission.               */
/* ** DISCLAIMER: THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS  */
/* ** OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED      */
/* ** WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.    */
/* *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* */
/*************************************************************************
 * CIDD_2_SKEWT.c - Read a  key click in a CIDD window, gather model
 *  data, generate a synthetic CLASS file
 */

#define CIDD_2_SKEWT_MAIN
 
#include "cidd2skewt.h"

void process_args( int argc, char *argv[]);
void init_xview( int *argc_ptr, char    *argv[]);
int  x_error_proc( Display *disp, XErrorEvent *event);
Notify_value base_win_destroy( Notify_client   client, Destroy_status  status);
void get_parameter_database( char    *fname);
void init_data_space(void);
void modify_xview_objects(void);

/********************************************************************
 * MAIN: Process arguments, initialize and begin application
 */
 

void
main(argc, argv)
	int		argc;
	char		**argv;
{
	xv_init(XV_INIT_ARGC_PTR_ARGV,&argc,argv,XV_X_ERROR_PROC,x_error_proc,NULL);
	 
	process_args(argc,argv);	/* process command line arguments */

	/* initialize globals, get/set defaults, establish data sources etc. */
	init_data_space();
 
	init_xview(&argc,argv); /* create all Xview objects */	

	/* make changes to xview objects not available from DevGuide */
	modify_xview_objects();

	/*
	 * Turn control over to XView.
	 */
	xv_main_loop(gd.C2s_base_win_c2s_bw->c2s_bw);
	exit(0);
}

#define ARG_OPTION_STRING   "dp:"
/*****************************************************************
 * PROCESS_ARGS: Progess command line arguments. Set option flags
 *	   And print usage info if necessary
 */

void process_args( int argc, char *argv[])
{
	int err_flag =0;
	int	 c;
	extern  int optind; /* index to remaining arguments */
	extern  char *optarg;   /* option argument string */

	gd.db_name = "cidd2skewt.defaults";	/* Set the default data base name */
	 
	while ((c = getopt(argc, argv,ARG_OPTION_STRING)) != EOF) {
		switch(c) {
			case 'd' :	/* debug mode */
				gd.debug = 1;
			break;
 
			case 'p' :	/* alternate parameter database file */
				gd.db_name = optarg;
			break;
 
			case '?':   /* error in options */
			default:
				err_flag++;
			break;
		}
 
	};
 
	if(err_flag) {
		fprintf(stderr,"Usage:cidd2skewt [-d] [-p alternate_parameter_file] \n");
		exit(-1);
	}
}  
 
/***************************************************************************
 * INIT_XVIEW : Initialize the base frame and other global objects
 */ 
 
void init_xview( int *argc_ptr, char	*argv[])
{
	Notify_value	base_win_destroy(); /* destroy interposer */
 
	gd.C2s_base_win_c2s_bw = c2s_base_win_c2s_bw_objects_initialize(NULL,NULL);

	gd.Load_pu_popup1 = load_pu_popup1_objects_initialize(NULL, gd.C2s_base_win_c2s_bw->c2s_bw);
	
	notify_interpose_destroy_func(gd.C2s_base_win_c2s_bw->c2s_bw,base_win_destroy);

	gd.dpy = (Display *) xv_get(gd.C2s_base_win_c2s_bw->c2s_bw,XV_DISPLAY);
}

/*****************************************************************
 * X_ERROR_PROC: Handle errors generated by the X server
 */
 
int x_error_proc( Display *disp, XErrorEvent *event)
{
	char	text[256];
 
	XGetErrorText(disp,event->error_code,text,256);
	fprintf(stderr,"Generated X error : %s, ID:%u\n",text,event->resourceid);
 
	switch(event->error_code) {
		default :
			return   XV_OK;
		break;
 
		case BadAlloc :
			return   XV_OK;
		break;
	}
}
 
/*****************************************************************
 * BASE_WIN_DESTROY: Interposition for base frame destroys
 */

Notify_value
base_win_destroy( Notify_client   client, Destroy_status  status)
{
	int i;
	char	fname[1024];

	switch(status) {
		case DESTROY_CLEANUP:
 
		case DESTROY_PROCESS_DEATH:
			return notify_next_destroy_func(client,status);
		break;
 
		case DESTROY_CHECKING:
			return NOTIFY_DONE;
		break;
 
		case DESTROY_SAVE_YOURSELF:
			return NOTIFY_DONE;
		break;
	}
}

/************************************************************************
 * GET_PARAMETER_DATABASE: Load the parameter data base and set initial
 *     parameters
 *
 */

void    get_parameter_database( char    *fname)
{
    /* Retrieve the application's Default/Resource data base */
    gd.db = XrmGetFileDatabase(fname);
    if(gd.db == NULL) {
        fprintf(stderr,"Could'nt open or find %s\n",gd.db_name);
        exit(-1);
    }
}

/*****************************************************************
 * INIT_DATA_SPACE : Init all globals and set up defaults
 */

void init_data_space(void)
{
    int i;
    int coord_key;

    INSTANCE = xv_unique_key(); /* get keys for retrieving data */

    get_parameter_database(gd.db_name); /* load the program's parameter database*/

    sprintf(gd.fname,"cidd_skewt.class");
    if(getwd(gd.data_dir) == NULL) {
	perror("cidd2class getpw()");
	exit(-1);
    }


    coord_key = XRSgetLong(gd.db, "cidd.coord_key", 63500);
    if((gd.coord_expt = (coord_export_t *) ushm_create(coord_key, sizeof(coord_export_t), 0666)) == NULL) {
        fprintf(stderr, "Couldn't create shared memory segment for Aux process communications\n");
        exit(-1);
    }

    gd.auto_command  = XRSgetString(gd.db, "cidd2skewt.auto_command","/local/rdss/bin/suds");
     
    gd.default_host = XRSgetString(gd.db, "cidd2skewt.default_host","");
    gd.default_port = XRSgetLong(gd.db, "cidd2skewt.default_port",-1);

    gd.base_press = XRSgetDouble(gd.db, "cidd2skewt.base_pressure",1000.0);

    /* Gather info on Temperature data */
    strncpy(gd.Temper.host,XRSgetString(gd.db, "cidd2skewt.temp_host",gd.default_host),128);
    gd.Temper.port = XRSgetLong(gd.db, "cidd2skewt.temp_port",gd.default_port);
    gd.Temper.field_no = XRSgetLong(gd.db, "cidd2skewt.temp_field",-1);
    gd.Temper.scale = XRSgetDouble(gd.db, "cidd2skewt.temp_scale",1.0);
    gd.Temper.bias = XRSgetDouble(gd.db, "cidd2skewt.temp_bias",0.0);
     
    /* Gather info on Relative Humidity data */
    strncpy(gd.Relhum.host,XRSgetString(gd.db, "cidd2skewt.relhum_host",gd.default_host),128);
    gd.Relhum.port = XRSgetLong(gd.db, "cidd2skewt.relhum_port",gd.default_port);
    gd.Relhum.field_no = XRSgetLong(gd.db, "cidd2skewt.relhum_field",-1);
    gd.Relhum.scale = XRSgetDouble(gd.db, "cidd2skewt.relhum_scale",1.0);
    gd.Relhum.bias = XRSgetDouble(gd.db, "cidd2skewt.relhum_bias",0.0);
     
    /* Gather info on Pressure data */
    strncpy(gd.Press.host,XRSgetString(gd.db, "cidd2skewt.pres_host",gd.default_host),128);
    gd.Press.port = XRSgetLong(gd.db, "cidd2skewt.pres_port",gd.default_port);
    gd.Press.field_no = XRSgetLong(gd.db, "cidd2skewt.pres_field",-1);
    gd.Press.scale = XRSgetDouble(gd.db, "cidd2skewt.pres_scale",1.0);
    gd.Press.bias = XRSgetDouble(gd.db, "cidd2skewt.pres_bias",0.0);
     
    /* Gather info on Theta/Buoyancyv data */
    strncpy(gd.Theta.host,XRSgetString(gd.db, "cidd2skewt.theta_host",gd.default_host),128);
    gd.Theta.port = XRSgetLong(gd.db, "cidd2skewt.theta_port",gd.default_port);
    gd.Theta.field_no = XRSgetLong(gd.db, "cidd2skewt.theta_field",-1);
    gd.Theta.scale = XRSgetDouble(gd.db, "cidd2skewt.theta_scale",1.0);
    gd.Theta.bias = XRSgetDouble(gd.db, "cidd2skewt.theta_bias",0.0);
     
    /* Gather info on Dew point data */
    strncpy(gd.Dewpt.host,XRSgetString(gd.db, "cidd2skewt.dewpt_host",gd.default_host),128);
    gd.Dewpt.port = XRSgetLong(gd.db, "cidd2skewt.dewpt_port",gd.default_port);
    gd.Dewpt.field_no = XRSgetLong(gd.db, "cidd2skewt.dewpt_field",-1);
    gd.Dewpt.scale = XRSgetDouble(gd.db, "cidd2skewt.dewpt_scale",1.0);
    gd.Dewpt.bias = XRSgetDouble(gd.db, "cidd2skewt.dewpt_bias",0.0);
     
    /* Gather info on Mixing Ratio: Qv data */
    strncpy(gd.Mix_r.host,XRSgetString(gd.db, "cidd2skewt.mixr_host",gd.default_host),128);
    gd.Mix_r.port = XRSgetLong(gd.db, "cidd2skewt.mixr_port",gd.default_port);
    gd.Mix_r.field_no = XRSgetLong(gd.db, "cidd2skewt.mixr_field",-1);
    gd.Mix_r.scale = XRSgetDouble(gd.db, "cidd2skewt.mixr_scale",1.0);
    gd.Mix_r.bias = XRSgetDouble(gd.db, "cidd2skewt.mixr_bias",0.0);
     
    /* Gather info on Wind U data */
    strncpy(gd.U_wind.host,XRSgetString(gd.db, "cidd2skewt.windu_host",gd.default_host),128);
    gd.U_wind.port = XRSgetLong(gd.db, "cidd2skewt.windu_port",gd.default_port);
    gd.U_wind.field_no = XRSgetLong(gd.db, "cidd2skewt.windu_field",-1);
    gd.U_wind.scale = XRSgetDouble(gd.db, "cidd2skewt.windu_scale",1.0);
    gd.U_wind.bias = XRSgetDouble(gd.db, "cidd2skewt.windu_bias",0.0);
     
    /* Gather info on Wind U data */
    strncpy(gd.V_wind.host,XRSgetString(gd.db, "cidd2skewt.windv_host",gd.default_host),128);
    gd.V_wind.port = XRSgetLong(gd.db, "cidd2skewt.windv_port",gd.default_port);
    gd.V_wind.field_no = XRSgetLong(gd.db, "cidd2skewt.windv_field",-1);
    gd.V_wind.scale = XRSgetDouble(gd.db, "cidd2skewt.windv_scale",1.0);
    gd.V_wind.bias = XRSgetDouble(gd.db, "cidd2skewt.windv_bias",0.0);
     
}

/*****************************************************************
 * MODIFY_XVIEW_OBJECTS : Modify any Xview objects that couldn't
 *    be set up in Devguide. This is primarily to avoid manually
 *    changing any *ui.c file
 */

void modify_xview_objects(void)
{
    int i;
    char string[128];

    sprintf(string,"%g",gd.base_press);
    xv_set(gd.C2s_base_win_c2s_bw->slp_tx, PANEL_VALUE,string,NULL);

    xv_set(gd.Load_pu_popup1->fname_tx, PANEL_VALUE,gd.fname,NULL);
    xv_set(gd.Load_pu_popup1->dir_tx, PANEL_VALUE,gd.data_dir,NULL);
}
