#
# Recursive make - makes the subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	load_spdb \
	metar2spdb \
	metar_repeat_day \
	print_spdb \
	print_spdb_index

include $(RAP_MAKE_INC_DIR)/rap_make_recursive_dir_targets





