#
# Recursive make - makes the subdirectory code
#

include $(LROSE_CORE_DIR)/build/make_include/lrose_make_macros

TARGETS = $(GENERAL_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	TimeProps \
	TrackGridStats \
	TrackProps \
	Tracks2Ascii \
	VerifyTracks \
	storms_to_ascii \
	storms_to_tifs \
	track_print \
	verify_day \
	verify_grid
        
include $(LROSE_CORE_DIR)/build/make_include/lrose_make_recursive_dir_targets
