/* *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* */
/* ** Copyright UCAR (c) 1990 - 2016                                         */
/* ** University Corporation for Atmospheric Research (UCAR)                 */
/* ** National Center for Atmospheric Research (NCAR)                        */
/* ** Boulder, Colorado, USA                                                 */
/* ** BSD licence applies - redistribution and use in source and binary      */
/* ** forms, with or without modification, are permitted provided that       */
/* ** the following conditions are met:                                      */
/* ** 1) If the software is modified to produce derivative works,            */
/* ** such modified software should be clearly marked, so as not             */
/* ** to confuse it with the version available from UCAR.                    */
/* ** 2) Redistributions of source code must retain the above copyright      */
/* ** notice, this list of conditions and the following disclaimer.          */
/* ** 3) Redistributions in binary form must reproduce the above copyright   */
/* ** notice, this list of conditions and the following disclaimer in the    */
/* ** documentation and/or other materials provided with the distribution.   */
/* ** 4) Neither the name of UCAR nor the names of its contributors,         */
/* ** if any, may be used to endorse or promote products derived from        */
/* ** this software without specific prior written permission.               */
/* ** DISCLAIMER: THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS  */
/* ** OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED      */
/* ** WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.    */
/* *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* */
/*******************************************
 * ufnexrad2gate_tdrp.h
 *
 * TDRP header file for 'ufnexrad2gate' module.
 *
 * Code for program ufnexrad2gate
 *
 * This header file has been automatically
 * generated by TDRP, do not modify.
 *
 *******************************************/

#ifndef _ufnexrad2gate_tdrp_h
#define _ufnexrad2gate_tdrp_h

#ifdef __cplusplus
extern "C" {
#endif

#include <tdrp/tdrp.h>

/*
 * typedefs
 */

typedef enum {
  SCAN_SECTOR_MODE = 0,
  SCAN_RHI_MODE = 1,
  SCAN_SURVEILLANCE_MODE = 2
} ufnexrad2gate_scan_mode;

typedef struct {
  char* file_id_string;
  char* field_name;
  long field_factor;
  long field_scale;
  long field_bias;
  tdrp_bool_t primary_flag;
} ufnexrad2gate_file_info;

typedef struct {
  double target_elevation;
  long primary_tilt;
  long secondary_tilt;
} ufnexrad2gate_tilt_table;

typedef struct {
  long radar_id;
  long samples_per_beam;
  double pulse_width;
  double wavelength;
} ufnexrad2gate_radar_params;

/*
 * typedef for main struct - ufnexrad2gate_tdrp_struct
 */

typedef struct {

  size_t struct_size;

  /***** file_info *****/

  struct {
    ufnexrad2gate_file_info *val;
    int len;
  } file_info;
  ufnexrad2gate_file_info *_file_info;
  int file_info_n;

  /***** tilt_table *****/

  struct {
    ufnexrad2gate_tilt_table *val;
    int len;
  } tilt_table;
  ufnexrad2gate_tilt_table *_tilt_table;
  int tilt_table_n;

  /***** radar_params *****/

  ufnexrad2gate_radar_params radar_params;

  /***** debug *****/

  tdrp_bool_t debug;

  /***** malloc_debug_level *****/

  long malloc_debug_level;

  /***** data_field_by_field *****/

  tdrp_bool_t data_field_by_field;

  /***** set_time_to_current *****/

  tdrp_bool_t set_time_to_current;

  /***** scan_mode *****/

  ufnexrad2gate_scan_mode scan_mode;

  /***** summary_interval *****/

  long summary_interval;

  /***** summary_print *****/

  tdrp_bool_t summary_print;

  /***** header_interval *****/

  long header_interval;

  /***** header_print *****/

  tdrp_bool_t header_print;

  /***** output_port *****/

  long output_port;

  /***** check_gate_spacing *****/

  tdrp_bool_t check_gate_spacing;

  /***** target_gate_spacing *****/

  long target_gate_spacing;

  /***** target_start_range *****/

  long target_start_range;

  /***** device_read_wait *****/

  long device_read_wait;

  /***** ngates_out *****/

  long ngates_out;

  /***** ngates_dropped *****/

  long ngates_dropped;

  /***** time_correction *****/

  long time_correction;

  /***** input_file_path *****/

  char* input_file_path;

  /***** input_file_spec *****/

  char* input_file_spec;

} ufnexrad2gate_tdrp_struct;

/*
 * function prototypes
 */

/*************************************************************
 * ufnexrad2gate_tdrp_load_from_args()
 *
 * Loads up TDRP using the command line args.
 *
 * Check TDRP_usage() for command line actions associated with
 * this function.
 *
 *   argc, argv: command line args
 *
 *   ufnexrad2gate_tdrp_struct *params: loads up this struct
 * 
 *   char **override_list: A null-terminated list of overrides
 *     to the parameter file.
 *     An override string has exactly the format of an entry
 *     in the parameter file itself.
 *
 *   char **params_path_p: if non-NULL, this is set to point to
 *                         the path of the params file used.
 *
 *  Returns 0 on success, -1 on failure.
 */

extern int ufnexrad2gate_tdrp_load_from_args(int argc, char **argv,
                                ufnexrad2gate_tdrp_struct *params,
                                char **override_list,
                                char **params_path_p);

/*************************************************************
 * ufnexrad2gate_tdrp_load()
 *
 * Loads up TDRP for a given module.
 *
 * This version of load gives the programmer the option to load
 * up more than one module for a single application. It is a
 * lower-level routine than ufnexrad2gate_tdrp_load_from_args,
 * and hence more flexible, but the programmer must do more work.
 *
 *   char *param_file_path: the parameter file to be read in.
 *
 *   ufnexrad2gate_tdrp_struct *params: loads up this struct
 *
 *   char **override_list: A null-terminated list of overrides
 *     to the parameter file.
 *     An override string has exactly the format of an entry
 *     in the parameter file itself.
 *
 *  expand_env: flag to control environment variable
 *                expansion during tokenization.
 *              If TRUE, environment expansion is set on.
 *              If FALSE, environment expansion is set off.
 *
 *  Returns 0 on success, -1 on failure.
 */

extern int ufnexrad2gate_tdrp_load(char *param_file_path,
                      ufnexrad2gate_tdrp_struct *params,
                      char **override_list,
                      int expand_env, int debug);

/*************************************************************
 * ufnexrad2gate_tdrp_load_defaults()
 *
 * Loads up defaults for a given module.
 *
 * See ufnexrad2gate_tdrp_load() for more details.
 *
 *  Returns 0 on success, -1 on failure.
 */

extern int ufnexrad2gate_tdrp_load_defaults(ufnexrad2gate_tdrp_struct *params,
                               int expand_env);

/*************************************************************
 * ufnexrad2gate_tdrp_sync()
 *
 * Syncs the user struct data back into the parameter table,
 * in preparation for printing.
 */

extern void ufnexrad2gate_tdrp_sync(void);

/*************************************************************
 * ufnexrad2gate_tdrp_print()
 * 
 * Print params file
 *
 * The modes supported are:
 *
 *   PRINT_SHORT:   main comments only, no help or descriptions
 *                  structs and arrays on a single line
 *   PRINT_NORM:    short + descriptions and help
 *   PRINT_LONG:    norm  + arrays and structs expanded
 *   PRINT_VERBOSE: long  + private params included
 */

extern void ufnexrad2gate_tdrp_print(FILE *out, tdrp_print_mode_t mode);

/*************************************************************
 * ufnexrad2gate_tdrp_free_all()
 *
 * Frees up all TDRP dynamic memory.
 */

extern void ufnexrad2gate_tdrp_free_all(void);

/*************************************************************
 * ufnexrad2gate_tdrp_check_all_set()
 *
 * Return TRUE if all set, FALSE if not.
 *
 * If out is non-NULL, prints out warning messages for those
 * parameters which are not set.
 */

extern int ufnexrad2gate_tdrp_check_all_set(FILE *out);

/*************************************************************
 * ufnexrad2gate_tdrp_check_is_set()
 *
 * Return TRUE if parameter is set, FALSE if not.
 *
 */

extern int ufnexrad2gate_tdrp_check_is_set(char *param_name);

/*************************************************************
 * ufnexrad2gate_tdrp_array_realloc()
 *
 * Realloc 1D array.
 *
 * If size is increased, the values from the last array entry is
 * copied into the new space.
 *
 * Returns 0 on success, -1 on error.
 */

extern int ufnexrad2gate_tdrp_array_realloc(char *param_name,
                              int new_array_n);

/*************************************************************
 * ufnexrad2gate_tdrp_array2D_realloc()
 *
 * Realloc 2D array.
 *
 * If size is increased, the values from the last array entry is
 * copied into the new space.
 *
 * Returns 0 on success, -1 on error.
 */

extern int ufnexrad2gate_tdrp_array2D_realloc(char *param_name,
                                 int new_array_n1,
                                 int new_array_n2);

/*************************************************************
 * ufnexrad2gate_tdrp_table()
 *
 * Returns pointer to static Table for this module.
 */

extern TDRPtable *ufnexrad2gate_tdrp_table(void);

/*************************************************************
 * ufnexrad2gate_tdrp_init()
 *
 * Module table initialization function.
 *
 *
 * Returns pointer to static Table for this module.
 */

extern TDRPtable *ufnexrad2gate_tdrp_init(ufnexrad2gate_tdrp_struct *params);

#ifdef __cplusplus
}
#endif

#endif

