/* *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* */
/* ** Copyright UCAR (c) 1990 - 2016                                         */
/* ** University Corporation for Atmospheric Research (UCAR)                 */
/* ** National Center for Atmospheric Research (NCAR)                        */
/* ** Boulder, Colorado, USA                                                 */
/* ** BSD licence applies - redistribution and use in source and binary      */
/* ** forms, with or without modification, are permitted provided that       */
/* ** the following conditions are met:                                      */
/* ** 1) If the software is modified to produce derivative works,            */
/* ** such modified software should be clearly marked, so as not             */
/* ** to confuse it with the version available from UCAR.                    */
/* ** 2) Redistributions of source code must retain the above copyright      */
/* ** notice, this list of conditions and the following disclaimer.          */
/* ** 3) Redistributions in binary form must reproduce the above copyright   */
/* ** notice, this list of conditions and the following disclaimer in the    */
/* ** documentation and/or other materials provided with the distribution.   */
/* ** 4) Neither the name of UCAR nor the names of its contributors,         */
/* ** if any, may be used to endorse or promote products derived from        */
/* ** this software without specific prior written permission.               */
/* ** DISCLAIMER: THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS  */
/* ** OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED      */
/* ** WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.    */
/* *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* */

/************************************************************************
 * params.hh
 *
 * Text for print_params
 *
 * RAP, NCAR, Boulder CO
 *
 * February 2009
 *
 * Nancy Rehak
 ************************************************************************/

static const string ParamsTextMasterHeader =
"#####################################################################################\n"
"#  CIDD.master\n"
"#  Configurable Interactive Data Display Master Params\n"
"#\n"
"#  NCAR/RAP May 2000  -FH.\n"
"# \n"
"#  Note:  This is an example file for the Configurable Interactive Data Display (CIDD).\n"
"#\n"
"#  The order of the various sections of the param file is arbitrary and are delimited by\n"
"#   <SECTION_NAME> ...Content... </SECTION_NAME>    tags\n"
"#\n"
"# Currently Supported sections:\n"
"#\n"
"#  GRIDS   - Describes each source of data and which color scales to use, etc.\n"
"#  WINDS   - Describes each source of wind data.\n"
"#  MAPS    - Describes each map overlay source\n"
"#  MAIN_PARAMS - Controls most of the features of the Display - Sets domains, menu bars, etc.\n"
"#  DRAW_EXPORT - (TDRP syntax) Describes possible products to manually draw.\n"
"#  SYMPRODS    - (TDRP syntax) Describes the sources of Symbolic Product Data\n"
"#  TERRAIN     - (TDRP syntax) Describes the of Land Use and Terrain Data\n"
"#  ROUTE_WINDS  - (TDRP syntax) Describes the Pre-defined Route's Features\n"
"#  GUI_CONFIG -   (TDRP syntax)  Describes New GUI Feature Parameters for CIDD\n"
"#\n"
"#####################################################################################\n"
"\n";

static const string ParamsTextGrids =
"<GRIDS>\n"
"# Legend Label: used for all on-screen labels and for movie/html file naming.\n"
"#           An Empty grid field can be obtained by using the keyword \"None\"\n"
"#\n"
"# Button Label:  used for all menus.\n"
"#\n"
"# URL:  is of the form:  mdvp:://host.domain:[port]:dir/dir&Field_name.\n"
"#                          (Run the DsServerMgr executable for mdvp service)\n"
"#   Spaces can be in field names by substituting a Caret character for the space:\n"
"#\n"
"#   Field^Name = \"Field Name\"\n"
"#   Field Index can alternatively be specified by prepending a '#' character to the field\n"
"#\n"
"# Colorscale:  Name of the file containing the value to color mapping for this field.\n"
"#\n"
"# Units:  A label used on the color scales, etc.\n"
"#\n"
"# Cont-lo-hi-interv:  Default/Starting Contour low and high limits and interval.\n"
"# Note: Setting the Contour interval to 0.0 tells CIDD to use the color scale\n"
"# for its colors and values. This feature is used to produce color coded\n"
"# line contours.\n"
"#\n"
"# Rendering Format: The style to render the grid. Current options are:\n"
"#  cart:  - Rectangle/polygon fills of gridded data. (note \"radial\" is also\n"
"#           supported for backwards compatibility. CIDD now \"auto detects\"\n"
"#           datasets with non-rectangular grid cells.\n"
"#  cont:  - False color filled  contours.\n"
"#  lcont:  - Line contours.\n"
"#  dcont:  - Dynamic Contours - Automatically switches between cart & cont.\n"
"#          - Uses the 'cidd.dynamic_contour_threshold:' parameter\n"
"#  Note: Add the word \"comp\" to the format keyword to turn on composite request by default:\n"
"#     example:  cont,comp for a composite color filled contours.\n"
"#     example:  cart,comp for a composite filled polygon rendering\n"
"#        Add the word \"autoscale\" to the format keyword to turn on automatic color scale scaling\n"
"#        (In this mode the color scale will be expanded/shrunk to cover the dynamic range of the\n"
"#        data plane in memory, with regular, linear intervals.)\n"
"#     example:  cont,comp,autoscale for a composite color filled contours, that is auto-scaled.\n"
"#\n"
"# Display_in_menu: Display this field in the main menu. (1 = Yes 0 = No)\n"
"# Bkgnd_Render: Render this field automatically in the background. (1 = Yes 0 = No)\n"
"#  Note: This is used to set up \"toggle-able\" field images for comparing two fields,\n"
"#  and to select which fields get generated in HTML output mode. \n"
"\n"
"#----------------------------------------------------------------------------------------------------------\n"
"#Legend   Button                                                             Rendering\n"
"#Label    Label       URL           Colorscale Units Cont-lo-hi-interv Format Display_in_menu Bkgnd_Render\n"
"#----------------------------------------------------------------------------------------------------------\n"
"Nat_DBZ_Mosiac NSSL_MOSAIC  mdvp:://ncwf-4::ncwf/mdv/nsslMosaic2D/merged&#0  dbz.colors      dbz     0 0 0   cart  1 0\n"
"#\n"
"KFTG_DBZ  FTG_DBZ_0.5  mdvp:://tundra::dia/mdv/nids/radial_dbz/ftg&dbz   dbz.colors    dBZ     -5   80  5  cart   1 0\n"
"KFTG_VEL  FTG_VEL.5  mdvp:://tundra::dia/mdv/nids/radial_vel/ftg&vel   dbz.colors    dBZ     -5   80  5  cart   1 0\n"
"\n"
"KCYS_DBZ  CYS_DBZ_0.5  mdvp:://tundra::dia/mdv/nids/radial_dbz/cys&dbz   dbz.colors    dBZ     -5   80  5  cart   1 0\n"
"KCYS_VEL  CYS_VEL.5  mdvp:://tundra::dia/mdv/nids/radial_vel/cys&vel   dbz.colors    dBZ     -5   80  5  cart   1 0\n"
"#\n"
"KPUX_DBZ  PUX_DBZ_0.5  mdvp:://tundra::dia/mdv/nids/radial_dbz/pux&dbz   dbz.colors    dBZ     -5   80  5  cart   1 0\n"
"KPUX_VEL  PUX_VEL.5  mdvp:://tundra::dia/mdv/nids/radial_vel/pux&vel   dbz.colors    dBZ     -5   80  5  cart   1 0\n"
"#\n"
"KGLD_DBZ  GLD_DBZ_0.5  mdvp:://tundra::dia/mdv/nids/radial_dbz/gld&dbz   dbz.colors    dBZ     -5   80  5  cart   1 0\n"
"KGLD_VEL  GLD_VEL.5  mdvp:://tundra::dia/mdv/nids/radial_vel/gld&vel   dbz.colors    dBZ     -5   80  5  cart   1 0\n"
"#\n"
"KDDC_DBZ  DDC_DBZ_0.5  mdvp:://tundra::dia/mdv/nids/radial_dbz/ddc&dbz   dbz.colors    dBZ     -5   80  5  cart   1 0\n"
"KDDC_VEL  DDC_VEL.5  mdvp:://tundra::dia/mdv/nids/radial_vel/ddc&vel   dbz.colors    dBZ     -5   80  5  cart   1 0\n"
"#\n"
"KAMA_DBZ  AMA_DBZ_0.5  mdvp:://tundra::dia/mdv/nids/radial_dbz/ama&dbz   dbz.colors    dBZ     -5   80  5  cart   1 0\n"
"KAMA_VEL  AMA_VEL.5  mdvp:://tundra::dia/mdv/nids/radial_vel/ama&vel   dbz.colors    dBZ     -5   80  5  cart   1 0\n"
"#\n"
"KLNX_DBZ  LNX_DBZ_0.5  mdvp:://tundra::dia/mdv/nids/radial_dbz/lnx&dbz   dbz.colors    dBZ     -5   80  5  cart   1 0\n"
"#\n"
"KVNX_DBZ  VNX_DBZ_0.5  mdvp:://tundra::dia/mdv/nids/radial_dbz/vnx&dbz   dbz.colors    dBZ     -5   80  5  cart   1 0\n"
"#\n"
"KICT_DBZ  ICT_DBZ_0.5  mdvp:://tundra::dia/mdv/nids/radial_dbz/ict&dbz   dbz.colors    dBZ     -5   80  5  cart   1 0\n"
"#\n"
"KGJX_DBZ  GJX_DBZ_0.5  mdvp:://tundra::dia/mdv/nids/radial_dbz/gjx&dbz   dbz.colors    dBZ     -5   80  5  cart   1 0\n"
"\n"
"TREC_DBZ  TREC_DBZ_0.5 mdvp:://tundra::dia/mdv/trec/ftg&dbz   dbz.colors    dBZ     -5   80  5  cart   1 0\n"
"#\n"
"TREC_U    TREC_U  mdvp:://tundra::dia/mdv/trec/ftg&#1   vel.colors dBZ  -5   80  5  cart,autoscale   1 0\n"
"TREC_V    TREC_V  mdvp:://tundra::dia/mdv/trec/ftg&#2   vel.colors dBZ  -5   80  5  cart,autoscale   1 0\n"
"#\n"
"</GRIDS>\n"
"\n";

static const string ParamsTextWinds =
"<WINDS>\n"
"#----------------------------------------------------------------------------\n"
"# Note:\n"
"# Legend_label: Used for Image Labels and Menus\n"
"# URL: should be of the form \"protocol://host:port/dir/&\" \n"
"#   The U,V and W field names will be appended to complete the URL\n"
"#   Use the name \"None\" to indicate no W field component.\n"
"# U: The  East-West Wind component Field name \n"
"#   Spaces can be in field names by substituting a Caret character for the space:\n"
"#   Example: Field^Name = \"Field Name\"\n"
"#   Field Index can alternatively be specified by prepending a '#' character to the field \n"
"#   (Use this if there are duplicate field names in the data files)\n"
"#   Example: First field in file = \"#1\"\n"
"# V: North-South Wind component Field name \n"
"# W: Up-Down  Wind component Field name - Use \"None\" to indicate no W field\n"
"#\n"
"#  Units: Labels append this (for barbs and reference lines) \n"
"# \n"
"# Style: This column is broken in to several components for backward compatibility\n"
"# 1. A mandatory number must be first.\n"
"#     Absolute value of the number is the starting Line width.\n"
"#     Values <= 0 Turns it off to begin with\n"
"# 2. Second component is a comma followed by the rendering style:  \n"
"#     Wind Rendering Style  Options:\n"
"#     \"arrow\" (centered at data point),\n"
"#     \"vector\",(Vertex at data point )\n"
"#     \"barb\" (N Hemisp),\n"
"#     \"labeledbarb\", (labeled to nearest 10 degrees at the center - N. Hemisp)\n"
"#     \"tuft\", (like a piece of yarn - the least obtrusive - like a headless vector)\n"
"#     \"tickvector\" (Cross ticks at wind_time_scale_interval  minutes)\n"
"#     \"metbarb\" (Calcs latitude - works for both hemispheres and\n"
"#     adds a label of the 10's digit off the end of the barb, ala winds aloft charts)\n"
"#     \"barb_sh\" (S Hemisphere),\n"
"#     \"labeledbarb\", (labeled to nearest 10 degrees at the center - N. Hemisp)\n"
"#     NOTE: When using arrow,vector,tuft,tickvector,  the data must be in\n"
"#     m/sec for the scaling to work correctly. For the others (Barbs),\n"
"#     the units are arbitrary, but the flag units on the barbs will reflect\n"
"#     the data's native units. \n"
"# Example: \"-2,metbarb\" -->  Width 2, off to start, using winds aloft chart barbs\n"
"# Example: \"1\"  --> Width 1, On to start, Uses cidd.wind_marker_type: defined in main section\n"
"#\n"
"# Color: Any Legal X color name - Can be several words, Example: dark green\n"
"#\n"
"# Legend_label  URL U V W_fieldnames units  Style [Color]\n"
"#----------------------------------------------------------------------------\n"
"TREC    mdvp:://tundra::dia/mdv/ctrec/ftg&  #1 #2 None  m/s  0      yellow\n"
"\n"
"</WINDS>\n"
"\n";

static const string ParamsTextMaps =
"<MAPS>\n"
"#\n"
"# MAP_CODE Must be less than 16 characters, Color must be regular X color name\n"
"# Complete map file name used is  map_file_subdir/Map_file_name\n"
"# 0 = OFF, > 0 = ON, line of width N\n"
"# Detail thresholds are in Km across the image.#\n"
"# Note: Maps with Identical Control Labels will have only one GUI Entry and\n"
"#   will be turned on and off as a group.\n"
"#\n"
"#------------------------------------------------------------------------------------------\n"
"# MAP_CODE Control_Label   Map_File_Name   On/OFF Detail__min Detail_max Color     \n"
"#------------------------------------------------------------------------------------------\n"
"\n"
"#Coasts      Coasts         coasts.map             2  0.0 10000.0  white\n"
"\n"
"US_Highways     US_Highways        conus_ushwys.map   1      0.0 1000.0     grey\n"
"\n"
"Interstates    Interstates conus_interstates.map   1      0.0 10000.0     white\n"
"Interstates  Interstates   conus_interstatelabels.map     1    400.0 3000.0  white\n"
"Interstates  Interstates   conus_interstatelabels_high.map  1  0.0 400.0   white\n"
"\n"
"\n"
"DIA_RUNW          DIA_runways           DIA_runways.map      1      0.0 10000.0     yellow\n"
"DIA_TAXI          DIA_taxiways          DIA_taxiways.map     1      0.0 10000.0     gold\n"
"DIA_CONC          DIA_concourse         DIA_concourses.map   1      0.0 10000.0     orange\n"
"#\n"
"Colo_Aviation     Colo_Aviation         Colo_aviation.map    1      0.0 1000.0     cyan \n"
"Colo_Towns        Colo_Towns            Colo_towns.map       1      0.0 1000.0     blue \n"
"Colo_roadmap_A    Colo_roadmap_A        Colo_roadmap_A.map   0      0.0 1000.0     grey\n"
"Colo_counties     Colo_counties         Colo_counties.map    0      0.0 1000.0     yellow \n"
"UDFCD_mesonet     UDFCD_mesonet         Colo_UDFCD_meso.map  0      0.0 100.0      white\n"
"UDFCD_mesonet_ul  UDFCD_mesonet_ul      Colo_UDFCD_meso_unlab.map  0    0.0 100.0  orange\n"
"#\n"
"RADARS            NWS_RADARS            radars.map           0      0.0 10000.0     red\n"
"US_NEXRADS        US_NEXRADS            US_nexrad.map        1      0.0 10000.0     red\n"
"#\n"
"COUNTIES          US_Counties           us_counties.map      1      0.0 1000.0     blue \n"
"STATES            State_Borders         usa.map              1      0.0 10000.0     green \n"
"#\n"
"SAO_MOUNTAIN      SAO_MOUNTAIN          mountain_sao.map     0      0.0 10000.0     yellow \n"
"#DIA_METARS       CO METARS             FTG_METAR.map        1      0.0 10000.0     red\n"
"</MAPS>\n"
"\n";

static const string ParamsTextMainParams =
"######################################################################################\n"
"######################################################################################\n"
"######################################################################################\n"
"######################################################################################\n"
"######################################################################################\n"
"<MAIN_PARAMS>\n"
"\n"
"# Parameter data base for the Configurable Interactive Data Display; CIDD\n"
"\n"
"# Note: One can set these from the command line using the -v flag.\n"
"# The value is a bitwise combination of the following debug\n"
"# parameters. Example : -v7 turns on all three -v 3, the first two\n"
"\n"
"# General informational messages - Initialization messages\n"
"cidd.debug_flag:            0\n"
"\n"
"# Data flow related messages  - More verbose\n"
"cidd.debug1_flag:           0\n"
"\n"
"# Verbose diagnostics - developer debugging info - \n"
"cidd.debug2_flag:           0\n"
"\n"
"# Uncomment the next parameter to start up cidd in archival mode\n"
"#  Starting at the indicated time. Enter HH:MM MM/DD/YY format time string\n"
"#  System will startup using field 0, requesting data closest to the\n"
"# demo time. The movie frame will be centered on the time after applying\n"
"# temporal rounding. \n"
"#cidd.demo_time:  20:00 5/25/2000\n"
"\n"
"# Set times to the nearest value divisible by the number of seconds\n"
"cidd.temporal_rounding:    300\n"
"\n"
"# Sets the time_interval to \"regular\", \"daily\" or \"yearly\"\n"
"# CIDD users can do this interactively by entering \"1 yr\" or \"1 day\"\n"
"# in the movie control panel  interval text widget. CIDD will recognize these special\n"
"# \"intervals\" and will do the right thing.\n"
"cidd.climo_mode: regular\n"
"\n"
"# Maximum number of days over which to request time lists.\n"
"# If the epoch exceeds this number of days, then no time list requests\n"
"# will be made. Time lists requests spanning many years can take too long.\n"
"cidd.max_time_list_span: 365\n"
"\n"
"#  MOVIE Related resources\n"
"\n"
"#  This determines how many movie frames are in the loop to start with\n"
"#  Setting this high will cause the X server to hog memory.\n"
"cidd.starting_movie_frames:     16\n"
"\n"
"# Minutes per movie frame on startup\n"
"# The display will automatically update every this interval, throwing away its\n"
"# oldest movie frame and creating and drawing a new one.\n"
"# \n"
"cidd.time_interval:  5.0\n"
"\n"
"# Span in minutes a frame covers in Climo mode. - The time_interval will be\n"
"# either \"1 day\" or \"1 year\" \n"
"cidd.frame_span:  60.0\n"
"\n"
"# This parameter sets the maximum number of hours in the future a user can select\n"
"# from the quick forecast menu. See SHOW_FORECAST_MENU menu bar button\n"
"cidd.forecast_interval:  24\n"
"\n"
"# This parameter sets the maximum number of hours in the PAST a user can select\n"
"# from the quick forecast menu. See SHOW_PAST_MENU menu bar button\n"
"cidd.past_interval:  96\n"
"\n"
"# When a Forecast hour is chosen, magnify the time interval by this factor.\n"
"# This adjusts the frame time_interval to be more appropriate for \n"
"# forecast (model) data, which is often output on a more coarse time interval.\n"
"# When \"Now\" is selected the magnification is undone. Default is 1.0\n"
"# \n"
"cidd.movie_magnify_factor:  10.0\n"
"\n"
"# Set this param to 1 to get CIDD to check and reject for rendering\n"
"# Any data that falls outside the movie frame interval + the\n"
"# slop/stretch_factor - Used to reject \"out of date\" data.\n"
"cidd.check_data_times:  0\n"
"\n"
"\n"
"# Set this parameter to 1 when displaying data on dissimilar grid projections\n"
"# and stripes or other artifacts are rendered. CIDD will then check each polygon\n"
"# to make sure it will render correctly. This slows down CIDD's rendering a bit\n"
"# so it is off by default.\n"
"cidd.check_clipping:  0\n"
"\n"
"# Sets the allowable time error for data to appear in movie frames\n"
"# (times the time_interval) (6 min * 6 = 36 minutes before or after\n"
"# the beginning or end of the movie frame times\n"
"cidd.stretch_factor:     6.0\n"
"\n"
"# Sets whether Cidd request data closest to the midpoint of a movie\n"
"# frame (0) or the end (1). \n"
"# 0= Midpoint requests(Closest_to), 1 = End point requests (First_before).\n"
"# Typically, real-time operation should operate as 1 (End point requests)\n"
"# Choose mode 0 if you want to enter a time and have data the data\n"
"# at that time appear, regardless of how wide the movie frame interval is.\n"
"cidd.gather_data_mode:  0\n"
"\n"
"# Number of milliseconds between checks for images needing redrawn\n"
"# Set this lower on faster hardware - Recommended 50-250\n"
"# This sets the ultimate speed of the movie looping\n"
"cidd.redraw_interval:     100\n"
"\n"
"# Number of seconds between data update requests - The display will\n"
"# check the Data Mapper for new data every interval in real-time mode.\n"
"# Every interval CIDD will check for updates to each grid and product. If\n"
"# no datamap_host is set, the data is assumed to be old and will be reloaded\n"
"# every interval. Set this wisely. Values of 10-900 are typical. Default=120\n"
"# Setting this below 3 seconds is not advised.  interacts with the Data\n"
"# Mapper Host parameter: cidd.datamap_host:\n"
"\n"
"cidd.update_interval:      300\n"
"\n"
"# Data Mapper Host\n"
"#cidd.datamap_host:  venus\n"
"\n"
"#  Number of seconds to wait for data to come in before giving up\n"
"#  On very slow networks this may need to go as high as 180 seconds!\n"
"cidd.data_timeout_secs: 40\n"
"\n"
"# Length of time to wait before killing simple external commands\n"
"# Used When running single image convert scripts and driving\n"
"# Browsers to web pages.\n"
"cidd.simple_command_timeout_secs: 30\n"
"\n"
"# Length of time to wait before killing complex external commands\n"
"# Used when spawning animation building script\n"
"cidd.complex_command_timeout_secs: 180\n"
"\n"
"# Set to 1 to start up cidd in movie-on mode, 0 = off\n"
"cidd.movie_on: 0\n"
"\n"
"# Set the delay at the end of the movie loop in msec \n"
"cidd.movie_delay: 3000\n"
"\n"
"# Set the speed of the movie loop. - (msec per frame)\n"
"cidd.movie_speed_msec: 75\n"
"\n"
"# If set to 1 - forces CIDD to reload all data every time the movie frames \n"
"# rotate one old frame out and generate a new frame.\n"
"cidd.reset_frames:   0\n"
"\n"
"# Gather model run times within these number of hours from the end\n"
"# of the movie loop. More hours means more Model runs will appear in the menu.\n"
"cidd.model_run_list_hours:  24   \n"
"\n"
"# After this period of inactivity, the display\n"
"# will reset itself to a known starting point\n"
"# Set this <= 0 to essentially turn off.\n"
"cidd.idle_reset_seconds: 0\n"
"\n"
"# HTML Mode - Set this to 1 to put CIDD into the automatic HTML output mode.\n"
"# Note: cidd.image_dir MUST be set.\n"
"cidd.html_mode: 0\n"
"\n"
"# Set to 1 if one wants CIDD to run once through its HTML output\n"
"# plot list and then exit - Currently all fields at each zoom level\n"
"cidd.run_once_and_exit: 0\n"
"\n"
"# Set transparency of generated images.\n"
"# If 0, the normal background color is used.\n"
"# Set to 1 for transparent background.\n"
"cidd.transparent_images: 0\n"
"\n"
"# Image Generation related resources\n"
"\n"
"# Set this to a value to get cidd to output imagery in this directory\n"
"#cidd.image_dir: /tmp\n"
"\n"
"# Save images to subdirs based on date?\n"
"#cidd.save_images_to_day_subdir: 0\n"
"\n"
"# Image extension - Sets the output image types\n"
"# In latest CIDD versions, only png type is available.\n"
"cidd.image_ext: png\n"
"\n"
"# The prefix for the horiz and vert image file names\n"
"cidd.image_horiz_prefix: CH\n"
"cidd.image_vert_prefix: CV\n"
"# The separator used in the image file names\n"
"cidd.image_name_separator: _\n"
"# The HTML MODE Output file name is built from parts.\n"
"# Some of these are optional - see related parameters below.\n"
"# 'Prefix' + Frame_number + legend_name + zoom_level + [button_name] + [height] +\n"
"#  frame_time + [data_generation_time] + [data_valid_time] + .'cidd.image_ext'\n"
"\n"
"# When set to 1 forces the output filename to contain height\n"
"# See the comment above on the order\n"
"cidd.add_height_to_filename: 1\n"
"\n"
"# When set to 1 forces the output filename to contain the Frame Number.\n"
"# See the comment above on the order\n"
"cidd.add_frame_num_to_filename: 1\n"
"\n"
"# When set to 1 forces the output filename to contain the button_name\n"
"# See the comment above on the order.\n"
"cidd.add_button_name_to_filename: 0\n"
"\n"
"# When set to 1 forces the output filename to contain the Frame time\n"
"# its image file name.  See the comment above on the order\n"
"cidd.add_frame_time_to_filename: 1\n"
"\n"
"# When set to 1 forces the output filename to contain the data's generation\n"
"# time in its file name.  See the comment above on the order\n"
"cidd.add_gen_time_to_filename: 0\n"
"\n"
"# When set to 1 forces the output filename to contain  the data's valid\n"
"# time in its file name.  See the comment above on the order\n"
"cidd.add_valid_time_to_filename: 0\n"
"# \n"
"# Separate Horizontal and Vertical Image save resources    \n"
"#\n"
"# NOTE: CIDD appends the image name to the command string before executing.\n"
"# This allows the script to pull the name off the command line.\n"
"# It is often useful to place a \"rm\" as the last command to remove\n"
"# the image after printing, conversion, etc\n"
"#\n"
"# Note: that this is initially set to cidd.image_dir\n"
"cidd.horiz_image_dir:   /tmp\n"
"# The default file name until reset by the user - Appends other info automatically\n"
"cidd.horiz_image_fname   CH\n"
"# Note that this is initially set to cidd.image_convert_script\n"
"cidd.horiz_image_command:  convert_image.csh\n"
"#\n"
"# Note that this is initially set to cidd.image_dir\n"
"cidd.vert_image_dir:    /tmp\n"
"# The default file name until reset by the user - Appends other info automatically\n"
"cidd.vert_image_fname:  CV\n"
"# Note that this is initially set to cidd.image_convert_script\n"
"cidd.vert_image_command:  convert_image.csh\n"
"\n"
"# Output an imagename.xml file which contains geo referencing information.\n"
"# If use_latlon_in_geo_xml is true, then the georeferencing information\n"
"# will be given in latitude/longitude values.  Otherwise, projection values\n"
"# will be used. (For a lat/lon projection, information is always given in\n"
"# latitude/longitude.)\n"
"cidd.output_geo_xml: 0\n"
"cidd.use_latlon_in_geo_xml: 0\n"
"\n"
"# Set the format for the time fields in the names of output xwd images.\n"
"# See strftime(3) for options.  Default is: %H%M\n"
"cidd.movieframe_time_format:  %H%M\n"
"\n"
"# This script will be exec'd if set whenever an html_mode image is output.\n"
"# The full path name of the xwd image will be sent as the script argument\n"
"# Setting cidd.horiz_image_command or cidd.horiz_image_command will override\n"
"# this and allow separate scripts to be called for horiz and vert images.\n"
"#cidd.image_convert_script: convert_image.csh\n"
"\n"
"# This script will be exec'd if set whenever a print command is issued.\n"
"# The full path name of the xwd image will be sent as the script argument\n"
"cidd.print_script: convert_image_print.csh\n"
"\n"
"# This script will be exec'd if set whenever the user selects the Output Loop\n"
"# Button, after the last image has output. The arguments will be a list\n"
"# of each output file in the series. CIDD will prepends the cidd.image_dir to each\n"
"# files name which takes the form: cidd_field_name_zoom_name.xwd \n"
"cidd.series_convert_script: make_anim.csh\n"
"\n"
"# Set to 1 to ask that data be compressed during the MDV Protocol\n"
"# data requests. Default is = 0\n"
"cidd.request_compressed_data: 1\n"
" \n"
"# Set to 1 to ask that data be compressed with the newer more efficient GZIP_VOL\n"
"cidd.request_gzip_vol_compression: 0\n"
"\n"
"#                  DOMAIN RELATED RESOURCES \n"
"#\n"
"# Sets the projection for cidd's plan view - Current valid choices are:\n"
"# CARTESIAN, LAT_LON, LAMBERT,  POLAR_STEREO, STEREOGRAPHIC, MERCATOR\n"
"# Mercator is relative to the longitude origin.\n"
"cidd.projection_type:    CARTESIAN\n"
"\n"
"# These must be set if using a LAMBERT conformal projection - Ignored otherwise\n"
"cidd.lambert_lat1: 20.0\n"
"cidd.lambert_lat2: 60.0 \n"
"\n"
"# These must be set when using POLAR_STEREO (Polar stereographic)\n"
"#cidd.tangent_lat: 90.0\n"
"#cidd.tangent_lon: 0.0\n"
"#cidd.central_scale: 1.0\n"
"\n"
"# These must be set when using STEREOGRAPHIC (Oblique stereographic)\n"
"cidd.tangent_lat: 60.0\n"
"cidd.tangent_lon: 0.0\n"
"cidd.central_scale: 1.0\n"
"\n"
"# Set this to the amount grids are rotated clockwise to true north.\n"
"# Overlays will rotate counterclockwise. - In Degrees\n"
"# Only valid for CARTESIAN projection\n"
"cidd.north_angle:        0.0\n"
"\n"
"# Diagnostic mode used to ignore the Elevation angle on polar data (radars, etc).\n"
"# Set to 0 to display all polar grids as if the elevation were always 0.0 degrees.\n"
"# Allows one to view radial data near 90 degrees elevation.\n"
"# Note: \n"
"cidd.use_cosine: 1\n"
"\n"
"# Set the scale factor and label for Range rings and Distance scales.\n"
"#cidd.units_per_km:          0.5395932\n"
"\n"
"# Set the following to Deg for LAT_LON projections - Default is \"km\"\n"
"#cidd.scale_units_label:  nm\n"
"\n"
"# When set to 1, Request the outer domain established by cidd.domain_limit params\n"
"cidd.always_get_full_domain:  0\n"
"\n"
"# When set to 1, Request the whole earth or Hemisphere, centered on the origin.\n"
"cidd.do_not_clip_on_mdv_request:  0\n"
"\n"
"# When set to 1, do not decimate on MDV request, get all points from MDV server\n"
"cidd.do_not_decimate_on_mdv_request:  0\n"
"\n"
"# Minimum distance to zoom into to in KM.  Won't allow the user to define\n"
"# custom zooms small than this size (along the longest edge).\n"
"cidd.min_zoom_threshold: 5.0\n"
"\n"
"# Set the aspect ratio of the domain for Cidd. Cidd will preserve this aspect\n"
"# ration for all zooms. Ratio is Width/Height.\n"
"# If set <= 0.0, CIDD will compute the aspect ratio based on the extent of the\n"
"# first domain.\n"
"#cidd.aspect_ratio:   0.0\n"
"cidd.aspect_ratio:   1.1\n"
"\n"
"# Note CIDD now applies a correction to LAT_LON projections to expand the Y coords, making them\n"
"# appear to be equi-distant in Latitude and Longitude.\n"
"# Based on the cos(average latitude of the current view)\n"
"\n"
"# Switch to enable the status window. 0 = off\n"
"cidd.enable_status_window: 1\n"
" \n"
"# Report clicks in the status window \n"
"# By default distance are in km and bearings in Deg \n"
" \n"
"cidd.report_clicks_in_status_window: 1 \n"
"cidd.report_click_move_dist_in_nm: 0 \n"
"cidd.report_click_move_dirn_in_mag: 0 \n"
"cidd.magnetic_variation: 11 \n"
" \n"
"# Switch to enable the single middle button click save image feature\n"
"# Warning - Will allow users shell access, or to write to other dirs.\n"
"cidd.enable_save_image_panel: 1\n"
" \n"
"# On startup and each time the reset button is pressed, the display\n"
"# will indicate a click at this point, as if the user had clicked..\n"
"cidd.reset_click_longitude: 120.0\n"
"cidd.reset_click_latitude:  26.0\n"
"#\n"
"# The Outer most domain: Overlays are clipped to this domain and \n"
"# pan/moves cannot exceed these edge limits. Note: CIDD does not pan on the\n"
"# outermost domain!\n"
"# Note: for Lat/Lon Domains, Choose 0-360, -90+90. to get whole earth\n"
"#    One can also choose Longitude range  -180 to 180, -90 to 270, etc.\n"
"# For whole earth views, aspect ration 1.0,  set the outer most domain\n"
"# to  -180 to 180 and -180 to 180. Otherwise, set the aspect ratio to 2.0\n"
"# and use -180 to 180 and -90 to 90.\n"
"#\n"
"cidd.domain_limit_min_x:        -2900\n"
"cidd.domain_limit_max_x:         2900\n"
"cidd.domain_limit_min_y:        -2900\n"
"cidd.domain_limit_max_y:         2900\n"
" \n"
"# The Lat, Long of the center of the display. Internal range rings\n"
"# are relative to this point.\n"
"cidd.origin_longitude:       -104.5683\n"
"cidd.origin_latitude:        39.7914\n"
"#\n"
"#\n"
"# Select the data fields/page to start on.\n"
"cidd.planview_start_page:   1\n"
"cidd.xsect_start_page:      1\n"
"#\n"
"\n"
"#\n"
"# The Outer most domain:\n"
"cidd.num_zoom_levels:         5\n"
"cidd.start_zoom_level:        1\n"
"cidd.zoom_limits_in_latlon:   0\n"
"\n"
"# The number of Cached images for zooms.\n"
"cidd.num_cache_zooms:       4\n"
"#\n"
"# Note, the Domain labels are used for automated output imagery.\n"
"# It's suggested that names without spaces be used when running\n"
"# in HTML output mode.\n"
"#\n"
"cidd.level1_label:              FULL DOMAIN\n"
"cidd.level1_min_xkm:                -1100.0\n"
"cidd.level1_min_ykm:                -1700.0\n"
"cidd.level1_max_xkm:                2200.0\n"
"cidd.level1_max_ykm:                2000.0\n"
"#\n"
"cidd.level2_label:               FTG AREA\n"
"cidd.level2_min_xkm:                -155.0\n"
"cidd.level2_min_ykm:                -140.0\n"
"cidd.level2_max_xkm:                125.0\n"
"cidd.level2_max_ykm:                140.0\n"
"#\n"
"cidd.level3_label:              AIRPORT\n"
"cidd.level3_min_xkm:                -60.0\n"
"cidd.level3_min_ykm:                -60.0\n"
"cidd.level3_max_xkm:                50.0\n"
"cidd.level3_max_ykm:                50.0\n"
"#\n"
"cidd.level4_label:              ERN PLAINS \n"
"cidd.level4_min_xkm:                -100.0\n"
"cidd.level4_min_ykm:                -400.0\n"
"cidd.level4_max_xkm:                550.0\n"
"cidd.level4_max_ykm:                250.0\n"
"#\n"
"cidd.level5_label:               WRN KS\n"
"cidd.level5_min_xkm:                0.0\n"
"cidd.level5_min_ykm:               -400.0\n"
"cidd.level5_max_xkm:               600.0\n"
"cidd.level5_max_ykm:               150.0\n"
"\n"
"\n"
"# Vertical Range and Resolution - Establishes a vertical coordinate system\n"
"# for the cross sectional imagery.\n"
"# All data must map into this range for it to be visible. \n"
"# min_ht is value nearest the ground - Plotted at the bottom.\n"
"# max_ht is the value furtherest from the ground - Plotted at the top.\n"
"#\n"
"# Units are ignored and no inter conversions or re-mappings are performed.\n"
"# Returned cross sections are are often km, but could be sigma, pressure or degrees elevation. \n"
"# Examples:\n"
"# Sigma : min_ht = 1.0, max_ht = 0.0, ht_interval = .1\n"
"# Pressure : min_ht = 1100.0, max_ht = 100.0, ht_interval = -100\n"
"# Radial Radar:  min_ht = 0.0 max_ht = 25.0, ht_interval = 1.0\n"
"#  \n"
"cidd.min_ht:               0.25\n"
"cidd.max_ht:               22.25\n"
"cidd.ht_interval           0.5\n"
"cidd.start_ht:             0.5\n"
"\n"
"# Radial data Limits\n"
"cidd.min_rkm:                0.0\n"
"cidd.max_rkm:                400.0\n"
"cidd.min_adeg:               0.0\n"
"cidd.max_adeg:               360.0\n"
"\n"
"# List of comma delimited local directories or HTTP URLs to search\n"
"# Search . then each directory/URL in order \n"
"cidd.color_file_subdir:   /local/colorscales, http://www.rap.ucar.edu/colorscales\n"
"cidd.map_file_subdir:     /local/maps, http://www.rap.ucar.edu/maps\n"
"\n"
"#\n"
"# Station locator features\n"
"#\n"
"# Maximum allowed  Distance in km between request point and station\n"
"cidd.locator_margin_km:   50\n"
"\n"
"# Full Path File name or http URL to a station data file.\n"
"# The format of each line is:  ID, LAT, LON, ALT(m), TYPE\n"
"#cidd.station_loc_url: http://www.rap.ucar.edu/maps/Taiwan_stations.dat \n"
"\n"
"#\n"
"# FMQ Type URL for Receiving Remote commands\n"
"#cidd.remote_ui_url: /tmp/remoteUI\n"
"\n"
"# Tunnel for all DsServer (mdvp,spdbp,etc) Protocols\n"
"# USE THIS TO CROSS A FIREWALL ON THE SERVER END OF THE CHAIN \n"
"#Set this to the special http tunnel that resides in the same local\n"
"#network as the  data server hosts. This allows \"tunneling\" the MDV and\n"
"#Spdb data protocols through a host, running apache:httpd that is visible\n"
"#from the Internet or intranet. Note: a special  \"Apache::Mod_perl\"\n"
"#extension (The tunnel - it's similar to a cgi mechanism) must be\n"
"#installed on the http server for this to work.\n"
"#\n"
"#cidd.http_tunnel_url: http://www.rap.ucar.edu/DsServerTunnel\n"
"#\n"
"# USE THIS TO CROSS A FIREWALL AT THE Client/CIDD End of the Chain\n"
"# Set this to the url of a http forwarding proxy to pass \n"
"# http requests through the proxy. \n"
"# This is usually the same as the HTTP proxy URL in your browser.\n"
"# Note. If you need the data to flow through the proxy\n"
"# the http_tunnel_url must be enabled\n"
"#\n"
"# This is NCAR's internal HTTP proxy\n"
"#cidd.http_proxy_url: http://webcache.ucar.edu:3128/  \n"
"#\n"
"# Another view of the possible Service Topologies.\n"
"# \n"
"# All Local - No Firewalls - Standard Setup \n"
"#--------- Local Lan --------------\n"
"# CIDD<--- MDVP --->DsMdvServer\n"
"# \n"
"# Data Services Behind a firewall\n"
"#----- Internet ----|Firewall|------ Local Lan ----------------\n"
"# CIDD<---HTTP--->DsServer Tunnel<---MDVP--->DsMdvServer\n"
"#  \n"
"## Both Client and Data Services behind Firewalls\n"
"#---Local Lan ---|Firewall|--Internet----|Firewall|--------Local Lan ----------\n"
"# CIDD<---HTTP--->Http Proxy<---HTTP--->DsServer Tunnel<---MDVP--->DsMdvServer\n"
"#\n"
"#\n"
"\n"
"#  Plan View and Cross Section COLORS\n"
"#\n"
"# Legends, scales, etc use this color\n"
"cidd.foreground_color: white\n"
"\n"
"# Background of Images use this color\n"
"cidd.background_color: black\n"
"\n"
"# Background of margins will be this color\n"
"cidd.margin_color: black\n"
"\n"
"# Render values outside the data range of the color scale in this color\n"
"# 'transparent' is the default\n"
"cidd.out_of_range_color: transparent\n"
"\n"
"# Color of the cross section reference line \n"
"cidd.route_path_color: yellow\n"
"\n"
"# Text in the time axis margins are this color\n"
"cidd.time_axis_color: pink\n"
"\n"
"# A solid rectangle  showing the movie frame extent is drawn in this color\n"
"cidd.time_frame_color: gray50\n"
"\n"
"# The text in the height selector margin is rendered in this color\n"
"cidd.height_axis_color: pink\n"
"\n"
"# A solid rectangle showing the height extent of the data plane is drawn in this color\n"
"cidd.height_indicator_color: gray50\n"
"\n"
"# Range rings and azimuth lines\n"
"cidd.range_ring_color: gray\n"
"\n"
"# \n"
"# Set the following colors to 'transparent' to avoid having these\n"
"# plotted. (This is the default) Otherwise, these data will be\n"
"# plotted in the indicated color\n"
"cidd.missing_data_color: grey20\n"
"\n"
"cidd.bad_data_color: grey20\n"
"#\n"
"# Time Control (Movie) Pop-up Colors\n"
"cidd.epoch_indicator_color: orange\n"
"cidd.now_time_color: red\n"
"cidd.time_tick_color1: cyan\n"
"cidd.time_tick_color2: yellow\n"
"cidd.time_tick_color3: magenta\n"
"cidd.time_tick_color4: green\n"
"cidd.time_tick_color5: red\n"
"cidd.time_tick_color6: blue\n"
"\n"
"#Toggle for displaying the height Selector in Right Margin\n"
"# Note Right Margin should be at least 50 pixels wide\n"
"cidd.show_height_sel:       1  \n"
"\n"
"# Display data access and rendering messages - This is probably not\n"
"# necessary in situations where all data is small and local.\n"
"cidd.show_data_messages: 1\n"
"\n"
"# Sets the relative intensity of images, relative to the overlays \n"
"# Set between 0.2 and 1.0.\n"
"cidd.image_inten:            0.8\n"
"# The number of selectable intensity levels in the slider control\n"
"cidd.inten_levels:            32\n"
"#\n"
"#\n"
"# Sets the relative intensity of data grid colors, relative to the overlays \n"
"cidd.data_inten:            1.0\n"
"\n"
"# Sets the threshold in drawable grid points where image rendering \n"
"# is done by a filling method on the client, rather than by rectangles\n"
"# on the Xserver.\n"
"# Set this high if the X server is fast or the comm link to the server is slow.\n"
"# Set this low if the X server is slow. Typical values range from 10,000 to\n"
"# 100,000  Used for 'cart' style rendering.\n"
"\n"
"cidd.image_fill_threshold:    80000\n"
"\n"
"# This sets the threshold in grid cells when the the display will\n"
"# render a grid as contours or as filled rectangles. Grids containing\n"
"# less than the threshold cells will be rendered as filled contours.\n"
"# used for 'dcont' style rendering\n"
"cidd.dynamic_contour_threshold:    160000\n"
"\n"
"# Sets the format for output of Lat, Lon's. 0= Decimal Degrees, 1 = deg min' sec\"\n"
"cidd.latlon_mode:        0\n"
"\n"
"# Set the format for the time strings. See 'man strftime' for format options.\n"
"# Can add additional text as part of the Time string.\n"
"# Default is: \"%m/%d/%Y %H:%M:%S\"\n"
"cidd.label_time_format:  %m/%d/%Y %H:%M\n"
"\n"
"# Set the format for the time string in the movie start time text field\n"
"# of the movie pop-up window.  This is set separately from the general\n"
"# time string because you generally don't want any extra text and want\n"
"# to display things in an order that allows for easier entry.\n"
"# Default is: %H:%M %m/%d/%Y\n"
"cidd.moviestart_time_format: %H:%M %m/%d/%Y\n"
"\n"
"# Set the format for the time strings in the frame range text fields.\n"
"# Default is: %H:%M\n"
"cidd.frame_range_time_format: %H:%M:%S\n"
"\n"
"# Plot a Legend for each Grid overlay; 0=Off, 1=On\n"
"cidd.layer_legends_on: 1  \n"
"\n"
"# Plot a Legend for each Contour overlay; 0=Off, 1=On\n"
"cidd.cont_legends_on: 1\n"
"\n"
"# Plot a Legend for each Wind overlay; 0=Off, 1=On\n"
"cidd.wind_legends_on: 1\n"
"\n"
"# Plot a Legend for each Symbolic Product overlay; 0=Off, 1=On\n"
"cidd.symprod_legends_on: 1\n"
"    \n"
"# Switch to turn off all data labels on the display\n"
"cidd.display_labels: 1  \n"
"#\n"
"# Switch to turn on/off Height, Route and Wind Scale reference lines\n"
"cidd.display_ref_lines: 1\n"
"# \n"
"\n"
"# TOP Margin styles:\n"
"# 1. Default. Places a distance scale in the top Margin.\n"
"# 2. Place a Frame number and Time - Used often for HTML output.\n"
"# 3. None: -  Used often to place the Data label\n"
"#\n"
"cidd.top_margin_render_style: 1\n"
"\n"
"# Bottom Margin Styles\n"
"# 1 - Distance Scale\n"
"# 2 - Time Scale\n"
"cidd.bot_margin_render_style: 2\n"
"\n"
"#\n"
"# Explicitly set the Label start coords, and delta Y.\n"
"# If left unset, legends start relative to the top and left margins.\n"
"#\n"
"cidd.horiz_legends_start_x:  30\n"
"cidd.horiz_legends_start_y:  30\n"
"cidd.horiz_legends_delta_y:  30\n"
"\n"
"#\n"
"# WINDOW SIZE PARAMS\n"
"#\n"
"#  The starting window size\n"
"cidd.horiz_default_height:    800\n"
"#\n"
"# Note that the control panel with the menu bar will hide itself if the window is\n"
"# sized smaller than the cidd.horiz_min_height. This is useful if you want no\n"
"# visible User Interface.\n"
"cidd.horiz_min_height:        400\n"
"\n"
"#\n"
"# Currently not used\n"
"cidd.horiz_min_width:         400\n"
"#\n"
"cidd.horiz_default_x_pos:     0\n"
"cidd.horiz_default_y_pos:     0\n"
"\n"
"cidd.horiz_top_margin:        20\n"
"cidd.horiz_bot_margin:        20\n"
"cidd.horiz_left_margin:       20\n"
"cidd.horiz_right_margin:      60\n"
"\n"
"cidd.vert_min_height:        120\n"
"cidd.vert_min_width:         120\n"
"cidd.vert_default_height:    440\n"
"cidd.vert_default_width:     600\n"
"\n"
"cidd.vert_top_margin:        20\n"
"cidd.vert_bot_margin:        20\n"
"cidd.vert_left_margin:       20\n"
"cidd.vert_right_margin:      30\n"
"\n"
"\n"
"# Set range_ring_spacing to a negative value to dynamically determine spacing.\n"
"cidd.range_ring_spacing:        50.0\n"
"cidd.max_ring_range:            1000.0\n"
"\n"
"#  Render Range rings at the origin of the data, instead of the origin of the display.\n"
"cidd.range_ring_follows_data: 0\n"
"\n"
"#  Render Range rings only for radar type data.\n"
"cidd.range_ring_for_radar_only: 1\n"
"\n"
"#  Shift the Domain if the data shifts.\n"
"cidd.domain_follows_data: 0\n"
"\n"
"# x_space, y_space in pixels determine allowable space for range ring labels\n"
"cidd.range_ring_x_space:    40\n"
"cidd.range_ring_y_space:    13\n"
"cidd.azimuth_interval:       30.0\n"
"cidd.azimuth_radius:         200.0\n"
"\n"
"# Toggles to turn on/off  Extras features on startup\n"
"cidd.range_rings:             0\n"
"cidd.range_ring_labels:       1\n"
"cidd.azimuth_lines:           0\n"
"\n"
"# Starting state of the All Winds ON/OFF feature\n"
"cidd.all_winds_on: 1\n"
"\n"
"# Wind vector parameters \n"
"cidd.barb_shaft_len:         30\n"
"cidd.wind_head_size:         5\n"
"cidd.ideal_x_vectors:        20\n"
"cidd.ideal_y_vectors:        20\n"
"cidd.wind_head_angle:        30.0\n"
"#\n"
"\n"
"# Wind Vector interval scale factor.\n"
"# Vectors will be drawn to show\n"
"# cidd.wind_scaler * cidd.wind_time_scale_interval minutes of motion\n"
"cidd.wind_scaler: 3\n"
"\n"
"#  Minutes between steps on the wind scaling slider. Wind vector \n"
"#  length = cidd.wind_scaler * wind_time_scale_interval *  wind velocity\n"
"cidd.wind_time_scale_interval: 10.0\n"
"\n"
"# Wind Rendering Style  Options:\n"
"# \"arrow\" (centered at data point),\n"
"# \"vector\",(Vertex at data point )\n"
"# \"barb\" (N Hemisp),\n"
"# \"labeledbarb\", (labeled to nearest 10 degrees at the center - N. Hemisp)\n"
"# \"tuft\", (like a piece of yarn - the least obtrusive - like a headless vector)\n"
"# \"tickvector\" (Cross ticks at wind_time_scale_interval  minutes)\n"
"# \"metbarb\" (Calcs latitude - works for both hemispheres and\n"
"# adds a label of the 10's digit off the end of the barb, ala winds aloft charts)\n"
"# \"barb_sh\" (S Hemisphere),\n"
"# \"labeledbarb\", (labeled to nearest 10 degrees at the center - N. Hemisp)       \n"
"# NOTE: When using arrow,vector,tuft,tickvector,  the data must be in\n"
"# m/sec for the scaling to work correctly. For the others (Barbs),\n"
"# the units are arbitrary, but the flag units on the barbs will reflect\n"
"# the data's native units.\n"
"cidd.wind_marker_type: arrow\n"
"cidd.wind_w_scale_factor:    10.0\n"
"#\n"
"# Set this value to convert from the your reference speed units \n"
"# to m/sec.  ie wind_units_scale_factor =  m/sec / chosen units\n"
"# default = 1.0\n"
"cidd.wind_units_scale_factor:     1.0\n"
"\n"
"# Sets the length of the wind vector reference speed legend.\n"
"cidd.wind_reference_speed: 30.0\n"
"\n"
"# Select the label to be printed next to the reference bar\n"
"# Default = m/sec\n"
"cidd.wind_units_label:  km/hr\n"
"\n"
"# Uncomment the following lines to turn on default contour fields\n"
"# Uses the contour levels and the Field Label string in data.info\n"
"# The parameters are Exact_field_label and color and optional \"off\"\n"
"# Keyword. If \"off\" param is used, the field will be defined, but will\n"
"# not be activated on startup.\n"
"#cidd.contour1_field: FzLevel red off\n"
"#cidd.contour2_field: SURF_T white\n"
"#cidd.contour3_field: SURF_T white\n"
"#cidd.contour4_field: SURF_T white\n"
"#cidd.contour5_field: SURF_T white\n"
"# \n"
"# Set to 1 to have numeric labels on line contours, 0 = off\n"
"cidd.label_contours:   0           \n"
"\n"
"#  Default line width of contours\n"
"cidd.contour_line_width: 1\n"
"\n"
"# Apply smoothing to data grids before contouring\n"
"# 0 = Off, 1 = single pass, 2 = double pass\n"
"cidd.smooth_contours: 0 \n"
"\n"
"# Add 1 part in 250 Noise to help smooth contours\n"
"cidd.add_noise: 0 \n"
"\n"
"# Use Alternate (Mdvx) Contouring Routines -\n"
"# Slower - Nicer labeling - Less smooth - \n"
"# Warning - Does not work correctly when data and display origins are different\n"
"# (Works fine in lat/lon projections)\n"
"cidd.use_alt_contours: 0 \n"
"\n"
"#\n"
"# Contours at this value will have a wider line\n"
"# \n"
"# \n"
"cidd.special_contour_value: 0.25\n"
"\n"
"# Sometimes, for CONTOURING it is useful to make\n"
"# the assumption that the bad and/or missing values\n"
"# should be considered at the minimum of the dynamic range of the\n"
"# data. IE. If you want bad an/or missing contoured\n"
"# set these to 1, otherwise, set them to 0 (default)\n"
"#\n"
"cidd.map_bad_to_min_value: 0\n"
"cidd.map_missing_to_min_value: 0\n"
"#\n"
"# Uncomment the following lines to set up fields on startup that will\n"
"# appear as overlaid fields. Layers are on by default unless the\n"
"optional \"off\" string appears last. \n"
"cidd.layer5_field:  KCYS-DBZ \n"
"cidd.layer4_field:  KPUX-DBZ\n"
"cidd.layer3_field:  KGJX-DBZ\n"
"cidd.layer2_field:  KGLD-DBZ off\n"
"cidd.layer1_field:  KLNX-DBZ off\n"
"\n"
"# Rendering order for layers:\n"
"#  0: render main field first then layers\n"
"#  1: render main field on top of layers.\n"
"cidd.draw_main_on_top: 0\n"
"\n"
"\n"
"# Option to mark latest click location:\n"
"cidd.mark_latest_click_location: 0\n"
"cidd.latest_click_mark_color: red\n"
"cidd.latest_click_mark_size: 11\n"
"\n"
"# Option to mark latest click location from client app:\n"
"cidd.mark_latest_client_location: 0\n"
"cidd.latest_client_mark_color: yellow\n"
"cidd.latest_client_mark_size: 11\n"
"\n"
"# Place Cidd fonts in ascending order of size. Cidd will choose the\n"
"# highest font number that will fit in a given screen space.\n"
"# Pick a nice spectrum of font sizes, with all of them readable.\n"
"# CIDD currently accepts up to 16 different fonts\n"
"cidd.num_fonts: 8\n"
"#\n"
"cidd.font1: 6x9\n"
"cidd.font2: -*-courier-medium-r-normal-*-10-*-*-*-*-*-*-*\n"
"cidd.font3: -*-courier-medium-r-normal-*-12-*-*-*-*-*-*-*\n"
"cidd.font4: -*-courier-bold-r-normal-*-12-*-*-*-*-*-*-*\n"
"cidd.font5: -*-courier-bold-r-normal-*-14-*-*-*-*-*-*-*\n"
"cidd.font6: -*-courier-bold-r-normal-*-15-*-*-*-*-*-*-*\n"
"cidd.font7: -*-courier-bold-r-normal-*-16-*-*-*-*-*-*-*\n"
"cidd.font8: -*-courier-bold-r-normal-*-18-*-*-*-*-*-*-*\n"
"cidd.font9: -*-courier-bold-r-normal-*-24-*-*-*-*-*-*-*\n"
"cidd.font10: -*-courier-bold-r-normal-*-30-*-*-*-*-*-*-*\n"
"\n"
"# font_display_mode = 1 - Clears background behind label text., 0 - No\n"
"cidd.font_display_mode: 0 \n"
"# \n"
"\n"
"#Toggle for displaying an analog clock in the upper right hand corner of the image\n"
"cidd.show_clock:       0\n"
"\n"
"# Set to 0 to draw the analog clock using UTC, 1 = local time.\n"
"cidd.draw_clock_local: 0\n"
"\n"
"# Time stamps are displayed as UTC When = 0., Local time when = 1\n"
"# All Input time widgets expect UTC when set to 0, local times when set to 1.\n"
"cidd.use_local_timestamps: 0\n"
"\n"
"#####################################################################################\n"
"# GUI RELATED STUFF\n"
"#\n"
"# Set this parameter to force the field menu pop-up to this many columns\n"
"# If set <= 0, then cidd sets this dynamically, allowing at most 30 in each\n"
"# column.\n"
"cidd.num_field_menu_cols: 1\n"
"\n"
"# This parameter sets WSDDM specific behavior On -\n"
"# - Go to end of loop when movie stops.\n"
"# - No on-image no-data message when winds are missing\n"
"cidd.wsddm_mode:            0\n"
"\n"
"# This parameter allows the user to define a route/rhi with one mouse\n"
"# click and drag. When set to 1, disallows multi way point cross sections\n"
"# - RHI are defined by clicking right mouse near the radar origin and\n"
"# dragging away from the radar along the desired  azimuth and releasing.\n"
"cidd.one_click_rhi: 0\n"
"\n"
"# CIDD uses the number pad keys 7,9,4,6,1,3 to rotate the RHI \n"
"# by +/- these amounts\n"
"# 7-9 is coarse 4-6 is medium and 1-3 is fine.\n"
"cidd.rotate_coarse_adjust: 6\n"
"cidd.rotate_medium_adjust: 2\n"
"cidd.rotate_fine_adjust:  0.5\n"
"\n"
"# Disable Pick Feature\n"
"cidd.disable_pick_mode: 0\n"
"\n"
"# Underscores in Field names and legends are replaced by spaces if set \n"
"cidd.replace_underscores: 1\n"
"\n"
"# Close CIDD's pop ups When the main window is closed. Turn this off (0) if you\n"
"# don't want CIDD to close its pop ups when switching between virtual desktops\n"
"cidd.close_popups: 0\n"
"\n"
"# CIDD can Render Overlay fields using filled polygons, and clip the data\n"
"# between some minimum and maximum.  This is useful, for example, if one wants\n"
"# to show Radar data over +40dB overlaid on Satellite imagery.\n"
"# Default behavior is to render the overlay fields using the same render method\n"
"# selected in the fields <GRID> line.\n"
"cidd.clip_overlay_fields: 0\n"
"\n"
"# \n"
"# MENU_BAR Configuration\n"
"# The Menu bar is configurable. One can configure which buttons/functions are\n"
"available to the user. In many operational setting many of the functions should\n"
"not be available.  For research/ post analysis most of them should be enabled. \n"
"#####################################################################################\n"
"# Defines for the Menu Bar at the top of the main window. Functions are:\n"
"#\n"
"#    --- One Shot Functions ---\n"
"# RELOAD - (Force all data to be reloaded)\n"
"# RESET - (Set display to starting zoom, field, products on/off state, etc)\n"
"# SET_TO_NOW - (Sets the display to current time - canceling forecast mode)\n"
"# SET_DRAW_MODE - (Enable the Human entered feature drawing mode)\n"
"# SET_PICK_MODE - (Enable Symprod Picking Mode) \n"
"# SET_ROUTE_MODE - (Enable the Flight Route drawing mode)\n"
"# PRINT_BUTTON - (Save and Print the plan view image) \n"
"# HELP_BUTTON - (Send Netscape to a useful help Page)\n"
"# EXIT_BUTTON - Kills the Display\n"
"# CLONE_CIDD - Starts another instance of the same display \n"
"# SNAP_IMAGE - Starts A Snapshot viewer - Displaying the current image\n"
"#\n"
"#    --- Toggle things on and off ----\n"
"# LOOP_ONOFF - (Turn the movie loop on/off)\n"
"# WINDS_ONOFF - (Turn all winds on/off)\n"
"# SYMPRODS_ONOFF - (Turn all Symbolic Products on/off)\n"
"# REPORT_MODE_ONOFF - (Turn on/off Continuous Report Mode )\n"
"# LANDUSE_ONOFF  - (Turn On/off the Land Use image)\n"
"#\n"
"#    --- Display Panels ---\n"
"# SHOW_DPD_PANEL - (Show/Hide Page Definition Panel which configures individual pages)\n"
"# SHOW_XSECT_PANEL - (Show/Hide the Cross Section Display View Panel)\n"
"# SHOW_GRID_PANEL - (Show/Hide the Data Source Configuration Panel)\n"
"# SHOW_STATUS_PANEL - (Show/Hide a Status message window)\n"
"# SHOW_TIME_PANEL - (Show/Hide the Movie loop control Panel) \n"
"# CLOSE_POPUPS  - (Close all Popup panels)\n"
"#\n"
"#    --- Display Additional Menus ---\n"
"# SHOW_DPD_MENU - (Show/Hide the field/page description menu)\n"
"# SHOW_VIEW_MENU - (Show/Hide the zoom level menu)\n"
"# SHOW_MAP_MENU - (Show/Hide the map overlay menu)\n"
"# SHOW_PRODUCT_MENU - (Show/Hide the symbolic product menu)\n"
"# SHOW_FORECAST_MENU -(Show/Hide the forecast mode menu)\n"
"# SHOW_PAST_MENU    - (Show/Hide the past mode menu)\n"
"# SHOW_BOOKMARK_MEN - (Show/Hide the helpful bookmark menu)\n"
"# SHOW_GENTIME_MENU - (Show/Hide the Model Generation Time menu)\n"
"# SHOW_CMD_MENU  -    (Show/Hide the Command menu)\n"
"# ZOOM_BACK - (Go back to previous zoom)\n"
"# \n"
"#\n"
"#####################################################################################\n"
"cidd.num_menu_bar_cells: 18\n"
"#\n"
"cidd.menu_bar_label1: Fields\n"
"cidd.menu_bar_funct1: SHOW_DPD_MENU\n"
"# \n"
"cidd.menu_bar_label2: Zoom\n"
"cidd.menu_bar_funct2: SHOW_VIEW_MENU\n"
"#\n"
"cidd.menu_bar_label3: BACK\n"
"cidd.menu_bar_funct3: ZOOM_BACK\n"
"#\n"
"cidd.menu_bar_label4: Maps\n"
"cidd.menu_bar_funct4: SHOW_MAP_MENU\n"
"#\n"
"cidd.menu_bar_label5: Movie\n"
"cidd.menu_bar_funct5: SHOW_TIME_PANEL\n"
"#\n"
"cidd.menu_bar_label6: Loop\n"
"cidd.menu_bar_funct6: LOOP_ONOFF\n"
"#\n"
"cidd.menu_bar_label7: X-Sect\n"
"cidd.menu_bar_funct7: SHOW_XSECT_PANEL\n"
"#\n"
"cidd.menu_bar_label8: Products\n"
"cidd.menu_bar_funct8: SHOW_PRODUCT_MENU\n"
"#\n"
"cidd.menu_bar_label9: All products\n"
"cidd.menu_bar_funct9: SYMPRODS_ONOFF\n"
"#\n"
"cidd.menu_bar_label10: Winds\n"
"cidd.menu_bar_funct10: WINDS_ONOFF\n"
"#\n"
"cidd.menu_bar_label11: Overlays\n"
"cidd.menu_bar_funct11: SHOW_DPD_PANEL\n"
"#\n"
"cidd.menu_bar_label12: Config\n"
"cidd.menu_bar_funct12: SHOW_GRID_PANEL\n"
"#\n"
"cidd.menu_bar_label13: Status\n"
"cidd.menu_bar_funct13: SHOW_STATUS_PANEL\n"
"#\n"
"cidd.menu_bar_label14: Now\n"
"cidd.menu_bar_funct14: SET_TO_NOW\n"
"#\n"
"cidd.menu_bar_label15: Reset\n"
"cidd.menu_bar_funct15: RESET\n"
"#\n"
"cidd.menu_bar_label16: Reload\n"
"cidd.menu_bar_funct16: RELOAD\n"
"#\n"
"cidd.menu_bar_label17: DataValue\n"
"cidd.menu_bar_funct17: REPORT_MODE_ONOFF\n"
"#\n"
"cidd.menu_bar_label18: Exit\n"
"cidd.menu_bar_funct18: EXIT_BUTTON\n"
"#\n"
"#cidd.menu_bar_label19: Print\n"
"#cidd.menu_bar_funct19: PRINT_BUTTON\n"
"#\n"
"#cidd.menu_bar_label20: Help\n"
"#cidd.menu_bar_funct20: HELP_BUTTON\n"
"#\n"
"#cidd.menu_bar_label21: Model-Run\n"
"#cidd.menu_bar_funct21: SHOW_GENTIME_MENU\n"
"#\n"
"#cidd.menu_bar_label22: Fcast\n"
"#cidd.menu_bar_funct22: SHOW_FORECAST_MENU\n"
"#\n"
"#cidd.menu_bar_label23: Past\n"
"#cidd.menu_bar_funct23: SHOW_PAST_MENU\n"
"# \n"
"#cidd.menu_bar_label24: Close Popups\n"
"#cidd.menu_bar_funct24: CLOSE_POPUPS\n"
"#\n"
"#cidd.menu_bar_label25: URL\n"
"#cidd.menu_bar_funct25: SHOW_BOOKMARK_MENU\n"
"#\n"
"#cidd.menu_bar_label26: Base Map\n"
"#cidd.menu_bar_funct26: LANDUSE_ONOFF\n"
"#\n"
"#cidd.menu_bar_label27: CLONE\n"
"#cidd.menu_bar_funct27: CLONE_CIDD\n"
"#\n"
"#cidd.menu_bar_label28: Commands\n"
"#cidd.menu_bar_funct28: SHOW_CMD_MENU\n"
"#\n"
"#cidd.menu_bar_label29: Snapshot\n"
"#cidd.menu_bar_funct29: SNAP_IMAGE\n"
"#\n"
"#cidd.menu_bar_label30: Select Route \n"
"#cidd.menu_bar_funct30: SET_ROUTE_MODE\n"
"#NOTE - SET_ROUTE_MODE turns off cross sections in GUI\n"
"#\n"
"#cidd.menu_bar_label31: Draw Mode\n"
"#cidd.menu_bar_funct31: SET_DRAW_MODE\n"
"#\n"
"# Valid in CIDD v 2.136 or greater\n"
"#cidd.menu_bar_label32: Pick Mode\n"
"#cidd.menu_bar_funct32: SET_PICK_MODE\n"
"\n"
"##########################################\n"
"\n"
"cidd.horiz_frame_label:  **  Colorado/ Front Range NIDS DATA - Master Parameter file **\n"
"\n"
"# Set the message to display when no data is available\n"
"cidd.no_data_message:     NO DATA FOUND (in this area at the selected time)\n"
"\n"
"# System NO-Data  Status/Info File\n"
"# Cidd will check for updates to this file and will Replace the no_data_message\n"
"# With the text from this file\n"
"cidd.status_info_file:\n"
"\n"
"# HELP TEXT LINKS                       \n"
"# These take the form:\n"
"# cidd.widget_name_help:       file_name:file_index_key_string\n"
"# The HELPPATH environment variable must be set or the help file\n"
"# must be located in /usr/lib/help.\n"
"# Note the file name gets expanded to file_name.info\n"
"#\n"
"cidd.canvas_help:              cidd_help:canvas\n"
"cidd.frame_message_help:       cidd_help:frame_message\n"
"\n"
"cidd.help_command:   /opt/google/chrome/chrome http://www.rap.ucar.edu/CIDD'\n"
"\n"
"#\n"
"# This command is run whenever a BOOKMARK_MENU button is pressed.\n"
"# The characters; %U are replaced with the url text from the\n"
"# parameters; cidd.bookmarkN below.\n"
"cidd.bookmark_command:  /opt/google/chrome/chrome %U\n"
"\n"
"# Number of bookmarks in the Menu\n"
"cidd.num_bookmarks: 4\n"
"\n"
"# BOOKMARKS FOR Quick Reference\n"
"# Create N Bookmark and Label parameters\n"
"# cidd.bookmarkN: - The exact URL text for use in the cidd.bookmark_command.\n"
"# cidd.bookmark_labelN: The Label that appears in the menu\n"
"#\n"
"cidd.bookmark1: http://mars/aoaws/doc/roc_mds.html\n"
"cidd.bookmark_label1: ROC\n"
"cidd.bookmark2: http://www.rap.ucar.edu/weather/\n"
"cidd.bookmark_label2: RAP Weather\n"
"cidd.bookmark3: http://adds.awc-kc.noaa.gov/\n"
"cidd.bookmark_label3: ADDS\n"
"cidd.bookmark4: http://cessna/\n"
"cidd.bookmark_label4: ADDS-Cessna\n"
"\n"
"\n"
"# Resources for compatibility with TITAN-TIME HISTORY Program\n"
"\n"
"cidd.track_server_instance:         Operations\n"
"cidd.track_past_plot_period:        0\n"
"cidd.track_future_plot_period:      0\n"
"cidd.track_n_forecast_steps:        5\n"
"cidd.track_forecast_interval:       6\n"
"cidd.track_data_time_margin:        750\n"
"cidd.track_past_color:              yellow\n"
"cidd.track_current_color:           cyan\n"
"cidd.track_future_color:            blue\n"
"cidd.track_forecast_color:          red\n"
"\n"
"#  KEYS for SHARED MEMORY SEGMENTS\n"
"\n"
"# Key for coordinate shared memory\n"
"cidd.coord_key:               61500\n"
"\n"
"# Key for TITAN control shared memory\n"
"cidd.titan_key               61501\n"
"\n"
"\n"
"#  Starting Size size of fonts for symbolic products - From above list\n"
"cidd.product_font_size: 4\n"
"\n"
"#Detail thresholds and font adjustment parameters. First implicit threshold is 0.0\n"
"# If the current distance across a domain is between the thresholds, then an adjustment is made to the\n"
"# default/selected font size. This is used to change the size of the fonts\n"
"# automatically as the users zooms in and out. Threshold values are in km across the\n"
"# viewing domain\n"
"cidd.product_detail_threshold1: 50.0\n"
"cidd.product_detail_adjustment1: +3\n"
"#\n"
"cidd.product_detail_threshold2: 200.0\n"
"cidd.product_detail_adjustment2: +2\n"
"#\n"
"cidd.product_detail_threshold3: 400.0\n"
"cidd.product_detail_adjustment3: +1\n"
"\n"
"# Product Scaling Constant. - Set this constant to determine\n"
"# at what zoom icons and will have a scale factor of 1.0\n"
"# Default = 300. Function = log10(Constant /km_across_screen) + 1.0;\n"
"# Set to less than 0 to disable icon scaling\n"
"cidd.scale_constant: 300.0 \n"
"\n"
"</MAIN_PARAMS>\n"
"\n";

/////////////////////////////////////////////////////////////////////////////
// GET_DEFAULT_PARAMS : Get a string representing the default parameters
//                      for this TDRP parameter object
// 

template <class T>
string get_default_tdrp_params(const string &section_name, T *params)
{
  // Load the temporary parameters since we don't seem to have them
  // loaded yet

  params->loadDefaults(false);
  
  // Open a temporary file to hold the parameters.  Write the parameters
  // to that file and close it.

  const string tmp_filename = ".params";
  
  FILE *tmp_file;

  if ((tmp_file = fopen(tmp_filename.c_str(), "w")) == 0)
  {
    fprintf(stderr,
	    "Error opening temporary file for writing TDRP parameters\n");
    exit(-1);
  }
  
  params->print(tmp_file);
  fclose(tmp_file);
  
  // Now read the file back into a string

  struct stat tmp_file_stat;
  
  if (stat(tmp_filename.c_str(), &tmp_file_stat) != 0)
  {
    fprintf(stderr,
	    "Error stating temporary file for writing TDRP parameters\n");
    exit(-1);
  }
  
  char *tmp_buffer = new char[tmp_file_stat.st_size + 1];

  if ((tmp_file = fopen(tmp_filename.c_str(), "r")) == 0)
  {
    fprintf(stderr,
	    "Error opening temporary file for reading TDRP parameters\n");
    exit(-1);
  }
  
  if (fread(tmp_buffer, sizeof(char), tmp_file_stat.st_size, tmp_file) !=
      (size_t)tmp_file_stat.st_size)
  {
    delete [] tmp_buffer;
    fprintf(stderr,
	    "Error reading TDRP parameters from temporary file\n");
    exit(-1);
  }
  
  fclose(tmp_file);
  unlink(tmp_filename.c_str());
  
  // Set the return string

  tmp_buffer[tmp_file_stat.st_size] = '\0';

  string return_string = "<" + section_name + ">\n";
  return_string += tmp_buffer;
  return_string += "</" + section_name + ">\n\n";
  
  delete [] tmp_buffer;
  
  return return_string;
}


