#! /bin/bash

#--------------------------------------------------------------------
#
# prepare lrose release
#
# Mike Dixon, RAP, NCAR, Boulder, CO, USA
# July 2010
#
#--------------------------------------------------------------------

# set the path

export PATH=.:/bin:./make_bin:/usr/bin:/sbin:/usr/sbin:/usr/bin/X11:/usr/local/bin:/usr/local/sbin:$HOME/bin

#--------------------------------------------------------------------
# usage function
#

function usage() {
    echo
    echo "Usage: prepare_src_release [options below]"
    echo "  -h:  produce this usage list"
    echo "  -d:  turn debugging on"
    echo "  -s:  statically-linked release"
    echo "       default is dynamic linking"
    echo "  -v:  turn verbose on"
    echo
}

#--------------------------------------------------------------------

# defaults

package=lrose
debug=true
verbose=false
static=false

# Parse command line options.
while getopts hdsv OPT; do
    case "$OPT" in
        h)
            usage
            exit 0
            ;;
        d)
            debug=true
            ;;
        v)
            verbose=true
            ;;
        s)
            static=true
            ;;
        \?)
            # getopts issues an error message
            echo "Problems with command line usage"
            usage
            exit 1
            ;;
    esac
done

if [ "$debug" == "true" ]
then
  echo "Running prepare_src_release"
  echo "  package: $package"
  echo "  debug: $debug"
  echo "  verbose: $verbose"
  echo "  static: $static"
fi

# Remove the switches we parsed above.
shift `expr $OPTIND - 1`

#######################################################
# get run time

year=`date -u +'%Y'`
month=`date -u +'%m'`
day=`date -u +'%d'`
hour=`date -u +'%H'`
min=`date -u +'%M'`
sec=`date -u +'%S'`

#--------------------------------------------------------------------

echo
echo "*********************************************************************"
echo
echo "  Preparing ${package} release"
echo
echo "  NCAR, Boulder, CO, USA"
echo
echo "  $year/$month/$day $hour:$min:$sec"
echo
echo "*********************************************************************"
echo

# remove any previous tar files

/bin/rm -f *.tgz

# set the path

export PATH=${PATH}:/bin:/usr/bin:/sbin:/usr/sbin:/usr/bin/X11:/usr/local/bin:/usr/local/sbin:/usr/lib64/qt4/bin:/usr/lib/qt4/bin:.
startingDir=`pwd`

# create configure.ac, makefile.am files
# run AutoConf

/bin/cp ./build/configure.base .
/bin/cp ./build/configure.base.shared .
/bin/cp ./build/Makefile.top ./Makefile

# create project-specific makefiles

./make_bin/install_distro_makefiles.py --distro ${package}

exit

if [ "$static" == "true" ]
then

    if [ "$verbose" == "true" ]
    then
        ./make_bin/createConfigure.am.py --dir . --pkg ${package} --verbose || exit 1
    else
        ./make_bin/createConfigure.am.py --dir . --pkg ${package} --debug || exit 1
    fi

else

    if [ "$verbose" == "true" ]
    then
        ./make_bin/createConfigure.am.py --dir . --baseName configure.base.shared \
            --verbose --shared --pkg ${package} || exit 1
    else
        ./make_bin/createConfigure.am.py --dir . --baseName configure.base.shared \
            --debug --shared --pkg ${package} || exit 1
    fi


fi

# copy docs to this level

cp ./build/docs/*.TXT .
cp -r ../docs/${package}_release_notes.txt .

# copy build scripts to this level

/bin/cp ../../lrose-netcdf/build_and_install_netcdf .
/bin/cp ./build/build_${package} .
/bin/cp ./release/prepare_bin_release .

# copy in the package tar file dependencies

mkdir -p netcdf_tar_files
/bin/cp -rf ../../lrose-netcdf/tar_files/* netcdf_tar_files

# compute release name and dir name

today=${year}${month}${day}
distName=${package}-${today}.src
srcTarName=${distName}.tgz
echo Preparing source release file $srcTarName

# make dist dir

/bin/rm -rf ${package}-????????* || exit 1
mkdir -p $distName || exit 1

# move everything there

mv * $distName

# make the tar file

tar cvfz $srcTarName --dereference $distName

# move everything back

mv $distName/* .
/bin/rm -rf $distName

#--------------------------------------------------------------------
# done

echo
echo "  **************************************************"
echo "  *** Done preparing release ***"
echo "  *** source tar file name: $srcTarName ***"
echo "  **************************************************"
echo

exit 0
