
//////////////////////////////////////////////////////////////
//
// Header file for RxDevStatusFormUI
//
//    This file is generated by RapidApp 1.2
//
//    This class implements the user interface portion of a class
//    Normally it is not used directly.
//    Instead the subclass, RxDevStatusForm is instantiated
//
//    To extend or alter the behavior of this class, you should
//    modify the RxDevStatusForm files
//
//    Restrict changes to those sections between
//    the "//--- Start/End editable code block" markers
//
//    This will allow RapidApp to integrate changes more easily
//
//    This class is a ViewKit user interface "component".
//    For more information on how components are used, see the
//    "ViewKit Programmers' Manual", and the RapidApp
//    User's Guide.
//
//////////////////////////////////////////////////////////////
#ifndef RXDEVSTATUSFORMUI_H
#define RXDEVSTATUSFORMUI_H
#include <Vk/VkComponent.h>


//---- Start editable code block: headers and declarations


//---- End editable code block: headers and declarations


class RxDevStatusFormUI : public VkComponent
{ 

  public:

    RxDevStatusFormUI ( const char *, Widget );
    RxDevStatusFormUI ( const char * );
    ~RxDevStatusFormUI();
    void create ( Widget );
    const char *  className();

    //---- Start editable code block: RxDevStatusForm public


    //---- End editable code block: RxDevStatusForm public


  protected:


    // Widgets created by this class

    Widget  _button46;
    Widget  _connModelabel;
    Widget  _connStatusLabel;
    Widget  _connToLabel;
    Widget  _connTypeLabel;
    Widget  _currReqLabel;
    Widget  _devEnabledToggle;
    Widget  _deviceDescriptionLabel;
    Widget  _failTimeLabel;
    Widget  _filterListScrolledText;
    Widget  _finScansToggle;
    Widget  _label31;
    Widget  _label33;
    Widget  _label34;
    Widget  _label35;
    Widget  _label38;
    Widget  _label40;
    Widget  _label41;
    Widget  _label43;
    Widget  _label44;
    Widget  _rxDevStatusForm;
    Widget  _scrolledWindow8;


    // These virtual functions are called from the private callbacks (below)
    // Intended to be overriden in derived classes to define actions

    virtual void closeWin ( Widget, XtPointer );
    virtual void deviceEnabledChanged ( Widget, XtPointer );
    virtual void getFinishedScansChanged ( Widget, XtPointer );

    //---- Start editable code block: RxDevStatusForm protected


    //---- End editable code block: RxDevStatusForm protected


  private: 

    // Array of default resources

    static String      _defaultRxDevStatusFormUIResources[];


    // Callbacks to interface with Motif

    static void closeWinCallback ( Widget, XtPointer, XtPointer );
    static void deviceEnabledChangedCallback ( Widget, XtPointer, XtPointer );
    static void getFinishedScansChangedCallback ( Widget, XtPointer, XtPointer );

    //---- Start editable code block: RxDevStatusForm private


    //---- End editable code block: RxDevStatusForm private
};
//---- Start editable code block: End of generated code


//---- End editable code block: End of generated code

#endif

