# *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* 
# ** Copyright UCAR (c) 1992 - 2001 
# ** University Corporation for Atmospheric Research(UCAR) 
# ** National Center for Atmospheric Research(NCAR) 
# ** Research Applications Program(RAP) 
# ** P.O.Box 3000, Boulder, Colorado, 80307-3000, USA 
# ** 2001/11/19 23:15:6 
# *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* 
###########################################################################
#
# Makefile for string module
#
# Mike Dixon, RAP, NCAR, Boulder, Co, USA, 80307
#
# Nov 1994
#
###########################################################################

include $(RAP_MAKE_INC_DIR)/rap_make_macros

LOC_INCLUDES = -I../include
LOC_CFLAGS = -D JAWS_FE_TECH_TRANSFER

TARGET_FILE = ../libtoolsa.a

#
# file lists
#

HDRS = $(RAP_INC_DIR)/toolsa/str.h

SRCS = \
	str_ncopy.c


#	str_binary.c \
#	str_blnk.c \
#	str_bpad.c \
#	str_concat.c \
#	str_copy.c \
#	str_delete.c \
#	str_dup.c \
#	str_equal.c \
#	str_free.c \
#	str_good.c \
#	str_insert.c \
#	str_mcopy.c \
#	str_parse.c \
#	str_parse_delim.c \
#	str_parse_double.c \
#	str_pastoc.c \
#	str_pos.c \
#	str_remove.c \
#	str_replace.c \
#	str_swap.c \
#	str_tokn.c

CPPC_SRCS = \

#	TaStr.cc

#
# general targets
#

include $(RAP_MAKE_INC_DIR)/rap_make_lib_module_targets

#
# local targets
#

depend: depend_generic

# DO NOT DELETE THIS LINE -- make depend depends on it.
