#
# Recursive make - makes the subdirectory code
#
#	rucIngest  - Won't build due to faulty grib lib

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	LdmMetars2File \
	PrintNids \
	NidsRadial2Mdv \
	WsiMetarIngest \
	Metar2Spdb \
	Nids2Mdv \
	NidsRadial2Mdv \
	NidsVad2Spdb \
	NidsRaster2Mdv \
	PrintNids \
	WsiMetarIngest \
	WsiNidsIngest \

include $(RAP_MAKE_INC_DIR)/rap_make_recursive_dir_targets
