// *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* 
// ** Copyright UCAR (c) 1990 - 2016                                         
// ** University Corporation for Atmospheric Research (UCAR)                 
// ** National Center for Atmospheric Research (NCAR)                        
// ** Boulder, Colorado, USA                                                 
// ** BSD licence applies - redistribution and use in source and binary      
// ** forms, with or without modification, are permitted provided that       
// ** the following conditions are met:                                      
// ** 1) If the software is modified to produce derivative works,            
// ** such modified software should be clearly marked, so as not             
// ** to confuse it with the version available from UCAR.                    
// ** 2) Redistributions of source code must retain the above copyright      
// ** notice, this list of conditions and the following disclaimer.          
// ** 3) Redistributions in binary form must reproduce the above copyright   
// ** notice, this list of conditions and the following disclaimer in the    
// ** documentation and/or other materials provided with the distribution.   
// ** 4) Neither the name of UCAR nor the names of its contributors,         
// ** if any, may be used to endorse or promote products derived from        
// ** this software without specific prior written permission.               
// ** DISCLAIMER: THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS  
// ** OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED      
// ** WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.    
// *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* 

/************************************************************************
 * params.hh
 *
 * Text for print_params
 *
 * RAP, NCAR, Boulder CO
 *
 * June 1990
 *
 * Mike Dixon
 ************************************************************************/

static const char *ParamsText =
  "###########\n"
  "# debugging\n"
  "#\n"
  "\n"
  "TimeHist.x_sync: false\n"
  "TimeHist.debug: false\n"
  "TimeHist.instance: ops\n"
  "\n"
  "#\n"
  "# main windows\n"
  "# Are they active?\n"
  "# Which one should plot on top, which on bottom?\n"
  "# Raise priority of 1 is on top, 4 on bottom\n"
  "#\n"
  "\n"
  "TimeHist.thist_active: true\n"
  "TimeHist.timeht_active: true\n"
  "TimeHist.rdist_active: true\n"
  "TimeHist.union_active: true\n"
  "\n"
  "TimeHist.thist_raise_priority: 1\n"
  "TimeHist.timeht_raise_priority: 3\n"
  "TimeHist.rdist_raise_priority: 4\n"
  "TimeHist.union_raise_priority: 2\n"
  "\n"
  "# Setup up union mode window\n"
  "\n"
  "TimeHist.union_mode: hail #! options are hail, floats\n"
  "\n"
  "#\n"
  "# realtime_only mode makes certain time-related buttons inoperable\n"
  "#\n"
  "\n"
  "TimeHist.realtime_only: false #! options are true, false\n"
  "\n"
  "#\n"
  "# archive_only mode makes most time-related buttons operable\n"
  "# resets to archive time instead of now\n"
  "#\n"
  "\n"
  "TimeHist.archive_only: false #! options are true, yes, false or no\n"
  "\n"
  "#\n"
  "# mouse double-click control\n"
  "#\n"
  "\n"
  "TimeHist.double_click_delay: 0.3\n"
  "\n"
  "#\n"
  "# time loop has base interval, upon which other actions are\n"
  "# based (secs). \n"
  "\n"
  "TimeHist.base_timer_interval: 0.15\n"
  "\n"
  "#\n"
  "# time delay at start to let things get started in order - secs\n"
  "\n"
  "TimeHist.startup_timer_interval: 5\n"
  "\n"
  "#\n"
  "# communication with rview, which starts up this program\n"
  "#\n"
  "\n"
  "TimeHist.track_shmem_key: 46000\n"
  "\n"
  "#\n"
  "# storm track data:\n"
  "#   server mapper for track server\n"
  "#   max message len for track data\n"
  "#   interval (secs) at which data is checked\n"
  "#\n"
  "\n"
  "TimeHist.servmap_host1: local\n"
  "TimeHist.servmap_host2: none\n"
  "TimeHist.max_message_len: 30000\n"
  "TimeHist.track_check_interval: 5.0\n"
  "\n"
  "#\n"
  "# case tracks\n"
  "#\n"
  "\n"
  "TimeHist.use_case_tracks: false\n"
  "TimeHist.case_tracks_file_path: $(TITAN_HOME)/params/case_tracks.9798\n"
  "\n"
  "#\n"
  "# partial tracks\n"
  "#\n"
  "\n"
  "TimeHist.partial_track_past_period: 20.0\n"
  "TimeHist.partial_track_future_period: 60.0\n"
  "\n"
  "#\n"
  "# startup plotting options\n"
  "#\n"
  "\n"
  "TimeHist.plot_thist_vol: true\n"
  "TimeHist.plot_thist_area: true\n"
  "TimeHist.plot_thist_pflux: true\n"
  "TimeHist.plot_thist_mass: true\n"
  "TimeHist.plot_thist_vil: true\n"
  "TimeHist.plot_thist_forecast: false #! options: false, limited, all\n"
  "TimeHist.plot_thist_fit: false\n"
  "\n"
  "TimeHist.timeht_mode: maxz          #! options: maxz, meanz, mass or vort\n"
  "TimeHist.timeht_centroids: limited  #! options: false, limited, all\n"
  "TimeHist.timeht_htmaxz: all         #! options: false, limited, all\n"
  "\n"
  "TimeHist.rdist_mode: vol            #! options: vol, area\n"
  "TimeHist.rdist_flipped: true\n"
  "\n"
  "# individual union fields can true or false\n"
  "\n"
  "TimeHist.plot_union_0: true\n"
  "TimeHist.plot_union_1: true\n"
  "TimeHist.plot_union_2: true\n"
  "TimeHist.plot_union_3: true\n"
  "TimeHist.plot_union_fit: false\n"
  "TimeHist.plot_union_log: false\n"
  "\n"
  "#\n"
  "# output for copies\n"
  "#\n"
  "\n"
  "TimeHist.ps_prologue_file: $(TITAN_HOME)/prologues/postscript\n"
  "TimeHist.output_file: $(TITAN_HOME)/output/TimeHist.ps\n"
  "TimeHist.ps_printer: jet\n"
  "TimeHist.print_command: lpr -h -P\n"
  "\n"
  "#\n"
  "# color scales\n"
  "#\n"
  "\n"
  "TimeHist.colorscale_dir: $(TITAN_HOME)/color_scales\n"
  "\n"
  "TimeHist.x_dbz_color_scale: dbz_color\n"
  "TimeHist.x_vorticity_color_scale: vorticity_color\n"
  "TimeHist.x_percent_color_scale: percent_color\n"
  "\n"
  "TimeHist.ps_dbz_color_scale: dbz_gray\n"
  "TimeHist.ps_vorticity_color_scale: vorticity_gray\n"
  "TimeHist.ps_percent_color_scale: percent_gray\n"
  "\n"
  "#\n"
  "# X window geometry\n"
  "#\n"
  "\n"
  "TimeHist.x_min_width: 300\n"
  "TimeHist.x_min_height: 250\n"
  "TimeHist.x_tscale_min_height: 50\n"
  "TimeHist.x_max_button_width: 80\n"
  "\n"
  "TimeHist.x_tscale_x: 0\n"
  "TimeHist.x_tscale_y: 895\n"
  "TimeHist.x_tscale_width: 900\n"
  "TimeHist.x_tscale_height: 95\n"
  "\n"
  "TimeHist.x_thist_x: 910\n"
  "TimeHist.x_thist_y: 95\n"
  "TimeHist.x_thist_width: 355\n"
  "TimeHist.x_thist_height: 280\n"
  "\n"
  "TimeHist.x_timeht_x: 910\n"
  "TimeHist.x_timeht_y: 400\n"
  "TimeHist.x_timeht_width: 355\n"
  "TimeHist.x_timeht_height: 285\n"
  "TimeHist.x_timeht_scale_width: 80\n"
  "\n"
  "TimeHist.x_rdist_x: 910\n"
  "TimeHist.x_rdist_y: 710\n"
  "TimeHist.x_rdist_width: 355\n"
  "TimeHist.x_rdist_height: 280\n"
  "TimeHist.x_rdist_scale_width: 50\n"
  "\n"
  "TimeHist.x_union_x: 910\n"
  "TimeHist.x_union_y: 710\n"
  "TimeHist.x_union_width: 355\n"
  "TimeHist.x_union_height: 280\n"
  "\n"
  "TimeHist.x_help_x: 500\n"
  "TimeHist.x_help_y: 450\n"
  "TimeHist.x_help_width: 500\n"
  "TimeHist.x_help_height: 400\n"
  "TimeHist.x_help_min_height: 150\n"
  "\n"
  "#\n"
  "# margins and clearances  - pixels\n"
  "#\n"
  "\n"
  "TimeHist.x_xaxis_margin: 25\n"
  "\n"
  "TimeHist.x_tscale_yaxis_margin: 0\n"
  "TimeHist.x_thist_yaxis_margin: 20\n"
  "TimeHist.x_timeht_yaxis_margin: 30\n"
  "TimeHist.x_rdist_yaxis_margin: 30\n"
  "TimeHist.x_union_yaxis_margin: 35\n"
  "\n"
  "TimeHist.x_top_margin: 22\n"
  "TimeHist.x_xaxis_endmargin: 40\n"
  "TimeHist.x_yaxis_endmargin: 10\n"
  "TimeHist.x_tick_length: 6\n"
  "TimeHist.x_header_clearance: 5\n"
  "\n"
  "TimeHist.x_text_margin: 8\n"
  "\n"
  "#\n"
  "# X scale dimensions. The scale element height is the height of each\n"
  "# color block in the scale window.\n"
  "#\n"
  "\n"
  "TimeHist.x_max_scale_element_ht: 20\n"
  "TimeHist.x_scale_element_width: 20\n"
  "\n"
  "#\n"
  "# X line widths - pixels\n"
  "#\n"
  "\n"
  "TimeHist.x_current_time_line_width: 3\n"
  "TimeHist.x_tick_line_width: 0\n"
  "TimeHist.x_divider_line_width: 0\n"
  "TimeHist.x_main_border_width: 5\n"
  "TimeHist.x_sub_border_width: 1\n"
  "TimeHist.x_crosshair_line_width: 1\n"
  "\n"
  "#\n"
  "# X fonts\n"
  "#\n"
  "\n"
  "TimeHist.x_text_font: 8x13\n"
  "TimeHist.x_button_font: 8x13\n"
  "TimeHist.x_title_font: 8x13\n"
  "TimeHist.x_scale_font: 6x10\n"
  "TimeHist.x_ticklabel_font: 6x10\n"
  "TimeHist.x_header_font: 8x13\n"
  "\n"
  "#\n"
  "# X colors\n"
  "#\n"
  "\n"
  "TimeHist.x_foreground: white\n"
  "TimeHist.x_background: black\n"
  "\n"
  "TimeHist.x_thist_vol_color: gray80\n"
  "TimeHist.x_thist_area_color: cyan\n"
  "TimeHist.x_thist_pflux_color: green\n"
  "TimeHist.x_thist_mass_color: magenta\n"
  "TimeHist.x_thist_vil_color: yellow\n"
  "TimeHist.x_thist_forecast_color: red\n"
  "\n"
  "TimeHist.x_union_0_color: yellow\n"
  "TimeHist.x_union_1_color: cyan\n"
  "TimeHist.x_union_2_color: green\n"
  "TimeHist.x_union_3_color: magenta\n"
  "\n"
  "TimeHist.x_ht_maxdbz_color: blue\n"
  "TimeHist.x_top_base_color: yellow\n"
  "TimeHist.x_ht_centroid_color: green\n"
  "TimeHist.x_ht_refl_centroid_color: cyan\n"
  "\n"
  "TimeHist.x_tick_color: yellow\n"
  "TimeHist.x_ticklabel_color: yellow\n"
  "\n"
  "TimeHist.x_text_color: yellow\n"
  "TimeHist.x_header_color: yellow\n"
  "TimeHist.x_titletext_color: gray\n"
  "TimeHist.x_buttontext_color: red\n"
  "TimeHist.x_scaletext_color: gray\n"
  "TimeHist.x_crosshair_color: red\n"
  "\n"
  "TimeHist.x_divider_color: CadetBlue\n"
  "TimeHist.x_border_color: CadetBlue\n"
  "TimeHist.x_hlight_background: mediumblue\n"
  "\n"
  "#\n"
  "# Postscript COPIES\n"
  "# =================\n"
  "#\n"
  "\n"
  "TimeHist.draw_copy_title: true\n"
  "\n"
  "#\n"
  "# postscript scale - all dimensions in inches, so scale up by\n"
  "# 72 from points to inches\n"
  "#\n"
  "\n"
  "TimeHist.ps_unitscale: 72\n"
  "\n"
  "#\n"
  "# postscript page details\n"
  "#\n"
  "\n"
  "TimeHist.ps_page_length: 11.0\n"
  "TimeHist.ps_page_width: 8.5\n"
  "TimeHist.ps_length_margin: 0.7\n"
  "TimeHist.ps_width_margin: 0.7\n"
  "TimeHist.ps_text_margin: 1.0\n"
  "\n"
  "#\n"
  "# print width - the max width of the postscript output\n"
  "#\n"
  "\n"
  "TimeHist.ps_print_width: 8.0\n"
  "\n"
  "#\n"
  "# limits to be placed on the print width\n"
  "#\n"
  "\n"
  "TimeHist.ps_max_print_width: 11.0\n"
  "TimeHist.ps_min_print_width: 2.0\n"
  "\n"
  "#\n"
  "# postscript plot sizes and relevant dimensions - the plot sizes\n"
  "# refer to the main plot area. The scale element height is the height of each\n"
  "# block in the scale, and the scale width is the width of the scale window\n"
  "#\n"
  "\n"
  "TimeHist.ps_plot_width: 8.0\n"
  "TimeHist.ps_plot_height: 6.0\n"
  "TimeHist.ps_max_scale_element_ht: 0.4\n"
  "TimeHist.ps_scale_element_width: 0.3\n"
  "TimeHist.ps_timeht_scale_width: 1.0\n"
  "TimeHist.ps_rdist_scale_width: 1.0\n"
  "TimeHist.ps_title_height: 0.5\n"
  "\n"
  "#\n"
  "# margins and clearances in inches\n"
  "#\n"
  "\n"
  "TimeHist.ps_xaxis_margin: 0.3\n"
  "\n"
  "TimeHist.ps_tscale_yaxis_margin: 0.5\n"
  "TimeHist.ps_thist_yaxis_margin: 0.35\n"
  "TimeHist.ps_timeht_yaxis_margin: 0.4\n"
  "TimeHist.ps_rdist_yaxis_margin: 0.4\n"
  "TimeHist.ps_union_yaxis_margin: 0\n"
  "\n"
  "TimeHist.ps_top_margin: 0.35\n"
  "TimeHist.ps_xaxis_endmargin: .3\n"
  "TimeHist.ps_yaxis_endmargin: .05\n"
  "TimeHist.ps_tick_length: 0.06\n"
  "TimeHist.ps_header_clearance: 0.05\n"
  "TimeHist.ps_plot_to_scale_margin: 0.25\n"
  "TimeHist.ps_title_to_plot_margin: 0.2\n"
  "\n"
  "\n"
  "#\n"
  "# postscript line widths\n"
  "#\n"
  "\n"
  "TimeHist.ps_border_line_width: 1.0\n"
  "TimeHist.ps_divider_line_width: 0.0\n"
  "TimeHist.ps_tick_line_width: 1.0\n"
  "TimeHist.ps_crosshair_line_width: 1.0\n"
  "\n"
  "#\n"
  "# postscript linestyles\n"
  "#\n"
  "\n"
  "TimeHist.ps_thist_vol_linestyle: 1.0 100.0 0.0\n"
  "TimeHist.ps_thist_area_linestyle: 1.0 1.0 1.0\n"
  "TimeHist.ps_thist_pflux_linestyle: 1.0 3.0 1.0\n"
  "TimeHist.ps_thist_mass_linestyle: 1.0 5.0 2.0\n"
  "TimeHist.ps_thist_vil_linestyle: 1.0 10.0 4.0\n"
  "TimeHist.ps_thist_forecast_linestyle: 1.0 100.0 0.0\n"
  "\n"
  "TimeHist.ps_union_0_linestyle: 1.0 100.0 0.0\n"
  "TimeHist.ps_union_1_linestyle: 1.0 1.0 1.0\n"
  "TimeHist.ps_union_2_linestyle: 1.0 3.0 1.0\n"
  "TimeHist.ps_union_3_linestyle: 1.0 5.0 2.0\n"
  "\n"
  "TimeHist.ps_ht_maxdbz_linestyle: 1.0 100.0 0.0\n"
  "TimeHist.ps_top_base_linestyle: 1.0 100.0 0.0\n"
  "TimeHist.ps_ht_centroid_linestyle: 1.0 4.0 2.0\n"
  "TimeHist.ps_ht_refl_centroid_linestyle: 1.0 8.0 4.0\n"
  "\n"
  "#\n"
  "# postscript font name and sizes\n"
  "#\n"
  "\n"
  "TimeHist.ps_fontname: Helvetica\n"
  "TimeHist.ps_title_fontsize: 14\n"
  "TimeHist.ps_scale_fontsize: 10\n"
  "TimeHist.ps_ticklabel_fontsize: 10\n"
  "TimeHist.ps_header_fontsize: 12\n"
  "\n";
