#! /bin/bash -f
#
# check_apps: Check build for applications
#

#--------------------------------------------------------------------
# usage function
#

function usage() {
    echo
    echo "Usage: check_apps [options below] prefix"
    echo "  -h:  produce this usage list"
    echo "  -d:  turn debugging on"
    echo "  -p:  set prefix (default is /usr/local)"
    echo
}

#--------------------------------------------------------------------
# check args

prefix=/usr/local
debug=false

# Parse command line options.
while getopts hdp: OPT; do
    case "$OPT" in
        h)
            usage
            exit 0
            ;;
        d)
            debug=true
            ;;
        p)
            prefix=$OPTARG
            ;;
        \?)
            # getopts issues an error message
            echo "Problems with command line usage"
            usage
            exit 1
            ;;
    esac
done

# Remove the switches we parsed above.
shift `expr $OPTIND - 1`

echo "Checking lrose build"

./make_bin/check_apps.pl \
  -list ./distribs/lrose/apps_check_list \
  -dir $prefix/bin \
  -label "LROSE" || exit 1



