#!/bin/sh

# checkout for lrose

# Function to check out a RAP application group (i.e., "apps/<group>")
# from RAP CVS including all of its associated applications. Its 
# makefile.lrose will be copied into "apps/<group>/src/makefile"
#
# Usage: checkoutAppGroup <appGroup> [ <radx> <cidd> <titan> ]
# Will checkout _makefiles/makefile.radx if radx included on command line
# Will checkout _makefiles/makefile.cidd if cidd included on command line
# Will checkout _makefiles/makefile.titan if titan included on command line

checkoutAppGroup() {
  if [ "$#" -lt 1 ]; then
      echo "Usage: $FUNCNAME <appGroupName>"
      return 1
  fi
  appGroup=$1
  cvs co -P apps/$appGroup
  /bin/rm -rf apps/$appGroup/src/_makefiles
  echo cvs co -P apps/$appGroup/src/_makefiles/makefile.lrose
  cvs co -P apps/$appGroup/src/_makefiles/makefile.lrose
  /bin/cp apps/$appGroup/src/_makefiles/makefile.lrose apps/$appGroup/src/makefile
  if [ "$#" -ge 2 ]; then
      echo cvs co -P apps/$appGroup/src/_makefiles/makefile.$2
      cvs co -P apps/$appGroup/src/_makefiles/makefile.$2
  fi
  if [ "$#" -ge 3 ]; then
      echo cvs co -P apps/$appGroup/src/_makefiles/makefile.$3
      cvs co -P apps/$appGroup/src/_makefiles/makefile.$3
  fi
  if [ "$#" -ge 4 ]; then
      echo cvs co -P apps/$appGroup/src/_makefiles/makefile.$4
      cvs co -P apps/$appGroup/src/_makefiles/makefile.$4
  fi
}

# Function to check out a bare RAP application group ("apps/<group>")
# from RAP CVS *without* any of its associated applications. Its 
# makefile.lrose will be copied into "apps/<group>/src/makefile".
#
# Usage: checkoutBareAppGroup <appGroup> [ <radx> <cidd> <titan> ]
# Will checkout _makefiles/makefile.radx if radx included on command line
# Will checkout _makefiles/makefile.cidd if cidd included on command line
# Will checkout _makefiles/makefile.titan if titan included on command line

checkoutBareAppGroup() {
  if [ "$#" -lt 1 ]; then
      echo "Usage: $FUNCNAME <appGroupName>"
      return 1
  fi
  appGroup=$1
  
  # First get the apps/<appGroup> and apps/<appGroup>/src directories WITHOUT
  # their subdirectories. We need to check them out to get their non-directory
  # contents (including .cvsignore files).
  cvs co -lP apps/$appGroup     # contents of apps/<group> w/o subdirs
  cvs co -lP apps/$appGroup/src # contents of apps/<group>/src w/o subdirs
  
  # Now get the apps/<appGroup>/src/_makefiles directory and install the 
  # makefile.lrose from there as apps/<appGroup>/src/makefile.
  echo cvs co -P apps/$appGroup/src/_makefiles/makefile.lrose
  cvs co -P apps/$appGroup/src/_makefiles/makefile.lrose
  /bin/cp apps/$appGroup/src/_makefiles/makefile.lrose apps/$appGroup/src/makefile
  if [ "$#" -ge 2 ]; then
      echo cvs co -P apps/$appGroup/src/_makefiles/makefile.$2
      cvs co -P apps/$appGroup/src/_makefiles/makefile.$2
  fi
  if [ "$#" -ge 3 ]; then
      echo cvs co -P apps/$appGroup/src/_makefiles/makefile.$3
      cvs co -P apps/$appGroup/src/_makefiles/makefile.$3
  fi
  if [ "$#" -ge 4 ]; then
      echo cvs co -P apps/$appGroup/src/_makefiles/makefile.$4
      cvs co -P apps/$appGroup/src/_makefiles/makefile.$4
  fi
}

# Function to check out a single RAP application under its associated group
# (i.e., "apps/<group>/src/<app>"). Typically this is used to add select 
# applications after a bare group is checked out via checkoutBareAppGroup.
#
# Usage checkoutApp <appGroup> <app>

checkoutApp(){
  if [ "$#" -lt 2 ]; then
      echo "Usage: $FUNCNAME <appGroupName> <appName>"
      return 1
  fi
  appGroup=$1
  app=$2
  cvs co -P apps/$appGroup/src/$app
}


# distribution

cvs co -P distribs/lrose

# documentation

cvs co -P distribs/env_settings
cvs co -P distribs/env_setup
#cvs co -P htdocs/cidd
#cvs co -P htdocs/maps
#cvs co -P htdocs/colorscales
#cvs co -P htdocs/projects/titan
#cvs co -P htdocs/projects/CIDD

# make etc.

cvs co make_include
cvs co make_bin

# libraries

cvs co -lP libs/Makefile
cvs co -P libs/_makefiles/makefile.lrose
cvs co -P libs/_makefiles/makefile.cidd
cvs co -P libs/_makefiles/makefile.radx
cvs co -P libs/_makefiles/makefile.titan
/bin/cp libs/_makefiles/makefile.lrose libs/makefile

cvs co -P libs/FiltAlg
cvs co -P libs/Fmq
cvs co -P libs/Mdv
cvs co -P libs/NcUtils
cvs co -P libs/Radx
cvs co -P libs/Refract
cvs co -P libs/Spdb
cvs co -P libs/SpdbServer
cvs co -P libs/advect
cvs co -P libs/apiMdv
cvs co -P libs/apiTitan
cvs co -P libs/cidd
cvs co -P libs/contour
cvs co -P libs/dataport
cvs co -P libs/devguide
cvs co -P libs/didss
cvs co -P libs/dsdata
cvs co -P libs/dsserver
cvs co -P libs/euclid
cvs co -P libs/forayRal
cvs co -P libs/grib
cvs co -P libs/grib2
cvs co -P libs/hydro
cvs co -P libs/mdv
cvs co -P libs/mm5
cvs co -P libs/olgx
cvs co -P libs/perl5
cvs co -P libs/physics
cvs co -P libs/radar
cvs co -P libs/rapformats
cvs co -P libs/rapmath
cvs co -P libs/rapplot
cvs co -P libs/rdi
cvs co -P libs/shapelib
cvs co -P libs/spdb
cvs co -P libs/spdbFormats
cvs co -P libs/symprod
cvs co -P libs/tdrp
cvs co -P libs/titan
cvs co -P libs/toolsa
cvs co -P libs/kd
cvs co -P libs/trmm_rsl
cvs co -P libs/xview


# system apps

cvs co -lP apps/Makefile
cvs co -P apps/_makefiles
/bin/cp apps/_makefiles/makefile.lrose apps/makefile

checkoutAppGroup scripts radx cidd titan
checkoutAppGroup procmap radx cidd titan
cvs co -P apps/procmap/src/scripts

# tdrp apps

checkoutAppGroup tdrp radx cidd titan

# titan apps

checkoutAppGroup titan titan
checkoutAppGroup titan_analysis titan

# radar apps

checkoutAppGroup radar radx cidd titan
checkoutAppGroup spol
checkoutAppGroup physics

# Radx apps

checkoutAppGroup Radx radx titan

# trec apps

checkoutAppGroup trec titan

# symprod apps

checkoutAppGroup symprod titan

# didss apps

checkoutAppGroup didss titan

# ingest apps

checkoutBareAppGroup ingest titan

checkoutApp ingest AcData2Spdb
checkoutApp ingest AcTrack2Polygon
checkoutApp ingest AcarsNc2GenPt
checkoutApp ingest AccessA2Mdv
checkoutApp ingest Amdar2Spdb
checkoutApp ingest Asos6401toSpdb
checkoutApp ingest Awos2Spdb
checkoutApp ingest Aws2Spdb
checkoutApp ingest BomAws2Spdb
checkoutApp ingest BomSounding2Spdb
checkoutApp ingest Bprp2Dsr
checkoutApp ingest BuoyObs2Spdb
checkoutApp ingest CWB_FortranBinary2Mdv
checkoutApp ingest CfRadial2DeTect
checkoutApp ingest CimmsSeviriNc2Mdv
checkoutApp ingest CreateStationList
checkoutApp ingest CsuSounding2Spdb
checkoutApp ingest CwbAws2Spdb
checkoutApp ingest CwbObs2Spdb
checkoutApp ingest CwbSfc2Mdv
checkoutApp ingest DeTect2Dsr
checkoutApp ingest DeTectHorizXml2Spdb
checkoutApp ingest DoeSounding2Spbd
checkoutApp ingest Dorade2Dsr
checkoutApp ingest Dorade2DsrArchiveDriver
checkoutApp ingest EdrIngest
checkoutApp ingest EolSndg2Spdb
checkoutApp ingest EuMetSat2Mdv
checkoutApp ingest GamicVol2Dsr
checkoutApp ingest GemScan2Dsr
checkoutApp ingest GemVolXml2Dsr
checkoutApp ingest Gemtronik2Netcdf
checkoutApp ingest Gini2Gif
checkoutApp ingest Gini2Mdv
checkoutApp ingest Grib2Mdv
checkoutApp ingest Grib2toMdv
checkoutApp ingest Grib2toNc
checkoutApp ingest GtsSockIngest
checkoutApp ingest Hrrr15minNcf2Mdv
checkoutApp ingest Image2Mdv
checkoutApp ingest Image2MdvAdjunct
checkoutApp ingest JmaMtSatHRIT2Mdv
checkoutApp ingest KSMesonet2Spdb
checkoutApp ingest KavLtg2Mit
checkoutApp ingest LMAingest
checkoutApp ingest LdarFlashExtent
checkoutApp ingest LdarPointProcess
checkoutApp ingest LdmDynamic2Static
checkoutApp ingest LdmMetars2File
checkoutApp ingest Lirp2Dsr
checkoutApp ingest Lirp2NetCdf
checkoutApp ingest LnpIngest
checkoutApp ingest LookAtProc
checkoutApp ingest Ltg2Spdb
checkoutApp ingest Mesonet2Spdb
checkoutApp ingest Metar2Spdb
checkoutApp ingest MetarCsv2Spdb
checkoutApp ingest Metreport2Spdb
checkoutApp ingest Migfa2Spdb
checkoutApp ingest MitLtg2Spdb
checkoutApp ingest Mrms2Mdv
checkoutApp ingest MrmsGribIngest
checkoutApp ingest MrmsMosaic2NetCDF
checkoutApp ingest MtSatHRIT2Mdv
checkoutApp ingest NPLtg2Spdb
checkoutApp ingest NWSsoundingIngest
checkoutApp ingest NasaLtgClimoHdf2Mdv
checkoutApp ingest NcRadar2Dsr
checkoutApp ingest NcRadarSplit
checkoutApp ingest NcarAcPosn2Spdb
checkoutApp ingest NewNidsRadial2Mdv
checkoutApp ingest Nexrad2Netcdf
checkoutApp ingest NexradBzipDecompress
checkoutApp ingest Nids2Mdv
checkoutApp ingest NidsIngest
checkoutApp ingest NidsRadial2Mdv
checkoutApp ingest NidsRaster2Mdv
checkoutApp ingest NidsVad2Spdb
checkoutApp ingest Nmsu2Spdb
checkoutApp ingest NrlTpw2Mdv
checkoutApp ingest Pirep2Spdb
checkoutApp ingest PirepCsv2Spdb
checkoutApp ingest PolarSat2Mdv
checkoutApp ingest Precip2Spdb
checkoutApp ingest PrintDeTectFile
checkoutApp ingest PrintNids
checkoutApp ingest PtypeIngest
checkoutApp ingest QPESum2Dsr
checkoutApp ingest QPESumBinary2Mdv
checkoutApp ingest QPESumVectors2Mdv
checkoutApp ingest RawIQ2NetCDF
checkoutApp ingest Rdas2Dsr
checkoutApp ingest SST2Mdv
checkoutApp ingest Sams2Spdb
checkoutApp ingest SatOrbit2AcPosn
checkoutApp ingest SawsUm2Mdv
checkoutApp ingest SerialIngest
checkoutApp ingest SeviriNc2Mdv
checkoutApp ingest ShipObsIngest
checkoutApp ingest SigAirMet2Spdb
checkoutApp ingest Sigmet2Dsr
checkoutApp ingest SigmetRaw2Dsr
checkoutApp ingest SigmetUdp2Dsr
checkoutApp ingest SigwxIngest
checkoutApp ingest Smos2Spdb
checkoutApp ingest SnoTel
checkoutApp ingest SoundingFaker
checkoutApp ingest SoundingQuery
checkoutApp ingest SstNc2Mdv
checkoutApp ingest SurfaceAscii2Spdb
checkoutApp ingest SynopObsIngest
checkoutApp ingest TXSchoolnet2Spdb
checkoutApp ingest TXpet2Spdb
checkoutApp ingest Taf2Spdb
checkoutApp ingest TamdarAsciiSndg2Spdb
checkoutApp ingest TamdarNcSndg2Spdb
checkoutApp ingest Terascan2Mdv
checkoutApp ingest TimestampFile
checkoutApp ingest TrmmHdf2Mdv
checkoutApp ingest TrmmLisHdf2Spdb
checkoutApp ingest TrmmV7Hdf2Mdv
checkoutApp ingest UAEMesonet2Spdb
checkoutApp ingest Ude2Spdb
checkoutApp ingest Uf2Dsr
checkoutApp ingest UrbaNetWashington2Sfc
checkoutApp ingest Usgs2Spdb
checkoutApp ingest VaisalaLtg2Mdv
checkoutApp ingest WDTLtg2Spdb
checkoutApp ingest WDTncdf2Mdv
checkoutApp ingest WTXlidar2Dsr
checkoutApp ingest WWA2spdb
checkoutApp ingest WafsTiled2Mdv
checkoutApp ingest WestTx2Spdb
checkoutApp ingest Windtracer2Dsr
checkoutApp ingest Windtracer2ncd
checkoutApp ingest Wrf2Mdv
checkoutApp ingest WrfVIL2Mdv
checkoutApp ingest WsiMetarIngest
checkoutApp ingest WsiNidsIngest
checkoutApp ingest asciiTerrain2Mdv
checkoutApp ingest asdi2Vector
checkoutApp ingest asdi2mdv
checkoutApp ingest asdi2netcdf
checkoutApp ingest asdi2spdb
checkoutApp ingest asdiVector2mdv
checkoutApp ingest asdiXml2spdb
checkoutApp ingest aws2Spdb
checkoutApp ingest axfProfiler
checkoutApp ingest axfSonde
checkoutApp ingest axfSurface
checkoutApp ingest binet2dsr
checkoutApp ingest class2shapefile
checkoutApp ingest classIngest
checkoutApp ingest classSplitter
checkoutApp ingest clearRadarFmq
checkoutApp ingest euroRadar2Mdv
checkoutApp ingest euroSfc2Spdb
checkoutApp ingest fileOrganizer
checkoutApp ingest file_repeat_day
checkoutApp ingest findREALzeroes
checkoutApp ingest frenchRadar2Dsr
checkoutApp ingest gfsIngest
checkoutApp ingest hiResNids2Mdv
checkoutApp ingest hiResNidsEchoTop2Mdv
checkoutApp ingest hiResNidsRadialImg2Mdv
checkoutApp ingest hiResNidsStormPrecip2Mdv
checkoutApp ingest hiResNidsVil2Mdv
checkoutApp ingest httpFileFetch
checkoutApp ingest ihop3x3Goes2Mdv
checkoutApp ingest ihop3x3GoesTpwc2Mdv
checkoutApp ingest ihopASOSIngest
checkoutApp ingest ihopNcarIssCdf2Spdb
checkoutApp ingest ihopNcarSfc2Spdb
checkoutApp ingest ihopNcarSfcCdf2Spdb
checkoutApp ingest ihopSfcComp2Spdb
checkoutApp ingest ingestAsciiAcPos2Vectors
checkoutApp ingest iris2dsr
checkoutApp ingest lassenNetcdf2Dsr
checkoutApp ingest lassenNetcdf2Mdv
checkoutApp ingest little_r2Spdb
checkoutApp ingest llAsosIngest
checkoutApp ingest llwasAverage
checkoutApp ingest llwasIngest
checkoutApp ingest lmaFlashExtent
checkoutApp ingest lmaGridder
checkoutApp ingest lmaPointProcess
checkoutApp ingest lmaPreProcess
checkoutApp ingest lowResNids2Mdv
checkoutApp ingest madis2Spdb
checkoutApp ingest mdlBdry2Spdb
checkoutApp ingest mdlPoly2Spdb
checkoutApp ingest mysqlSurface2Spdb
checkoutApp ingest netCDF2StnRptSpdb
checkoutApp ingest netCDFmesonet2SPDB
checkoutApp ingest nexrad2dsr
checkoutApp ingest nexrad2netcdf
checkoutApp ingest nexradBzUncomp
checkoutApp ingest nexradII_bz
checkoutApp ingest noaaportLtg2Spdb
checkoutApp ingest normBeam
checkoutApp ingest profilerIngest
checkoutApp ingest quikSCATIngest
checkoutApp ingest radar2Dsr
checkoutApp ingest radarMosaic2Mdv
checkoutApp ingest realLidarStats
checkoutApp ingest renameRealLidarFile
checkoutApp ingest rttcLma2Mdv
checkoutApp ingest rucIngest
checkoutApp ingest satWinds2Spdb
checkoutApp ingest sndgIngest
checkoutApp ingest southWestKs2Spdb
checkoutApp ingest superResNexradII2Dsr
checkoutApp ingest superResNexradLdmUnzip
checkoutApp ingest superResNexradRawUnzip
checkoutApp ingest sweepMerge
checkoutApp ingest timrexSat2mdv

# rvp8 apps

checkoutAppGroup rvp8

# xpol apps

checkoutAppGroup xpol titan

# dsserver apps

checkoutAppGroup dsserver titan cidd

# mdv apps

checkoutAppGroup mdv_utils titan
checkoutAppGroup mm5

# spdb apps

checkoutAppGroup spdb_utils titan

# file dist apps

checkoutAppGroup filedist titan

# selected filter apps

checkoutBareAppGroup filters titan
checkoutApp filters ApRemoval
checkoutApp filters BrightBand
checkoutApp filters ClutterRemove
checkoutApp filters LogFilter
checkoutApp filters NoiseFilter
checkoutApp filters stratiform_filter
checkoutApp filters tops_filter

# selected interp apps

checkoutBareAppGroup interp titan
checkoutApp interp surf_interp
checkoutApp interp SurfInterp

# selected ltg apps

checkoutBareAppGroup awc titan
checkoutApp awc LtgSpdb2Mdv
checkoutApp awc combine_ltg_radar

# selected sat apps

checkoutBareAppGroup satApps titan
checkoutApp satApps IR2Height

# refractivity apps

checkoutAppGroup refractt

# cidd apps

checkoutAppGroup cidd titan cidd

# selected hydro apps

checkoutBareAppGroup hydro titan
checkoutApp hydro BasinGenPt2Symprod
checkoutApp hydro BasinPrecip
checkoutApp hydro BasinPrecipSpdb2Xml
checkoutApp hydro PrecipAccum
checkoutApp hydro RateAccum
checkoutApp hydro RainGage
checkoutApp hydro Shape2Map

# selected spdb_server apps

checkoutAppGroup spdb_server titan

# matlab support

cvs co -P apps/matlab/src/mdv2matlab

# Sysview - Java

cvs co java/src/edu/ucar/rap/ant

#cvs co java/src/edu/ucar/rap/sysview/apps/sysview/build.xml
#ant -f java/src/edu/ucar/rap/sysview/apps/sysview/build.xml cvs-checkout-all

cvs co -P java/src/edu/ucar/rap/didss
cvs co -P java/src/edu/ucar/rap/dsserver
cvs co -P java/src/edu/ucar/rap/euclid
cvs co -P java/src/edu/ucar/rap/graphics
cvs co -P java/src/edu/ucar/rap/jrp
cvs co -P java/src/edu/ucar/rap/msg
cvs co -P java/src/edu/ucar/rap/rapmath
cvs co -P java/src/edu/ucar/rap/rapplot
cvs co -P java/src/edu/ucar/rap/sysview
cvs co -P java/src/edu/ucar/rap/util
cvs co -P java/src/edu/ucar/rap/util118
cvs co -P java/src/edu/ucar/rap/xml
cvs co -P java/src/edu/ucar/rap/zudnik

cvs co -P java/ext_lib/jdom/jdom-1.0/jdom.jar
cvs co -P java/ext_lib/javamail/javamail-1.3.1/mail.jar

cvs co -P java/ext_lib/jai/jai-1_1_1_01/jai_codec.jar
cvs co -P java/ext_lib/jai/jai-1_1_1_01/jai_core.jar
cvs co -P java/ext_lib/jai/jai-1_1_1_01/libmlib_jai.so

cvs co -P java/ext_lib/xerces/xerces-2_2_1/xercesImpl.jar
cvs co -P java/ext_lib/xerces/xerces-2_2_1/xmlParserAPIs.jar

# JAZZ

cvs co data/resources/icons
cvs co distribs/JADE_bootstrap

#cvs co java/ext_lib/geotools
#cvs co java/ext_lib/glf
#cvs co java/ext_lib/jaf
#cvs co java/ext_lib/jai
#cvs co java/ext_lib/jakarta-commons-httpclient
#cvs co java/ext_lib/javamail
#cvs co java/ext_lib/javaws
#cvs co java/ext_lib/jaxen
#cvs co java/ext_lib/JTS
#cvs co java/ext_lib/saxpath
#cvs co java/ext_lib/servlet
#cvs co java/ext_lib/xerces

cvs co java/src/keystore.rap
cvs co java/src/edu/ucar/rap/ant
cvs co java/src/edu/ucar/rap/datatype
cvs co java/src/edu/ucar/rap/didss
cvs co java/src/edu/ucar/rap/dobson
cvs co java/src/edu/ucar/rap/dsserver
cvs co java/src/edu/ucar/rap/euclid
cvs co java/src/edu/ucar/rap/filter
cvs co java/src/edu/ucar/rap/geometry
cvs co java/src/edu/ucar/rap/graphics
cvs co java/src/edu/ucar/rap/image
cvs co java/src/edu/ucar/rap/jade
cvs co java/src/edu/ucar/rap/jadeite
cvs co java/src/edu/ucar/rap/jazz
cvs co java/src/edu/ucar/rap/mdv
cvs co java/src/edu/ucar/rap/rapmath
cvs co java/src/edu/ucar/rap/rapplot
cvs co java/src/edu/ucar/rap/spdb
cvs co java/src/edu/ucar/rap/spdbFormats
cvs co java/src/edu/ucar/rap/util
cvs co java/src/edu/ucar/rap/util118
cvs co java/src/edu/ucar/rap/xml

# ./distribs/JADE_bootstrap -p java/src/edu/ucar/rap/jazz/apps/jazz
# cd java/src/edu/ucar/rap/jazz/apps/jazz
# ant cvs-checkout-all
# cd ../../../../../../../../

