#! /bin/bash

#--------------------------------------------------------------------
#
# install source lrose release
#
# Mike Dixon, RAP, NCAR, Boulder, CO, USA
# July 2010
#
#--------------------------------------------------------------------

# set the path

export PATH=.:/bin:./make_bin:/usr/bin:/sbin:/usr/sbin:/usr/bin/X11:/usr/local/bin:/usr/local/sbin:$HOME/bin

# set package name

package=$1
sub_dir=$2
release_dir=$3

#######################################################
# get run time

year=`date -u +'%Y'`
month=`date -u +'%m'`
day=`date -u +'%d'`
hour=`date -u +'%H'`
min=`date -u +'%M'`
sec=`date -u +'%S'`

#--------------------------------------------------------------------

echo
echo "*********************************************************************"
echo
echo "  Installing ${package} source release"
echo
echo "  NCAR, Boulder, CO, USA"
echo
echo "  $year/$month/$day $hour:$min:$sec"
echo
echo "*********************************************************************"
echo

echo "Installing the src release ...."

release=`ls ${package}-????????.src.tgz`

# make sure previous_releases dir exists

target_dir=${release_dir}/${sub_dir}
prevdir=${target_dir}/previous_releases
if [ -f $prevdir ]
then
  /bin/rm -f $prevdir
fi
mkdir -p $prevdir

# move old release out of the way

/bin/mv -f ${target_dir}/${package}-????????.src.tgz ${target_dir}/previous_releases

# copy in new release

cp $release ${target_dir}

tar_url=ftp://ftp.rap.ucar.edu/pub/titan/${sub_dir}/${release}
formula_name="${package}.rb"
./distribs/${package}/build_${package}_formula $tar_url $release $formula_name

/bin/cp -f ./distribs/${package}/docs/*.TXT ${target_dir}
/bin/cp -rf ./distribs/${package}/RELEASE_NOTES/* ${target_dir}
/bin/mv -f $formula_name ${target_dir}

#--------------------------------------------------------------------
# done

echo
echo "  **************************************************"
echo "  *** Done installing src release ***"
echo "  *** release file name: $release ***"
echo "  **************************************************"
echo

exit 0
