/* *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* */
/* ** Copyright UCAR (c) 1990 - 2016                                         */
/* ** University Corporation for Atmospheric Research (UCAR)                 */
/* ** National Center for Atmospheric Research (NCAR)                        */
/* ** Boulder, Colorado, USA                                                 */
/* ** BSD licence applies - redistribution and use in source and binary      */
/* ** forms, with or without modification, are permitted provided that       */
/* ** the following conditions are met:                                      */
/* ** 1) If the software is modified to produce derivative works,            */
/* ** such modified software should be clearly marked, so as not             */
/* ** to confuse it with the version available from UCAR.                    */
/* ** 2) Redistributions of source code must retain the above copyright      */
/* ** notice, this list of conditions and the following disclaimer.          */
/* ** 3) Redistributions in binary form must reproduce the above copyright   */
/* ** notice, this list of conditions and the following disclaimer in the    */
/* ** documentation and/or other materials provided with the distribution.   */
/* ** 4) Neither the name of UCAR nor the names of its contributors,         */
/* ** if any, may be used to endorse or promote products derived from        */
/* ** this software without specific prior written permission.               */
/* ** DISCLAIMER: THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS  */
/* ** OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED      */
/* ** WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.    */
/* *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* */
/*******************************************
 * track_server_tdrp.c
 *
 * TDRP C code file 'track_server' module.
 *
 * Code for program track_server
 *
 * This file has been automatically
 * generated by TDRP, do not modify.
 *
 *******************************************/

#include "track_server_tdrp.h"
#include <string.h>

/*
 * file scope variables
 */

static TDRPtable Table[24];
static track_server_tdrp_struct *Params;
static char *Module = "track_server";

/*************************************************************
 * track_server_tdrp_load_from_args()
 *
 * Loads up TDRP using the command line args.
 *
 * Check TDRP_usage() for command line actions associated with
 * this function.
 *
 *   argc, argv: command line args
 *
 *   track_server_tdrp_struct *params: loads up this struct
 * 
 *   char **override_list: A null-terminated list of overrides
 *     to the parameter file.
 *     An override string has exactly the format of an entry
 *     in the parameter file itself.
 *
 *   char **params_path_p: if non-NULL, this is set to point to
 *                         the path of the params file used.
 *
 *  Returns 0 on success, -1 on failure.
 */

int track_server_tdrp_load_from_args(int argc, char **argv,
                         track_server_tdrp_struct *params,
                         char **override_list,
                         char **params_path_p)
{
  Params = params;
  track_server_tdrp_init(Params);
  if (tdrpLoadFromArgs(argc, argv,
                       Table, Params,
                       override_list, params_path_p)) {
    return (-1);
  } else {
    return (0);
  }
}

/*************************************************************
 * track_server_tdrp_load()
 *
 * Loads up TDRP for a given module.
 *
 * This version of load gives the programmer the option to load
 * up more than one module for a single application. It is a
 * lower-level routine than track_server_tdrp_load_from_args,
 * and hence more flexible, but the programmer must do more work.
 *
 *   char *param_file_path: the parameter file to be read in.
 *
 *   track_server_tdrp_struct *params: loads up this struct
 *
 *   char **override_list: A null-terminated list of overrides
 *     to the parameter file.
 *     An override string has exactly the format of an entry
 *     in the parameter file itself.
 *
 *  expand_env: flag to control environment variable
 *                expansion during tokenization.
 *              If TRUE, environment expansion is set on.
 *              If FALSE, environment expansion is set off.
 *
 *  Returns 0 on success, -1 on failure.
 */

int track_server_tdrp_load(char *param_file_path,
               track_server_tdrp_struct *params,
               char **override_list,
               int expand_env, int debug)
{
  Params = params;
  track_server_tdrp_init(Params);
  if (tdrpLoad(param_file_path, Table,
               params, override_list,
               expand_env, debug)) {
    return (-1);
  } else {
    return (0);
  }
}

/*************************************************************
 * track_server_tdrp_load_defaults()
 *
 * Loads up defaults for a given module.
 *
 * See track_server_tdrp_load() for more details.
 *
 *  Returns 0 on success, -1 on failure.
 */

int track_server_tdrp_load_defaults(track_server_tdrp_struct *params,
                        int expand_env)
{
  Params = params;
  track_server_tdrp_init(Params);
  if (tdrpLoad(NULL, Table,
               params, NULL,
               expand_env, FALSE)) {
    return (-1);
  } else {
    return (0);
  }
}

/*************************************************************
 * track_server_tdrp_sync()
 *
 * Syncs the user struct data back into the parameter table,
 * in preparation for printing.
 */

void track_server_tdrp_sync(void)
{
  tdrpUser2Table(Table, Params);
}

/*************************************************************
 * track_server_tdrp_print()
 * 
 * Print params file
 *
 * The modes supported are:
 *
 *   PRINT_SHORT:   main comments only, no help or descriptions
 *                  structs and arrays on a single line
 *   PRINT_NORM:    short + descriptions and help
 *   PRINT_LONG:    norm  + arrays and structs expanded
 *   PRINT_VERBOSE: long  + private params included
 */

void track_server_tdrp_print(FILE *out, tdrp_print_mode_t mode)
{
  tdrpPrint(out, Table, Module, mode);
}

/*************************************************************
 * track_server_tdrp_check_all_set()
 *
 * Return TRUE if all set, FALSE if not.
 *
 * If out is non-NULL, prints out warning messages for those
 * parameters which are not set.
 */

int track_server_tdrp_check_all_set(FILE *out)
{
  return (tdrpCheckAllSet(out, Table, Params));
}

/*************************************************************
 * track_server_tdrp_check_is_set()
 *
 * Return TRUE if parameter is set, FALSE if not.
 *
 */

int track_server_tdrp_check_is_set(char *param_name)
{
  return (tdrpCheckIsSet(param_name, Table, Params));
}

/*************************************************************
 * track_server_tdrp_free_all()
 *
 * Frees up all TDRP dynamic memory.
 */

void track_server_tdrp_free_all(void)
{
  tdrpFreeAll(Table, Params);
}

/*************************************************************
 * track_server_tdrp_array_realloc()
 *
 * Realloc 1D array.
 *
 * If size is increased, the values from the last array entry is
 * copied into the new space.
 *
 * Returns 0 on success, -1 on error.
 */

int track_server_tdrp_array_realloc(char *param_name, int new_array_n)
{
  if (tdrpArrayRealloc(Table, Params, param_name, new_array_n)) {
    return (-1);
  } else {
    return (0);
  }
}

/*************************************************************
 * track_server_tdrp_array2D_realloc()
 *
 * Realloc 2D array.
 *
 * If size is increased, the values from the last array entry is
 * copied into the new space.
 *
 * Returns 0 on success, -1 on error.
 */

int track_server_tdrp_array2D_realloc(char *param_name,
                          int new_array_n1,
                          int new_array_n2)
{
  if (tdrpArray2DRealloc(Table, Params, param_name,
			 new_array_n1, new_array_n2)) {
    return (-1);
  } else {
    return (0);
  }
}

/*************************************************************
 * track_server_tdrp_table()
 *
 * Returns pointer to static Table for this module.
 */

TDRPtable *track_server_tdrp_table(void)
{
  return (Table);
}

/*************************************************************
 * track_server_tdrp_init()
 *
 * Module table initialization function.
 *
 *
 * Returns pointer to static Table for this module.
 */

TDRPtable *track_server_tdrp_init(track_server_tdrp_struct *params)

{

  TDRPtable *tt = Table;

  track_server_tdrp_struct pp; /* for computing byte_offsets */

  /* zero out struct, and store size */

  memset(params, 0, sizeof(track_server_tdrp_struct));
  params->struct_size = sizeof(track_server_tdrp_struct);

  /* Parameter 'debug' */
  /* ctype is 'track_server_debug' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = ENUM_TYPE;
  tt->param_name = tdrpStrDup("debug");
  tt->descr = tdrpStrDup("Debug option");
  tt->help = tdrpStrDup("If set, debug messages will be printed appropriately. DEBUG_EXTRA and above suppresses the spawning of child processes.");
  tt->val_offset = (char *) &(pp.debug) - (char *) &pp;
  tt->enum_def.name = tdrpStrDup("debug");
  tt->enum_def.nfields = 5;
  tt->enum_def.fields = (enum_field_t *)
      tdrpMalloc(tt->enum_def.nfields * sizeof(enum_field_t));
    tt->enum_def.fields[0].name = tdrpStrDup("DEBUG_OFF");
    tt->enum_def.fields[0].val = DEBUG_OFF;
    tt->enum_def.fields[1].name = tdrpStrDup("DEBUG_WARNINGS");
    tt->enum_def.fields[1].val = DEBUG_WARNINGS;
    tt->enum_def.fields[2].name = tdrpStrDup("DEBUG_NORM");
    tt->enum_def.fields[2].val = DEBUG_NORM;
    tt->enum_def.fields[3].name = tdrpStrDup("DEBUG_EXTRA");
    tt->enum_def.fields[3].val = DEBUG_EXTRA;
    tt->enum_def.fields[4].name = tdrpStrDup("DEBUG_VERBOSE");
    tt->enum_def.fields[4].val = DEBUG_VERBOSE;
  tt->single_val.e = DEBUG_OFF;
  tt++;
  
  /* Parameter 'malloc_debug_level' */
  /* ctype is 'long' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = LONG_TYPE;
  tt->param_name = tdrpStrDup("malloc_debug_level");
  tt->descr = tdrpStrDup("Malloc debug level");
  tt->help = tdrpStrDup("0 - none, 1 - corruption checking, 2 - records all malloc blocks and checks, 3 - printout of all mallocs etc.");
  tt->val_offset = (char *) &(pp.malloc_debug_level) - (char *) &pp;
  tt->has_min = TRUE;
  tt->has_max = TRUE;
  tt->min_val.l = 0;
  tt->max_val.l = 3;
  tt->single_val.l = 0;
  tt++;
  
  /* Parameter 'instance' */
  /* ctype is 'char*' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = STRING_TYPE;
  tt->param_name = tdrpStrDup("instance");
  tt->descr = tdrpStrDup("Process and server instance");
  tt->help = tdrpStrDup("Used for registration with procmap and servmap.");
  tt->val_offset = (char *) &(pp.instance) - (char *) &pp;
  tt->single_val.s = tdrpStrDup("Test");
  tt++;
  
  /* Parameter 'subtype' */
  /* ctype is 'char*' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = STRING_TYPE;
  tt->param_name = tdrpStrDup("subtype");
  tt->descr = tdrpStrDup("Server subtype");
  tt->help = tdrpStrDup("Used for registration with servmap.");
  tt->val_offset = (char *) &(pp.subtype) - (char *) &pp;
  tt->single_val.s = tdrpStrDup("Test");
  tt++;
  
  /* Parameter 'info' */
  /* ctype is 'char*' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = STRING_TYPE;
  tt->param_name = tdrpStrDup("info");
  tt->descr = tdrpStrDup("Server info");
  tt->help = tdrpStrDup("Used for registration with servmap.");
  tt->val_offset = (char *) &(pp.info) - (char *) &pp;
  tt->single_val.s = tdrpStrDup("Test");
  tt++;
  
  /* Parameter 'port' */
  /* ctype is 'long' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = LONG_TYPE;
  tt->param_name = tdrpStrDup("port");
  tt->descr = tdrpStrDup("Server port number.");
  tt->help = tdrpStrDup("TCP/IP port for this server.");
  tt->val_offset = (char *) &(pp.port) - (char *) &pp;
  tt->has_min = TRUE;
  tt->min_val.l = 10000;
  tt->single_val.l = 44000;
  tt++;
  
  /* Parameter 'storm_data_dir' */
  /* ctype is 'char*' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = STRING_TYPE;
  tt->param_name = tdrpStrDup("storm_data_dir");
  tt->descr = tdrpStrDup("Storm data directory");
  tt->help = tdrpStrDup("Directory holding the storm data.");
  tt->val_offset = (char *) &(pp.storm_data_dir) - (char *) &pp;
  tt->single_val.s = tdrpStrDup(".");
  tt++;
  
  /* Parameter 'realtime_avail' */
  /* ctype is 'tdrp_bool_t' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = BOOL_TYPE;
  tt->param_name = tdrpStrDup("realtime_avail");
  tt->descr = tdrpStrDup("Real-time flag");
  tt->help = tdrpStrDup("If set, indicates real-time data is available, shmem is created.");
  tt->val_offset = (char *) &(pp.realtime_avail) - (char *) &pp;
  tt->single_val.b = pFALSE;
  tt++;
  
  /* Parameter 'max_realtime_valid_age' */
  /* ctype is 'double' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = DOUBLE_TYPE;
  tt->param_name = tdrpStrDup("max_realtime_valid_age");
  tt->descr = tdrpStrDup("Max valid age of input files in realtime mode (secs)");
  tt->help = tdrpStrDup("This the max valid age for an incoming file. The program will wait for a data file more recent than this.");
  tt->val_offset = (char *) &(pp.max_realtime_valid_age) - (char *) &pp;
  tt->has_min = TRUE;
  tt->min_val.d = 1;
  tt->single_val.d = 360;
  tt++;
  
  /* Parameter 'max_packet_length' */
  /* ctype is 'long' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = LONG_TYPE;
  tt->param_name = tdrpStrDup("max_packet_length");
  tt->descr = tdrpStrDup("Max packet length.");
  tt->help = tdrpStrDup("Max length of packets for communicating with clients.");
  tt->val_offset = (char *) &(pp.max_packet_length) - (char *) &pp;
  tt->has_min = TRUE;
  tt->min_val.l = 10000;
  tt->single_val.l = 100000;
  tt++;
  
  /* Parameter 'product_mode_send_invalid_forecasts' */
  /* ctype is 'tdrp_bool_t' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = BOOL_TYPE;
  tt->param_name = tdrpStrDup("product_mode_send_invalid_forecasts");
  tt->descr = tdrpStrDup("Send invalid forecasts flag");
  tt->help = tdrpStrDup("Product output mode. If set, all forecasts will be sent. If not, only those marked valid will be sent.");
  tt->val_offset = (char *) &(pp.product_mode_send_invalid_forecasts) - (char *) &pp;
  tt->single_val.b = pFALSE;
  tt++;
  
  /* Parameter 'product_mode_forecast_lead_time' */
  /* ctype is 'long' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = LONG_TYPE;
  tt->param_name = tdrpStrDup("product_mode_forecast_lead_time");
  tt->descr = tdrpStrDup("Forecast lead time (secs).");
  tt->help = tdrpStrDup("Lead time for forecast shapes and positions.");
  tt->val_offset = (char *) &(pp.product_mode_forecast_lead_time) - (char *) &pp;
  tt->single_val.l = 1800;
  tt++;
  
  /* Parameter 'product_mode_product_id' */
  /* ctype is 'long' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = LONG_TYPE;
  tt->param_name = tdrpStrDup("product_mode_product_id");
  tt->descr = tdrpStrDup("Product id.");
  tt->help = tdrpStrDup("The product server uses this id to select a transformation routine.");
  tt->val_offset = (char *) &(pp.product_mode_product_id) - (char *) &pp;
  tt->has_min = TRUE;
  tt->min_val.l = 1;
  tt->single_val.l = 10100;
  tt++;
  
  /* Parameter 'product_mode_plot_current' */
  /* ctype is 'tdrp_bool_t' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = BOOL_TYPE;
  tt->param_name = tdrpStrDup("product_mode_plot_current");
  tt->descr = tdrpStrDup("Plot current shape flag");
  tt->help = tdrpStrDup("Product output mode. If set, the current storm shape will be sent.");
  tt->val_offset = (char *) &(pp.product_mode_plot_current) - (char *) &pp;
  tt->single_val.b = pFALSE;
  tt++;
  
  /* Parameter 'product_mode_plot_forecast' */
  /* ctype is 'tdrp_bool_t' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = BOOL_TYPE;
  tt->param_name = tdrpStrDup("product_mode_plot_forecast");
  tt->descr = tdrpStrDup("Plot forecast shape flag");
  tt->help = tdrpStrDup("Product output mode. If set, the forecast storm shape will be sent.");
  tt->val_offset = (char *) &(pp.product_mode_plot_forecast) - (char *) &pp;
  tt->single_val.b = pFALSE;
  tt++;
  
  /* Parameter 'product_mode_plot_ellipse' */
  /* ctype is 'tdrp_bool_t' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = BOOL_TYPE;
  tt->param_name = tdrpStrDup("product_mode_plot_ellipse");
  tt->descr = tdrpStrDup("Plot shape as ellipse");
  tt->help = tdrpStrDup("Product output mode. If set, the storm shape will be represented by and ellipse.");
  tt->val_offset = (char *) &(pp.product_mode_plot_ellipse) - (char *) &pp;
  tt->single_val.b = pFALSE;
  tt++;
  
  /* Parameter 'product_mode_plot_polygon' */
  /* ctype is 'tdrp_bool_t' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = BOOL_TYPE;
  tt->param_name = tdrpStrDup("product_mode_plot_polygon");
  tt->descr = tdrpStrDup("Plot shape as polygon");
  tt->help = tdrpStrDup("Product output mode. If set, the storm shape will be represented by and polygon.");
  tt->val_offset = (char *) &(pp.product_mode_plot_polygon) - (char *) &pp;
  tt->single_val.b = pFALSE;
  tt++;
  
  /* Parameter 'product_mode_plot_trend' */
  /* ctype is 'tdrp_bool_t' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = BOOL_TYPE;
  tt->param_name = tdrpStrDup("product_mode_plot_trend");
  tt->descr = tdrpStrDup("Plot trend");
  tt->help = tdrpStrDup("Product output mode. If set, the storm size and intensity trend will be included as text: '+' or '-'.");
  tt->val_offset = (char *) &(pp.product_mode_plot_trend) - (char *) &pp;
  tt->single_val.b = pFALSE;
  tt++;
  
  /* Parameter 'product_mode_speed_knots' */
  /* ctype is 'tdrp_bool_t' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = BOOL_TYPE;
  tt->param_name = tdrpStrDup("product_mode_speed_knots");
  tt->descr = tdrpStrDup("Plot speed as knots.");
  tt->help = tdrpStrDup("Product output mode. Default is speed as km/hr.");
  tt->val_offset = (char *) &(pp.product_mode_speed_knots) - (char *) &pp;
  tt->single_val.b = pFALSE;
  tt++;
  
  /* Parameter 'product_mode_speed_round' */
  /* ctype is 'tdrp_bool_t' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = BOOL_TYPE;
  tt->param_name = tdrpStrDup("product_mode_speed_round");
  tt->descr = tdrpStrDup("Plot speed rounded to nearest 5.");
  tt->help = tdrpStrDup("Product output mode. Default is not rounded.");
  tt->val_offset = (char *) &(pp.product_mode_speed_round) - (char *) &pp;
  tt->single_val.b = pFALSE;
  tt++;
  
  /* Parameter 'product_mode_fixed_length_arrows' */
  /* ctype is 'tdrp_bool_t' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = BOOL_TYPE;
  tt->param_name = tdrpStrDup("product_mode_fixed_length_arrows");
  tt->descr = tdrpStrDup("Fixed length arrows flag");
  tt->help = tdrpStrDup("Product output mode. If flag set, direction arrows are of fixed lenght. If not set, arrows are scaled to length for time product_mode_forecast_lead_time.");
  tt->val_offset = (char *) &(pp.product_mode_fixed_length_arrows) - (char *) &pp;
  tt->single_val.b = pFALSE;
  tt++;
  
  /* Parameter 'product_mode_zero_growth_forecast' */
  /* ctype is 'tdrp_bool_t' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = BOOL_TYPE;
  tt->param_name = tdrpStrDup("product_mode_zero_growth_forecast");
  tt->descr = tdrpStrDup("Zero growth forecast flag");
  tt->help = tdrpStrDup("Product output mode. If flag set, growth forecasts are forced to zero. Default is growth is non-zero.");
  tt->val_offset = (char *) &(pp.product_mode_zero_growth_forecast) - (char *) &pp;
  tt->single_val.b = pFALSE;
  tt++;
  
  /* Parameter 'product_mode_resend_old_data' */
  /* ctype is 'tdrp_bool_t' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = BOOL_TYPE;
  tt->param_name = tdrpStrDup("product_mode_resend_old_data");
  tt->descr = tdrpStrDup("Option to resend old data");
  tt->help = tdrpStrDup("Product output mode. If flag set, previously sent data will be resent if the algorithms are rerun. If not, only data later than that previously sent will be sent.");
  tt->val_offset = (char *) &(pp.product_mode_resend_old_data) - (char *) &pp;
  tt->single_val.b = pFALSE;
  tt++;
  
  /* trailing entry has param_name set to NULL */
  
  tt->param_name = NULL;
  
  return (Table);

}
