#---------------------------------------------------------------------
#
# Makefile for script files
#
#---------------------------------------------------------------------

#	Default INSTALL_DIR, should be overridden on command line

INSTALL_DIR=$(RAP_BIN_DIR)

#	Script files to be installed

SCRIPTS = \
	createConfigure.am.py \
	createMakefile.am.app.py \
	createMakefile.am.lib.py \
	createMakefile.am.recurse.py \
	createMakefile.am.topdir.py \
	fixConfigure.py \
	runAutoConf.py \
	run_autoconf

#	Targets

include $(RAP_MAKE_INC_DIR)/rap_make_script_targets
