
include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGET_FILE = ../libspdbFormats.a

LOC_INCLUDES = -I../include
LOC_CFLAGS =

HDRS = \

#CPPC_SRCS = \
#	Sounding.cc \
#	SoundingPut.cc \
#	SoundingGet.cc

C_SRCS = \
	sounding.c \

#
# general targets
#

include $(RAP_MAKE_INC_DIR)/rap_make_lib_module_targets

#
# local targets
#

depend: depend_generic

# DO NOT DELETE THIS LINE -- make depend depends on it.
