/* *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* */
/* ** Copyright UCAR (c) 1990 - 2016                                         */
/* ** University Corporation for Atmospheric Research (UCAR)                 */
/* ** National Center for Atmospheric Research (NCAR)                        */
/* ** Boulder, Colorado, USA                                                 */
/* ** BSD licence applies - redistribution and use in source and binary      */
/* ** forms, with or without modification, are permitted provided that       */
/* ** the following conditions are met:                                      */
/* ** 1) If the software is modified to produce derivative works,            */
/* ** such modified software should be clearly marked, so as not             */
/* ** to confuse it with the version available from UCAR.                    */
/* ** 2) Redistributions of source code must retain the above copyright      */
/* ** notice, this list of conditions and the following disclaimer.          */
/* ** 3) Redistributions in binary form must reproduce the above copyright   */
/* ** notice, this list of conditions and the following disclaimer in the    */
/* ** documentation and/or other materials provided with the distribution.   */
/* ** 4) Neither the name of UCAR nor the names of its contributors,         */
/* ** if any, may be used to endorse or promote products derived from        */
/* ** this software without specific prior written permission.               */
/* ** DISCLAIMER: THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS  */
/* ** OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED      */
/* ** WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.    */
/* *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* */
/*******************************************
 * gint2mdv_tdrp.c
 *
 * TDRP C code file 'gint2mdv' module.
 *
 * This file has been automatically
 * generated by TDRP, do not modify.
 *
 *******************************************/

#include "gint2mdv_tdrp.h"
#include <string.h>

/*
 * file scope variables
 */

static TDRPtable Table[22];
static gint2mdv_tdrp_struct *Params;
static char *Module = "gint2mdv";

/*************************************************************
 * gint2mdv_tdrp_load_from_args()
 *
 * Loads up TDRP using the command line args.
 *
 * Check TDRP_usage() for command line actions associated with
 * this function.
 *
 *   argc, argv: command line args
 *
 *   gint2mdv_tdrp_struct *params: loads up this struct
 * 
 *   char **override_list: A null-terminated list of overrides
 *     to the parameter file.
 *     An override string has exactly the format of an entry
 *     in the parameter file itself.
 *
 *   char **params_path_p: if non-NULL, this is set to point to
 *                         the path of the params file used.
 *
 *  Returns 0 on success, -1 on failure.
 */

int gint2mdv_tdrp_load_from_args(int argc, char **argv,
                         gint2mdv_tdrp_struct *params,
                         char **override_list,
                         char **params_path_p)
{
  Params = params;
  gint2mdv_tdrp_init(Params);
  if (tdrpLoadFromArgs(argc, argv,
                       Table, Params,
                       override_list, params_path_p)) {
    return (-1);
  } else {
    return (0);
  }
}

/*************************************************************
 * gint2mdv_tdrp_load()
 *
 * Loads up TDRP for a given module.
 *
 * This version of load gives the programmer the option to load
 * up more than one module for a single application. It is a
 * lower-level routine than gint2mdv_tdrp_load_from_args,
 * and hence more flexible, but the programmer must do more work.
 *
 *   char *param_file_path: the parameter file to be read in.
 *
 *   gint2mdv_tdrp_struct *params: loads up this struct
 *
 *   char **override_list: A null-terminated list of overrides
 *     to the parameter file.
 *     An override string has exactly the format of an entry
 *     in the parameter file itself.
 *
 *  expand_env: flag to control environment variable
 *                expansion during tokenization.
 *              If TRUE, environment expansion is set on.
 *              If FALSE, environment expansion is set off.
 *
 *  Returns 0 on success, -1 on failure.
 */

int gint2mdv_tdrp_load(char *param_file_path,
               gint2mdv_tdrp_struct *params,
               char **override_list,
               int expand_env, int debug)
{
  Params = params;
  gint2mdv_tdrp_init(Params);
  if (tdrpLoad(param_file_path, Table,
               params, override_list,
               expand_env, debug)) {
    return (-1);
  } else {
    return (0);
  }
}

/*************************************************************
 * gint2mdv_tdrp_load_defaults()
 *
 * Loads up defaults for a given module.
 *
 * See gint2mdv_tdrp_load() for more details.
 *
 *  Returns 0 on success, -1 on failure.
 */

int gint2mdv_tdrp_load_defaults(gint2mdv_tdrp_struct *params,
                        int expand_env)
{
  Params = params;
  gint2mdv_tdrp_init(Params);
  if (tdrpLoad(NULL, Table,
               params, NULL,
               expand_env, FALSE)) {
    return (-1);
  } else {
    return (0);
  }
}

/*************************************************************
 * gint2mdv_tdrp_sync()
 *
 * Syncs the user struct data back into the parameter table,
 * in preparation for printing.
 */

void gint2mdv_tdrp_sync(void)
{
  tdrpUser2Table(Table, Params);
}

/*************************************************************
 * gint2mdv_tdrp_print()
 * 
 * Print params file
 *
 * The modes supported are:
 *
 *   PRINT_SHORT:   main comments only, no help or descriptions
 *                  structs and arrays on a single line
 *   PRINT_NORM:    short + descriptions and help
 *   PRINT_LONG:    norm  + arrays and structs expanded
 *   PRINT_VERBOSE: long  + private params included
 */

void gint2mdv_tdrp_print(FILE *out, tdrp_print_mode_t mode)
{
  tdrpPrint(out, Table, Module, mode);
}

/*************************************************************
 * gint2mdv_tdrp_check_all_set()
 *
 * Return TRUE if all set, FALSE if not.
 *
 * If out is non-NULL, prints out warning messages for those
 * parameters which are not set.
 */

int gint2mdv_tdrp_check_all_set(FILE *out)
{
  return (tdrpCheckAllSet(out, Table, Params));
}

/*************************************************************
 * gint2mdv_tdrp_check_is_set()
 *
 * Return TRUE if parameter is set, FALSE if not.
 *
 */

int gint2mdv_tdrp_check_is_set(char *param_name)
{
  return (tdrpCheckIsSet(param_name, Table, Params));
}

/*************************************************************
 * gint2mdv_tdrp_free_all()
 *
 * Frees up all TDRP dynamic memory.
 */

void gint2mdv_tdrp_free_all(void)
{
  tdrpFreeAll(Table, Params);
}

/*************************************************************
 * gint2mdv_tdrp_array_realloc()
 *
 * Realloc 1D array.
 *
 * If size is increased, the values from the last array entry is
 * copied into the new space.
 *
 * Returns 0 on success, -1 on error.
 */

int gint2mdv_tdrp_array_realloc(char *param_name, int new_array_n)
{
  if (tdrpArrayRealloc(Table, Params, param_name, new_array_n)) {
    return (-1);
  } else {
    return (0);
  }
}

/*************************************************************
 * gint2mdv_tdrp_array2D_realloc()
 *
 * Realloc 2D array.
 *
 * If size is increased, the values from the last array entry is
 * copied into the new space.
 *
 * Returns 0 on success, -1 on error.
 */

int gint2mdv_tdrp_array2D_realloc(char *param_name,
                          int new_array_n1,
                          int new_array_n2)
{
  if (tdrpArray2DRealloc(Table, Params, param_name,
			 new_array_n1, new_array_n2)) {
    return (-1);
  } else {
    return (0);
  }
}

/*************************************************************
 * gint2mdv_tdrp_table()
 *
 * Returns pointer to static Table for this module.
 */

TDRPtable *gint2mdv_tdrp_table(void)
{
  return (Table);
}

/*************************************************************
 * gint2mdv_tdrp_init()
 *
 * Module table initialization function.
 *
 *
 * Returns pointer to static Table for this module.
 */

TDRPtable *gint2mdv_tdrp_init(gint2mdv_tdrp_struct *params)

{

  TDRPtable *tt = Table;

  gint2mdv_tdrp_struct pp; /* for computing byte_offsets */

  /* zero out struct, and store size */

  memset(params, 0, sizeof(gint2mdv_tdrp_struct));
  params->struct_size = sizeof(gint2mdv_tdrp_struct);

  /* Parameter 'debug' */
  /* ctype is 'tdrp_bool_t' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = BOOL_TYPE;
  tt->param_name = tdrpStrDup("debug");
  tt->descr = tdrpStrDup("Option to print debugging messages");
  tt->help = tdrpStrDup("");
  tt->val_offset = (char *) &(pp.debug) - (char *) &pp;
  tt->single_val.b = pFALSE;
  tt++;
  
  /* Parameter 'check_params' */
  /* ctype is 'tdrp_bool_t' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = BOOL_TYPE;
  tt->param_name = tdrpStrDup("check_params");
  tt->descr = tdrpStrDup("Option to check if parameters are set");
  tt->help = tdrpStrDup("If this is true, a check will be made on which parameters is set. A report will be generated for those params which are using the defaults");
  tt->val_offset = (char *) &(pp.check_params) - (char *) &pp;
  tt->single_val.b = pFALSE;
  tt++;
  
  /* Parameter 'print_params' */
  /* ctype is 'tdrp_bool_t' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = BOOL_TYPE;
  tt->param_name = tdrpStrDup("print_params");
  tt->descr = tdrpStrDup("Option to print parameters ");
  tt->help = tdrpStrDup("If this is true, used parameters will be printed at the beginning of the run.");
  tt->val_offset = (char *) &(pp.print_params) - (char *) &pp;
  tt->single_val.b = pFALSE;
  tt++;
  
  /* Parameter 'path_delim' */
  /* ctype is 'char*' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = STRING_TYPE;
  tt->param_name = tdrpStrDup("path_delim");
  tt->descr = tdrpStrDup("path delimiter");
  tt->help = tdrpStrDup("");
  tt->val_offset = (char *) &(pp.path_delim) - (char *) &pp;
  tt->is_private = TRUE;
  tt->single_val.s = tdrpStrDup("/");
  tt++;
  
  /* Parameter 'input_file_suffix' */
  /* ctype is 'char*' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = STRING_TYPE;
  tt->param_name = tdrpStrDup("input_file_suffix");
  tt->descr = tdrpStrDup("input file suffix");
  tt->help = tdrpStrDup("");
  tt->val_offset = (char *) &(pp.input_file_suffix) - (char *) &pp;
  tt->single_val.s = tdrpStrDup("nbr");
  tt++;
  
  /* Parameter 'output_file_suffix' */
  /* ctype is 'char*' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = STRING_TYPE;
  tt->param_name = tdrpStrDup("output_file_suffix");
  tt->descr = tdrpStrDup("output file suffix");
  tt->help = tdrpStrDup("");
  tt->val_offset = (char *) &(pp.output_file_suffix) - (char *) &pp;
  tt->single_val.s = tdrpStrDup("mdv");
  tt++;
  
  /* Parameter 'instance' */
  /* ctype is 'char*' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = STRING_TYPE;
  tt->param_name = tdrpStrDup("instance");
  tt->descr = tdrpStrDup("instance of program ");
  tt->help = tdrpStrDup("");
  tt->val_offset = (char *) &(pp.instance) - (char *) &pp;
  tt->single_val.s = tdrpStrDup("G2M_Nexrad");
  tt++;
  
  /* Parameter 'input_dir' */
  /* ctype is 'char*' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = STRING_TYPE;
  tt->param_name = tdrpStrDup("input_dir");
  tt->descr = tdrpStrDup("Input File Directory (realtime mode only)");
  tt->help = tdrpStrDup("Directory which contains new files to convert.");
  tt->val_offset = (char *) &(pp.input_dir) - (char *) &pp;
  tt->single_val.s = tdrpStrDup("not_set");
  tt++;
  
  /* Parameter 'output_dir' */
  /* ctype is 'char*' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = STRING_TYPE;
  tt->param_name = tdrpStrDup("output_dir");
  tt->descr = tdrpStrDup("Output File directory (top directory)");
  tt->help = tdrpStrDup("Name of directory where mdv files will be placed.");
  tt->val_offset = (char *) &(pp.output_dir) - (char *) &pp;
  tt->single_val.s = tdrpStrDup("not_set");
  tt++;
  
  /* Parameter 'mode' */
  /* ctype is 'gint2mdv_mode_t' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = ENUM_TYPE;
  tt->param_name = tdrpStrDup("mode");
  tt->descr = tdrpStrDup("Operational Mode");
  tt->help = tdrpStrDup("Realtime mode waits for new data; archive mode funs on file list");
  tt->val_offset = (char *) &(pp.mode) - (char *) &pp;
  tt->enum_def.name = tdrpStrDup("mode_t");
  tt->enum_def.nfields = 2;
  tt->enum_def.fields = (enum_field_t *)
      tdrpMalloc(tt->enum_def.nfields * sizeof(enum_field_t));
    tt->enum_def.fields[0].name = tdrpStrDup("REALTIME");
    tt->enum_def.fields[0].val = REALTIME;
    tt->enum_def.fields[1].name = tdrpStrDup("ARCHIVE");
    tt->enum_def.fields[1].val = ARCHIVE;
  tt->single_val.e = REALTIME;
  tt++;
  
  /* Parameter 'data_source' */
  /* ctype is 'char*' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = STRING_TYPE;
  tt->param_name = tdrpStrDup("data_source");
  tt->descr = tdrpStrDup("Data Source");
  tt->help = tdrpStrDup("Data Source (ie. NIDS/LOT)");
  tt->val_offset = (char *) &(pp.data_source) - (char *) &pp;
  tt->single_val.s = tdrpStrDup("NIDS/LOT");
  tt++;
  
  /* Parameter 'max_input_data_age' */
  /* ctype is 'long' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = LONG_TYPE;
  tt->param_name = tdrpStrDup("max_input_data_age");
  tt->descr = tdrpStrDup("Maximum Age of Input Data (in seconds)");
  tt->help = tdrpStrDup("For realtime only - max age of input data for it to be valid");
  tt->val_offset = (char *) &(pp.max_input_data_age) - (char *) &pp;
  tt->has_min = TRUE;
  tt->min_val.l = 60;
  tt->single_val.l = 300;
  tt++;
  
  /* Parameter 'malloc_debug_level' */
  /* ctype is 'long' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = LONG_TYPE;
  tt->param_name = tdrpStrDup("malloc_debug_level");
  tt->descr = tdrpStrDup("Malloc debug level");
  tt->help = tdrpStrDup("0 - none, 1 - corruption checking, 2 - records all malloc blocks and checks, 3 - printout of all mallocs etc.");
  tt->val_offset = (char *) &(pp.malloc_debug_level) - (char *) &pp;
  tt->has_min = TRUE;
  tt->has_max = TRUE;
  tt->min_val.l = 0;
  tt->max_val.l = 3;
  tt->single_val.l = 0;
  tt++;
  
  /* Parameter 'output_encoding_type' */
  /* ctype is 'long' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = LONG_TYPE;
  tt->param_name = tdrpStrDup("output_encoding_type");
  tt->descr = tdrpStrDup("Output Encoding Type");
  tt->help = tdrpStrDup("0 - None (data written as unsigned char), 1 - URL 8bit encoding.");
  tt->val_offset = (char *) &(pp.output_encoding_type) - (char *) &pp;
  tt->has_min = TRUE;
  tt->has_max = TRUE;
  tt->min_val.l = 0;
  tt->max_val.l = 1;
  tt->single_val.l = 0;
  tt++;
  
  /* Parameter 'collection_type' */
  /* ctype is 'long' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = LONG_TYPE;
  tt->param_name = tdrpStrDup("collection_type");
  tt->descr = tdrpStrDup("Data Collection Type ");
  tt->help = tdrpStrDup("Options are: 0 - Measured, 1 - Extrapolated, 2 - Forecast, 3 - Synthesis, 4 - Mixed");
  tt->val_offset = (char *) &(pp.collection_type) - (char *) &pp;
  tt->has_min = TRUE;
  tt->has_max = TRUE;
  tt->min_val.l = 0;
  tt->max_val.l = 4;
  tt->single_val.l = 0;
  tt++;
  
  /* Parameter 'projection_type' */
  /* ctype is 'long' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = LONG_TYPE;
  tt->param_name = tdrpStrDup("projection_type");
  tt->descr = tdrpStrDup("Projection Type ");
  tt->help = tdrpStrDup("Options are: -1-Native, 0-Lat/Lon, 1-Artcc, 2-Stereographic, 3-Lambert conformal, 4-Mercator  5-Polar stereo, 6-Polar stereo elliptic, 7-Cylindrical equidist, 8-Flat (cartesian), 9-Shperical");
  tt->val_offset = (char *) &(pp.projection_type) - (char *) &pp;
  tt->has_min = TRUE;
  tt->has_max = TRUE;
  tt->min_val.l = -2;
  tt->max_val.l = 9;
  tt->single_val.l = -2;
  tt++;
  
  /* Parameter 'vertical_type' */
  /* ctype is 'long' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = LONG_TYPE;
  tt->param_name = tdrpStrDup("vertical_type");
  tt->descr = tdrpStrDup("Vertical Type ");
  tt->help = tdrpStrDup("Options are: 0-Unknown, 1-Surface, 2-sigma-p, 3-Pressure , 4-Z (Constant Altitude)  5-sigma-z , 6-eta , 7-theta, 8-Mixed , 9-Elevation, 10-Composite, 11-Cross-section, 12- satelite");
  tt->val_offset = (char *) &(pp.vertical_type) - (char *) &pp;
  tt->has_min = TRUE;
  tt->has_max = TRUE;
  tt->min_val.l = 0;
  tt->max_val.l = 12;
  tt->single_val.l = 4;
  tt++;
  
  /* Parameter 'sensor_latitude' */
  /* ctype is 'double' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = DOUBLE_TYPE;
  tt->param_name = tdrpStrDup("sensor_latitude");
  tt->descr = tdrpStrDup("Sensor Latitude ");
  tt->help = tdrpStrDup("Sensor Latitude (if different than what is in gint header)");
  tt->val_offset = (char *) &(pp.sensor_latitude) - (char *) &pp;
  tt->has_min = TRUE;
  tt->has_max = TRUE;
  tt->min_val.d = -90;
  tt->max_val.d = 90;
  tt->single_val.d = 0;
  tt++;
  
  /* Parameter 'sensor_longitude' */
  /* ctype is 'double' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = DOUBLE_TYPE;
  tt->param_name = tdrpStrDup("sensor_longitude");
  tt->descr = tdrpStrDup("Sensor Longitude ");
  tt->help = tdrpStrDup("Sensor Longitude (if different than what is in gint header)");
  tt->val_offset = (char *) &(pp.sensor_longitude) - (char *) &pp;
  tt->has_min = TRUE;
  tt->has_max = TRUE;
  tt->min_val.d = -180;
  tt->max_val.d = 180;
  tt->single_val.d = 0;
  tt++;
  
  /* Parameter 'sensor_altitude' */
  /* ctype is 'double' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = DOUBLE_TYPE;
  tt->param_name = tdrpStrDup("sensor_altitude");
  tt->descr = tdrpStrDup("Sensor Altitude (KM)");
  tt->help = tdrpStrDup("Sensor Altitude (in KM - not in gint header)");
  tt->val_offset = (char *) &(pp.sensor_altitude) - (char *) &pp;
  tt->has_min = TRUE;
  tt->min_val.d = 0;
  tt->single_val.d = 0;
  tt++;
  
  /* Parameter 'vert_parameter' */
  /* ctype is 'double' */
  
  memset(tt, 0, sizeof(TDRPtable));
  tt->ptype = DOUBLE_TYPE;
  tt->param_name = tdrpStrDup("vert_parameter");
  tt->descr = tdrpStrDup("Vertical Parameters ");
  tt->help = tdrpStrDup("Vertical Parameters (ie. for Elevation Angles - gint wrong)");
  tt->val_offset = (char *) &(pp.vert_parameter.val) - (char *) &pp;
  tt->len_offset = (char *) &(pp.vert_parameter.len) - (char *) &pp;
  tt->array_offset = (char *) &(pp._vert_parameter) - (char *) &pp;
  tt->array_n_offset = (char *) &(pp.vert_parameter_n) - (char *) &pp;
  tt->is_array = TRUE;
  tt->array_len_fixed = FALSE;
  tt->array_elem_size = sizeof(double);
  tt->array_n = 4;
  tt->array_vals = (tdrpVal_t *)
      tdrpMalloc(tt->array_n * sizeof(tdrpVal_t));
    tt->array_vals[0].d = 0;
    tt->array_vals[1].d = 0;
    tt->array_vals[2].d = 0;
    tt->array_vals[3].d = 0;
  tt++;
  
  /* trailing entry has param_name set to NULL */
  
  tt->param_name = NULL;
  
  return (Table);

}
