#
# Recursive make - makes the subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	Ascii2Radx \
	Dsr2Radx \
	FixCfradialPaths \
	FixRadxPointing \
	FixRadxValues \
	GroundEchoStats \
	Makefile \
	Radx2Dsr \
	Radx2Grid \
	RadxBeamBlock \
	RadxBufr \
	RadxCalUpdate \
	RadxCheck \
	RadxClutMon \
	RadxConvert \
	RadxCov2Mom \
	RadxCreateVol \
	RadxDiffFields \
	RadxDiffVol \
	RadxDwellCombine \
	RadxEvad \
	RadxFilter \
	RadxHca \
	RadxKdp \
	RadxMergeFields \
	RadxMergeVols \
	RadxModelQc \
	RadxMon \
	RadxPartRain \
	RadxPersistentClutter \
	RadxPid \
	RadxPrint \
	RadxQc \
	RadxQpe \
	RadxRate \
	RadxSunMon \
	RadxTest \
	RadxTimeMedian \
	TestRadxMsg

include $(RAP_MAKE_INC_DIR)/rap_make_recursive_dir_targets
