#! /bin/csh
#
# test_cidd:  Run this script from the Params Directory to test
# the lastest executable
#


foreach file ( CIDD.master *.CIDD) 

echo "--------------------------------------------------------"
echo "-                                                      -"
echo "-                                                      -"
echo "--------------------------------------------------------"
echo "-                                                      -"
echo "-                                                      -"
echo "--------------------------------------------------------"
echo "-                                                      -"
echo "                 $file                                  "
echo "-                                                      -"
echo "--------------------------------------------------------"
echo "-                                                      -"
echo "-                                                      -"
echo "--------------------------------------------------------"
echo "-                                                      -"
echo "-                                                      -"
echo "--------------------------------------------------------"

../CIDD -p $file

end
