#!/bin/sh
# not_running: returns 0 (true) if a process is not running, else 1 (false).
# Tres Hofmeister <tres@ncar.ucar.edu>  5/11/93
# Usage: running process

PATH=/bin:/usr/bin:/usr/ucb

prog=`basename $0`

if [ $# -ne 1 ]; then
    echo "Usage: $prog process" >&2
    exit 1
fi

# Is this BSD or SysV?
if [ -f /vmunix ]; then
    BSD="true"
fi

proc=$1

# Quote any '/' characters in the pattern.
pat=`echo "$proc" | sed 's%/%\\\/%g'`

# A process name is considered to start with either a space,
# `(', or `/', and end with a space, `)', or at end of line.
if [ "$BSD" ]; then
    pids=`ps axww | awk '/( |\(|\/)'"$pat"'( |\)|$)/ && \
	$0 !~ / awk |'$prog'/ {print $1}'`
else
    pids=`ps -ef  | awk '/( |\(|\/)'"$pat"'( |\)|$)/ && \
	$0 !~ / awk |'$prog'/ {print $2}'`
fi

# Do any processes match this pattern?
if [ "$pids" ]; then
    exit 1
else
    exit 0
fi
