# This file is generated by `guide' for project `cidd_gui.P'.
# It is to be included by the Makefile for project `cidd_gui.P'.

SOURCES.G += extras_pu.G fields_pu.G h_win.G movie_pu.G v_win.G data_pu.G zoom_pu.G save_pu.G over_pu.G 
STUBS.G += extras_pu.G fields_pu.G h_win.G movie_pu.G v_win.G data_pu.G zoom_pu.G save_pu.G over_pu.G 
