/*
 * save_pu_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `save_pu.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include <gcm.h>
#include "save_pu_ui.h"

/*
 * Initialize an instance of object `save_im_pu'.
 */
save_pu_save_im_pu_objects *
save_pu_save_im_pu_objects_initialize(ip, owner)
	save_pu_save_im_pu_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (save_pu_save_im_pu_objects *) calloc(1, sizeof (save_pu_save_im_pu_objects))))
		return (save_pu_save_im_pu_objects *) NULL;
	if (!ip->save_im_pu)
		ip->save_im_pu = save_pu_save_im_pu_save_im_pu_create(ip, owner);
	if (!ip->save_cp)
		ip->save_cp = save_pu_save_im_pu_save_cp_create(ip, ip->save_im_pu);
	if (!ip->dir_tx)
		ip->dir_tx = save_pu_save_im_pu_dir_tx_create(ip, ip->save_cp);
	if (!ip->fname_tx)
		ip->fname_tx = save_pu_save_im_pu_fname_tx_create(ip, ip->save_cp);
	if (!ip->cmd_tx)
		ip->cmd_tx = save_pu_save_im_pu_cmd_tx_create(ip, ip->save_cp);
	if (!ip->save_bt)
		ip->save_bt = save_pu_save_im_pu_save_bt_create(ip, ip->save_cp);
	if (!ip->cancel_bt)
		ip->cancel_bt = save_pu_save_im_pu_cancel_bt_create(ip, ip->save_cp);
	if (!ip->save_pu_msg)
		ip->save_pu_msg = save_pu_save_im_pu_save_pu_msg_create(ip, ip->save_cp);
	return ip;
}

/*
 * Create object `save_im_pu' in the specified instance.
 */
Xv_opaque
save_pu_save_im_pu_save_im_pu_create(ip, owner)
	save_pu_save_im_pu_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 409,
		XV_HEIGHT, 101,
		XV_LABEL, "Save CIDD Image",
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		FRAME_CMD_PUSHPIN_IN, TRUE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `save_cp' in the specified instance.
 */
Xv_opaque
save_pu_save_im_pu_save_cp_create(ip, owner)
	save_pu_save_im_pu_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	gcm_initialize_colors(obj, "Wheat", NULL);
	return obj;
}

/*
 * Create object `dir_tx' in the specified instance.
 */
Xv_opaque
save_pu_save_im_pu_dir_tx_create(ip, owner)
	save_pu_save_im_pu_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	set_dir_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 2,
		XV_Y, 8,
		PANEL_VALUE_DISPLAY_LENGTH, 40,
		PANEL_VALUE_STORED_LENGTH, 256,
		PANEL_LABEL_STRING, "Dir:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, set_dir_proc,
		NULL);
	return obj;
}

/*
 * Create object `fname_tx' in the specified instance.
 */
Xv_opaque
save_pu_save_im_pu_fname_tx_create(ip, owner)
	save_pu_save_im_pu_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	set_fname_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 2,
		XV_Y, 33,
		PANEL_VALUE_DISPLAY_LENGTH, 40,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "File:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, set_fname_proc,
		NULL);
	return obj;
}

/*
 * Create object `cmd_tx' in the specified instance.
 */
Xv_opaque
save_pu_save_im_pu_cmd_tx_create(ip, owner)
	save_pu_save_im_pu_objects	*ip;
	Xv_opaque	owner;
{
	extern Panel_setting	set_command_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 2,
		XV_Y, 58,
		PANEL_VALUE_DISPLAY_LENGTH, 40,
		PANEL_VALUE_STORED_LENGTH, 256,
		PANEL_LABEL_STRING, "Command:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, set_command_proc,
		NULL);
	return obj;
}

/*
 * Create object `save_bt' in the specified instance.
 */
Xv_opaque
save_pu_save_im_pu_save_bt_create(ip, owner)
	save_pu_save_im_pu_objects	*ip;
	Xv_opaque	owner;
{
	extern void		save_image_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 6,
		XV_Y, 76,
		PANEL_LABEL_STRING, "Save",
		PANEL_NOTIFY_PROC, save_image_proc,
		NULL);
	return obj;
}

/*
 * Create object `cancel_bt' in the specified instance.
 */
Xv_opaque
save_pu_save_im_pu_cancel_bt_create(ip, owner)
	save_pu_save_im_pu_objects	*ip;
	Xv_opaque	owner;
{
	extern void		cancel_save_proc();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 340,
		XV_Y, 78,
		PANEL_LABEL_STRING, "Cancel",
		PANEL_NOTIFY_PROC, cancel_save_proc,
		NULL);
	return obj;
}

/*
 * Create object `save_pu_msg' in the specified instance.
 */
Xv_opaque
save_pu_save_im_pu_save_pu_msg_create(ip, owner)
	save_pu_save_im_pu_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 58,
		XV_Y, 80,
		PANEL_LABEL_STRING, "Window Information goes here",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

