#!/bin/csh
# *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* 
# ** Copyright UCAR (c) 1992 - 2010 
# ** University Corporation for Atmospheric Research(UCAR) 
# ** National Center for Atmospheric Research(NCAR) 
# ** Research Applications Laboratory(RAL) 
# ** P.O.Box 3000, Boulder, Colorado, 80307-3000, USA 
# ** 2010/10/7 23:11:39 
# *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* 

echo Checking directory $1
#
# Find all param files in the directory that was passed in as
# an argument and run checkParamFile on them with the parameters
# specified in updateAllParams.params. Do not recurse into
# subdirectories or we wind up looking at CIDD map files,
# colorscales and CVS files. Niles Oien April 2006.
#
find $1 -maxdepth 1 -type f -exec ./checkParamFile -params updateAllParams.params -f {} \;

#
