#!/bin/csh
# *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* 
# ** Copyright UCAR (c) 1992 - 2010 
# ** University Corporation for Atmospheric Research(UCAR) 
# ** National Center for Atmospheric Research(NCAR) 
# ** Research Applications Laboratory(RAL) 
# ** P.O.Box 3000, Boulder, Colorado, 80307-3000, USA 
# ** 2010/10/7 23:11:39 
# *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* 
#
# Find all directories with the word 'params' in their name
# under the $PROJ_DIR directory and call the checkAllParamFilesDir
# with that directory as an argument. Niles Oien.
#
find $PROJ_DIR  -name \*params\* -type d -exec ./checkAllParamFilesDir {} \;

#
