#! /bin/bash

nice find . '(' -name '*~' -o -name 'junk*' \
         -o -name '*.i' -o -name a.out -o -name '*errlog' \
         -o -name 'TAGS' ')' \
         -user $USER -type f -print -exec \rm '{}' \;
