#!/bin/sh --
# *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* 
# ** Copyright UCAR (c) 1992 - 2010 
# ** University Corporation for Atmospheric Research(UCAR) 
# ** National Center for Atmospheric Research(NCAR) 
# ** Research Applications Laboratory(RAL) 
# ** P.O.Box 3000, Boulder, Colorado, 80307-3000, USA 
# ** 2010/10/7 23:11:38 
# *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=* 
# running: returns 0 (true) if a process is running, else 1 (false).
# Tres Hofmeister <tres@ncar.ucar.edu>
# Usage: running process
# 5/11/93.  Updated: Mon Jul 21 15:30:45 MDT 1997

PATH=/bin:/usr/bin:/usr/ucb

prog=`basename $0`

if [ $# -ne 1 ]; then
    echo "Usage: $prog process" >&2
    exit 1
fi

# Is this BSD or SysV?
if ps -x >/dev/null 2>&1; then
    BSD="true"
fi

proc=$1

# Quote any '/' characters in the pattern.
pat=`echo "$proc" | sed 's%/%\\\/%g'`

# A process name is considered to start with either a space,
# `(', or `/', and end with a space, `)', or at end of line.
if [ "$BSD" ]; then
    pids=`ps axww | awk '/( |\(|\/)'"$pat"'( |\)|$)/ && \
	$0 !~ / awk |'$prog'/ {print $1}'`
else
    pids=`ps -ef  | awk '/( |\(|\/)'"$pat"'( |\)|$)/ && \
	$0 !~ / awk |'$prog'/ {print $2}'`
fi

# Do any processes match this pattern?
if [ "$pids" ]; then
    exit 0
else
    exit 1
fi
