/*
 * eventman_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `eventman.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include "eventman_ui.h"


/*
 * Global object definitions.
 */
eventman_em_bw_objects	*Eventman_em_bw;

#ifdef MAIN

/*
 * Instance XV_KEY_DATA key.  An instance is a set of related
 * user interface objects.  A pointer to an object's instance
 * is stored under this key in every object.  This must be a
 * global variable.
 */
Attr_attribute	INSTANCE;

main(int argc, char **argv)
{
	/*
	 * Initialize XView.
	 */
	xv_init(XV_INIT_ARGC_PTR_ARGV, &argc, argv, NULL);
	INSTANCE = xv_unique_key();
	
	/*
	 * Initialize user interface components.
	 * Do NOT edit the object initializations by hand.
	 */
	Eventman_em_bw = eventman_em_bw_objects_initialize(NULL, NULL);
	
	
	/*
	 * Turn control over to XView.
	 */
	xv_main_loop(Eventman_em_bw->em_bw);
	exit(0);
}

#endif


/*
 * Notify callback function for `goto_bt'.
 */
void
goto_proc(Panel_item item, Event *event)
{
	eventman_em_bw_objects *ip = (eventman_em_bw_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("eventman: goto_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `add_bt'.
 */
void
add_proc(Panel_item item, Event *event)
{
	eventman_em_bw_objects *ip = (eventman_em_bw_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("eventman: add_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `del_bt'.
 */
void
del_proc(Panel_item item, Event *event)
{
	eventman_em_bw_objects *ip = (eventman_em_bw_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("eventman: del_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `mailto_bt'.
 */
void
mail_proc(Panel_item item, Event *event)
{
	eventman_em_bw_objects *ip = (eventman_em_bw_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("eventman: mail_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `save_bt'.
 */
void
save_proc(Panel_item item, Event *event)
{
	eventman_em_bw_objects *ip = (eventman_em_bw_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("eventman: save_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `close_bt'.
 */
void
close_proc(Panel_item item, Event *event)
{
	eventman_em_bw_objects *ip = (eventman_em_bw_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("eventman: close_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `event_list'.
 */
int
ev_list_proc(Panel_item item, char *string, Xv_opaque client_data, Panel_list_op op, Event *event, int row)
{
	eventman_em_bw_objects *ip = (eventman_em_bw_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch(op) {
	case PANEL_LIST_OP_DESELECT:
		fprintf(stderr, "eventman: ev_list_proc: PANEL_LIST_OP_DESELECT: %s\n",string);
		break;

	case PANEL_LIST_OP_SELECT:
		fprintf(stderr, "eventman: ev_list_proc: PANEL_LIST_OP_SELECT: %s\n",string);
		break;

	case PANEL_LIST_OP_VALIDATE:
		fprintf(stderr, "eventman: ev_list_proc: PANEL_LIST_OP_VALIDATE: %s\n",string);
		break;

	case PANEL_LIST_OP_DELETE:
		fprintf(stderr, "eventman: ev_list_proc: PANEL_LIST_OP_DELETE: %s\n",string);
		break;
	}
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return XV_OK;
}

/*
 * Notify callback function for `summary_tx'.
 */
Panel_setting
summary_proc(Panel_item item, Event *event)
{
	eventman_em_bw_objects *ip = (eventman_em_bw_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "eventman: summary_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `end_time_tx'.
 */
Panel_setting
end_time_proc(Panel_item item, Event *event)
{
	eventman_em_bw_objects *ip = (eventman_em_bw_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "eventman: end_time_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Event callback function for `em_tp'.
 */
Notify_value
comment_text_proc(Xv_window win, Event *event, Notify_arg arg, Notify_event_type type)
{
	eventman_em_bw_objects *ip = (eventman_em_bw_objects *) xv_get(xv_get(win, XV_OWNER), XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "eventman: comment_text_proc: event %d\n", event_id(event));
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return notify_next_event_func(win, (Notify_event) event, arg, type);
}

/*
 * Notify callback function for `date_tx'.
 */
Panel_setting
start_time_proc(Panel_item item, Event *event)
{
	eventman_em_bw_objects *ip = (eventman_em_bw_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "eventman: start_time_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `help_bt'.
 */
void
help_proc(Panel_item item, Event *event)
{
	eventman_em_bw_objects *ip = (eventman_em_bw_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("eventman: help_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `rt_bt'.
 */
void
gort_proc(Panel_item item, Event *event)
{
	eventman_em_bw_objects *ip = (eventman_em_bw_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("eventman: gort_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `fname_tx'.
 */
Panel_setting
load_file_proc(Panel_item item, Event *event)
{
	eventman_em_bw_objects *ip = (eventman_em_bw_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "eventman: load_file_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}
