#
# Recursive make - makes the subdirectory code
#

include $(LROSE_MAKE_INC_DIR)/lrose_make_macros

TARGETS = $(GENERAL_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	AcGeoref2Spdb \
	AcGeorefCompare \
	HawkEye \
	Hsrl2Radx \
	HsrlSim \
	HsrlTcp2Fmq

include $(LROSE_MAKE_INC_DIR)/lrose_make_recursive_dir_targets
