#
# Recursive make - makes the subdirectory code
#

include $(LROSE_MAKE_INC_DIR)/lrose_make_macros

TARGETS = $(GENERAL_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	CalCompute \
	DsrGrabber \
	DsrMerge \
	DualDopplerLobes \
	HawkEye \
	IntfRemove \
	Mdv2Vad \
	MdvFold \
	RadarCal \
	RadarConst \
	SweepInfo2Spdb \
	VertCompute
        
include $(LROSE_MAKE_INC_DIR)/lrose_make_recursive_dir_targets
