/*
 * draw_pu_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `draw_pu.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include "cidd_gui.h"


/*
 * Notify callback function for `type_st'.
 */
void
select_draw_type_proc(Panel_item item, int value, Event *event)
{
	draw_pu_draw_pu_objects *ip = (draw_pu_draw_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "cidd_gui: select_draw_type_proc: value: %u\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `ok_bt'.
 */
void
draw_ok_proc(Panel_item item, Event *event)
{
	draw_pu_draw_pu_objects *ip = (draw_pu_draw_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("cidd_gui: draw_ok_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `cancel_bt'.
 */
void
draw_cancel_proc(Panel_item item, Event *event)
{
	draw_pu_draw_pu_objects *ip = (draw_pu_draw_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("cidd_gui: draw_cancel_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `serialno_tx'.
 */
Panel_setting
draw_serialno_proc(Panel_item item, Event *event)
{
	draw_pu_draw_pu_objects *ip = (draw_pu_draw_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	int	value = (int) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: draw_serialno_proc: value: %d\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `validtm_tx'.
 */
Panel_setting
draw_validtm_proc(Panel_item item, Event *event)
{
	draw_pu_draw_pu_objects *ip = (draw_pu_draw_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: draw_validtm_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `label_tx'.
 */
Panel_setting
draw_label_proc(Panel_item item, Event *event)
{
	draw_pu_draw_pu_objects *ip = (draw_pu_draw_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: draw_label_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `url_tx'.
 */
Panel_setting
draw_url_proc(Panel_item item, Event *event)
{
	draw_pu_draw_pu_objects *ip = (draw_pu_draw_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: draw_url_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `time_tx'.
 */
Panel_setting
set_draw_time_proc(Panel_item item, Event *event)
{
	draw_pu_draw_pu_objects *ip = (draw_pu_draw_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	char *	value = (char *) xv_get(item, PANEL_VALUE);
	
	fprintf(stderr, "cidd_gui: set_draw_time_proc: value: %s\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

	return panel_text_notify(item, event);
}

/*
 * Notify callback function for `delete_bt'.
 */
void
delete_draw_proc(Panel_item item, Event *event)
{
	draw_pu_draw_pu_objects *ip = (draw_pu_draw_pu_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fputs("cidd_gui: delete_draw_proc\n", stderr);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */
	/* gxv_end_connections */

}
