#
# Recursive make - makes the subdirectory code
#

include $(LROSE_CORE_DIR)/build/make_include/lrose_make_macros

TARGETS = $(GENERAL_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	AcGeoref2Spdb \
	AcGeorefCompare \
	AltCpCompute \
	AparTsPrint \
	AparTsSim \
	AparTs2Moments \
	CalCompute \
	CedricPrint \
	ChillCal2Xml \
	ChillSdb2CalXml \
	ChillSdb2Dsr \
	ChillSdbServer \
	ChillTsFile2Fmq \
	ChillTsTcp2Fmq \
	CmdVerify \
	Cov2Mom \
	DowSendFreq \
	DsrGrabber \
	DsrMerge \
	DualDopplerLobes \
	HawkEye \
	HcrTempRxGain \
	HcrVelCorrect \
	Hsrl2Radx \
	IntfRemove \
	Iq2Dsr \
	KinGin2Ncf \
	Mdv2Vad \
	MdvFold \
	MdvRadarShear \
	NexradPowerStats \
	PointingCpCompute \
	PowerInfo2Spdb \
	Qmap2Cidd \
	QuadratureTest \
	RadarCal \
	RadarConst \
	RadarMdvCompare \
	RadxDealias \
	RapMap2Chill \
	SimCpCompute \
	SpectraPrint \
	StaggeredLimits \
	SunCal \
	SunCpCompute \
	SweepInfo2Spdb \
	Ts2NetCDF \
	TsCalAuto \
	TsConvert \
	TsFile2Fmq \
	TsFmq2Tcp \
	TsGamic2Iwrf \
	TsMerge \
	TsOverlay \
	TsPrint \
	TsRefract2Dsr \
	TsScanInfoMerge \
	TsSim \
	TsSmartSave \
	TsStatusMonitor \
	TsTcp2File \
	TsTcp2Fmq \
	TsTimeFix \
	UfRadarPrint \
	VertCompute \
	ZdrCalSimHv

include $(LROSE_CORE_DIR)/build/make_include/lrose_make_recursive_dir_targets
