#
# Recursive make - makes the subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	AcGeoref2Spdb \
	AcGeorefCompare \
	AltCpCompute \
	CP2Udp2Fmq \
	CalCompute \
	CedricPrint \
	ChillCal2Xml \
	ChillSdb2CalXml \
	ChillSdb2Dsr \
	ChillSdbServer \
	ChillTsFile2Fmq \
	ChillTsTcp2Fmq \
	CmdVerify \
	Cov2Mom \
	DowSendFreq \
	Dsr2CP2Mom \
	DsrGrabber \
	DsrMerge \
	DualDopplerLobes \
	HawkEye \
	HcrVelCorrect \
	IntfRemove \
	Iq2Dsr \
	KinGin2Ncf \
	Mdv2Vad \
	MdvFold \
	MdvRadarShear \
	NexradPowerStats \
	PointingCpCompute \
	PowerInfo2Spdb \
	Qmap2Cidd \
	QuadratureTest \
	RadarCal \
	RadarConst \
	RadarMdvCompare \
	RapMap2Chill \
	SimCpCompute \
	SpectraPrint \
	StaggeredLimits \
	SunCpCompute \
	SweepInfo2Spdb \
	Ts2NetCDF \
	TsCalAuto \
	TsConvert \
	TsFile2Fmq \
	TsFmq2Tcp \
        TsGamic2Iwrf \
	TsMerge \
	TsOverlay \
	TsPrint \
	TsRefract2Dsr \
	TsScanInfoMerge \
	TsSim \
	TsSmartSave \
	TsStatusMonitor \
	TsTcp2File \
	TsTcp2Fmq \
	TsTimeFix \
	UfRadarPrint \
	VertCompute \
	ZdrCalSimHv

# Temporarily removed - add in after sync with RAL

# MdvPartRain
# PartRain
# SunCal


include $(RAP_MAKE_INC_DIR)/rap_make_recursive_dir_targets
