###########################################################################
#
# Makefile for ttest program
#
# Mike Dixon, RAP, NCAR, Boulder, CO, 80307, USA
#
# Feb 2009
#
###########################################################################

include $(LROSE_CORE_DIR)/build/make_include/lrose_make_macros

TARGET_FILE = ttest

LOC_INCLUDES =
LOC_CFLAGS =
LOC_LDFLAGS =
LOC_LIBS = -ltoolsa -ldataport

HDRS =

SRCS = \
	ttest.c

#
# standard targets
#

include $(LROSE_CORE_DIR)/build/make_include/lrose_make_c_targets

#
# local targets
#

# DO NOT DELETE THIS LINE -- make depend depends on it.
