#!/usr/bin/perl

use strict;
use vars qw($opt_h $opt_d $opt_v $opt_c $opt_D $opt_r $opt_p);
use Getopt::Std;
no warnings "uninitialized";
no locale;

(my $prog = $0) =~ s%.*/%%;
my ($jadePath, $cvsArgs);

#...------------...Usage Info...--------------------------------

$opt_h = $opt_d = $opt_v = 0;
my $usage = <<EOF;
Usage: $prog [-dv] [-[D|r]c cvs_options] -p path_to_jade_project
  -h  Help:     Print out this usage information.
  -d  Debug:    Print out minimal debug information.
  -v  Verbose:  Print out verbose debug information.
  -c  cvs_options:  Any tags to pass on to cvs checkout commands
  -D  date checkout: The cvs args are a date to use for checkout
  -r  tag checkout: The cvs args are a tag to use for checkout
  -p  path_to_jade_project:    relative path to jade project for checkout
  NOTE: If -D or -r are specified, -c is REQUIRED; otherwise -c is ignored
  expects standard input to be parsed so redirect a file to STDIN if need be.
EOF

#...------------...Sanity check the options...------------------

&getopts('hdvc:Drp:') || die $usage;
if ($opt_h) {
  print STDOUT "Got opt_h\n";
  die $usage 
}

unless ($opt_p) {
  print STDOUT "Error: no opt_p\n";
  die $usage;
}

my $verbose = 1 if $opt_v;
my $debug = 1 if ($opt_d || $verbose);
my $do_cvs_arg = "True" if $opt_c;
my $do_date_co = "True" if $opt_D;
my $do_tag_co = "True" if $opt_r;
my $printFlag = 1 if $opt_p;

if ( ($opt_D || $opt_r) && !($opt_c) ) {
  print STDOUT "Error: -D or -r used, so -c is required!\n";
  die $usage;
}

if ($opt_c) {
    # ($cvsArgs, $blah) = $opt_c =~ /.*/;
    ($cvsArgs = $opt_c) =~ /.*/;
    print STDOUT "Got cvs args: $cvsArgs\n" if $verbose;
}

if ($opt_p) {
    # ($jadePath) = $opt_p =~ /.*/;
    ($jadePath = $opt_p) =~ /.*/;
    print STDOUT "Got jade path: $jadePath\n" if $verbose;
}

my $cvsarg = $cvsArgs;

if ($opt_D) {
    print STDOUT "Checking out $jadePath using revision date: $cvsArgs\n";
    $cvsarg = "-P -D $cvsArgs";
}
elsif ($opt_r) {
    print STDOUT "Checking out $jadePath using revision tag: $cvsArgs\n";
    $cvsarg = "-P -r $cvsArgs";
}
else {
    print STDOUT "Checking out current build of $jadePath\n";
    $cvsarg = "-P";
}

# die if (1 == 1);

system("cvs co $cvsarg $jadePath/build.xml");
system("cvs co $cvsarg java/src/edu/ucar/rap/ant/");
system("cvs co $cvsarg java/src/edu/ucar/rap/jade/build.xml");
system("cvs co $cvsarg java/src/edu/ucar/rap/jade/extensions/build.xml");


